#ifndef HOLO_BASE_MSG_GEOMETRY_BOX_IDL_
#define HOLO_BASE_MSG_GEOMETRY_BOX_IDL_

#include <holo_base_msg/core/Types.idl>
#include <holo_base_msg/geometry/Pose.idl>

module holo_base_msg { module geometry {

struct Box2f
{
    holo_base_msg::core::float32_t  width;
    holo_base_msg::core::float32_t  height;
    holo_base_msg::geometry::Pose2f pose;
};

struct Box2d
{
    holo_base_msg::core::float64_t  width;
    holo_base_msg::core::float64_t  height;
    holo_base_msg::geometry::Pose2d pose;
};

struct Box3f
{
    holo_base_msg::core::float32_t  width;
    holo_base_msg::core::float32_t  height;
    holo_base_msg::core::float32_t  depth;
    holo_base_msg::geometry::Pose3f pose;
};

struct Box3d
{
    holo_base_msg::core::float64_t  width;
    holo_base_msg::core::float64_t  height;
    holo_base_msg::core::float64_t  depth;
    holo_base_msg::geometry::Pose3d pose;
};

}; };

#endif
