#ifndef HOLO_BASE_MSG_GEOMETRY_ROT_IDL_
#define HOLO_BASE_MSG_GEOMETRY_ROT_IDL_

#include <holo_base_msg/core/Types.idl>

module holo_base_msg { module geometry {

struct Rot2f
{
    holo_base_msg::core::float32_t theta;  // angle in radian
};

struct Rot2d
{
    holo_base_msg::core::float64_t theta;  // angle in radian
};

struct Rot3f
{
    holo_base_msg::core::float32_t  x;
    holo_base_msg::core::float32_t  y;
    holo_base_msg::core::float32_t  z;
    holo_base_msg::core::float32_t  w;
};

struct Rot3d
{
    holo_base_msg::core::float64_t  x;
    holo_base_msg::core::float64_t  y;
    holo_base_msg::core::float64_t  z;
    holo_base_msg::core::float64_t  w;
};

}; };

#endif

