base: BaseCamp/Library/master
projects:
  holo_perception_pilot:
    url: ${git_url}/per/holo_perception_pilot.git
    branch: dragonglass-master
    dependencies:
    - holo_3rdparty
    - holo_base
    - holo_perception_base
    - holo_dnn
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_perception_pilot/cmw_app:
    url: holo_perception_pilot/cmw_app
    dependencies:
    - holo_base
    - holo_base_msg
    - holo_perception_base
    - holo_perception_pilot
    - holo_cmw
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_planning_pilot:
    url: ${git_url}/pc/holo_planning_pilot.git
    branch: dragonglass-master
    dependencies:
    - holo_base
    - holo_planning_base
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_planning_pilot/cmw_app:
    url: holo_planning_pilot/cmw_app
    dependencies:
    - holo_planning_pilot
    - holo_base_msg
    - holo_cmw
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_control:
    url: ${git_url}/pc/holo_control.git
    branch: dragonglass-master
    dependencies:
    - holo_base
    - holo_control_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_control/cmw_app:
    url: holo_control/cmw_app
    dependencies:
    - holo_control
    - holo_cmw
    - holo_base_msg
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_fusion_cmw_app:
    url: ${git_url}/mlc/holo_localization_fusion_cmw_app.git
    branch: dragonglass-master
    dependencies:
    - holo_cmw
    - holo_base_msg
    - holo_localization_fusion
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_vision_cmw_app:
    url: ${git_url}/mlc/holo_localization_vision_cmw_app.git
    branch: dragonglass-master
    dependencies:
    - holo_cmw
    - holo_base_msg
    - holo_localization_vision
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_map_cmw_app:
    url: ${git_url}/map/holo_map_cmw_app.git
    branch: dragonglass-master
    dependencies:
    - holo_base
    - holo_base_msg
    - holo_cmw
    - holo_map_base
    - holo_map_format
    - holo_map_common
    - holo_map_core
    commands:
      doc:
        command: make
        arguments:
        - doc
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_sensors/cmw_app:
    url: holo_sensors/cmw_app
    dependencies:
    - holo_sensors
    - holo_cmw
    - holo_base_msg
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_prediction:
    url: ${git_url}/pc/holo_prediction.git
    branch: dragonglass-master
    dependencies:
    - holo_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_prediction/cmw_app:
    url: holo_prediction/cmw_app
    dependencies:
    - holo_prediction
    - holo_base_msg
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  odm:
    url: ${git_url}/fun/odm.git
    branch: dragonglass-master
    dependencies:
    - holo_base
    - holo_cmw
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  odm/cmw_app:
    url: odm/cmw_app
    dependencies:
    - odm
    - holo_cmw
    - holo_base_msg
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_hmi:
    url: ${git_url}/base/holo_hmi.git
    branch: dragonglass-master
    dependencies:
    - holo_base
    - holo_sensors
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_hmi/cmw_app:
    url: holo_hmi/cmw_app
    dependencies:
    - holo_hmi
    - holo_sensors
    - holo_cmw
    - holo_base_msg
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_daemon:
    url: ${git_url}/win/holo_daemon.git
    branch: dragonglass-develop
    dependencies:
    - holo_base
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_daemon/cmw_app:
    url: holo_daemon/cmw_app
    dependencies:
    - holo_daemon
    - holo_cmw
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  PilotApps:
    dependencies:
    - holo_perception_pilot/cmw_app
    - holo_planning_pilot/cmw_app
    - holo_localization_fusion_cmw_app
    - holo_localization_vision_cmw_app
    - holo_map_cmw_app
    - holo_sensors/cmw_app
    - holo_prediction/cmw_app
    - odm/cmw_app
    - holo_hmi/cmw_app
    - holo_daemon/cmw_app
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
  Pilot:
    dependencies:
    - BaseCamp
    - PilotApps
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
version: 1
