base: BaseCamp/Library/release/2021.12
projects:
  holo_map_adapter/cmw_app:
    url: holo_map_adapter/cmw_app
    branch: release/v0.5
    dependencies:
    - CS
    - MAP
    commands:
      configure:
        arguments:
          - ${SOURCE_ROOT}
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_cmw:
    commands:
      configure:
        arguments_tda4_qnx-7.0.0:
        - -DHOLO_CMW_BUILD_DDS_MICRO_WRAPPER=ON
        - -DHOLO_CMW_BUILD_OPENDDS_WRAPPER=OFF
        - ${SOURCE_ROOT}
        arguments_tda4_ubuntu-18.04:
        - -DHOLO_CMW_BUILD_OPENDDS_WRAPPER=ON
        - ${SOURCE_ROOT}
        arguments_x86_64_ubuntu-18.04:
        - -DHOLO_CMW_BUILD_DDS_MICRO_WRAPPER=ON
        - -DHOLO_CMW_BUILD_OPENDDS_WRAPPER=OFF
        - ${SOURCE_ROOT}
        arguments_x86_64_ubuntu-18.04-base:
        - -DHOLO_CMW_BUILD_DDS_MICRO_WRAPPER=ON
        - -DHOLO_CMW_BUILD_OPENDDS_WRAPPER=OFF
        - ${SOURCE_ROOT}
    steps: null
  holo_map_local_service_server:
    url: ${git_url}/map/holo_map_local_service_server.git
    branch: release/v0.5
    dependencies:
    - CS
    - MAP
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_map_local_service_client/tools:
    url: holo_map_local_service_client/tools
    branch: release/v0.5
    dependencies:
    - CS
    - MAP
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  BaseCampMapApplication:
    dependencies:
    - holo_map_adapter/cmw_app
    - holo_map_local_service_server
    - holo_map_local_service_client/tools
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
  holo_localization_fusion_cmw_app:
    url: ${git_url}/mlc/holo_localization_fusion_cmw_app.git
    branch: release/v0.5
    dependencies:
    - CS
    - MLC
    - MAP
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_vision_cmw_app:
    url: ${git_url}/mlc/holo_localization_vision_cmw_app.git
    branch: release/v0.2
    dependencies:
    - CS
    - MLC
    - VS
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_calibration:
    url: ${git_url}/mlc/holo_calibration.git
    branch: release/v0.4
    dependencies:
    - BaseCamp
    - holo_localization_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_calibration_cmw_app:
    url: ${git_url}/mlc/holo_calibration_cmw_app.git
    branch: release/v0.4
    dependencies:
    - holo_cmw
    - holo_calibration
    commands:
      configure:
        arguments:
        - ${SOURCE_ROOT}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  BaseCampMlcApplication:
    dependencies:
    - holo_localization_fusion_cmw_app
    - holo_localization_vision_cmw_app
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
  holo_sensors_cmw_app:
    url: ${git_url}/vs/holo_sensors_cmw_app.git
    branch: release/v0.6
    dependencies:
    - CS
    - VS
    commands:
      configure:
        command: 'cmake'
        arguments:
        - ${SOURCE_ROOT}
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  BaseCampVsApplication:
    dependencies:
    - holo_sensors_cmw_app
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
  holo_dnn_base/apps:
    url: holo_dnn_base/apps
    dependencies:
    - PER
    dependencies_MDC610-1.0.012-B0120000.B011:
    - PER
    - holo_dnn_mdc
    dependencies_MDC610-1.0.017-T.B011:
    - PER
    - holo_dnn_mdc
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_perception_pilot:
    url: ${git_url}/per/holo_perception_pilot.git
    branch: release/v0.5
    dependencies:
    - PER
    - holo_dnn_base/apps
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_perception_pilot/cmw_app:
    url: holo_perception_pilot/cmw_app
    dependencies:
    - PER
    - VS
    - holo_perception_pilot
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  BaseCampPerApplication:
    dependencies:
    - holo_perception_pilot/cmw_app
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
  holo_control_cmw_app:
    url: ${git_url}/bcpc/holo_control_cmw_app.git
    branch: release/v0.5
    dependencies:
    - CS
    - PC
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  BaseCampPcApplication:
    dependencies:
    - holo_control_cmw_app
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
  BaseCampApplication:
    dependencies:
    - BaseCampMapApplication
    - BaseCampMlcApplication
    - BaseCampVsApplication
    - BaseCampPerApplication
    - BaseCampPcApplication
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
version: 1
