base: HoloParking/HPA/GH01/develop
projects:
  holo_cmw:
    commands:
      configure:
        arguments:
        - -DHOLO_CMW_BUILD_ROS_WRAPPER=OFF
        - -DHOLO_CMW_BUILD_OPENDDS_WRAPPER=OFF
        - -DHOLO_CMW_BUILD_UMB_WRAPPER=OFF
        - -DHOLO_CMW_BUILD_DDS_MICRO_WRAPPER=ON
        - ${SOURCE_ROOT}
    steps: null

  holo_x_client:
      url: ${git_url}/~gaochengbin/holo_x_client.git
      dependencies: [holo_cmw, holo_base_msg, holo_sensors_base,holo_parking_msg]
      branch: zgg/holo_cmw2_dds_micro
