base: BaseCamp/Library/CS/develop
projects:
  holo_perception_base:
    url: ${git_url}/per/holo_perception_base.git
    branch: dragonglass-develop
    dependencies:
    - CS
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_dnn_base:
    url: ${git_url}/bcper/holo_dnn_base.git
    branch: dragonglass-develop
    dependencies:
    - holo_perception_base
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_dnn_mdc:
    url: ${git_url}/per/holo_dnn_mdc.git
    branch: dragonglass-develop
    dependencies:
    - holo_dnn_base
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_perception_3d:
    url: ${git_url}/bcper/holo_perception_3d.git
    branch: dragonglass-develop
    dependencies:
    - holo_perception_base
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  PER:
    dependencies:
    - holo_perception_base
    - holo_dnn_base
    - holo_perception_3d
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
version: 1
