base: HoloParking/HPA/GH01/develop
projects:
  holo_x_client:
    url: ${git_url}/sim/holo_x_client.git
    branch: gsl/pps_develop_20211201
    dependencies:
    - holo_cmw
    - holo_base_msg
    - holo_sensors_base
    - holo_parking_msg
    commands:
      configure:
        arguments:
        - -DUSE_PPS_WRAPPER=ON
        - ${SOURCE_ROOT}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
