#ifndef HOLO_PARKING_MSG_CONTROL_APA_CONTROL_COMMAND_IDL_
#define HOLO_PARKING_MSG_CONTROL_APA_CONTROL_COMMAND_IDL_

#include <holo_parking_msg/common/Common.idl>

module holo_parking_msg { module control {

#pragma DCPS_DATA_TYPE "holo_parking_msg::control::ApaControlCommand"
struct ApaControlCommand
{
    holo_parking_msg::common::Timestamp   timestamp;
    holo_parking_msg::core::bool_t        lon_auto_mode;
    holo_parking_msg::core::uint8_t       target_gear_request;
    holo_parking_msg::core::float32_t     stop_dist_request;
    holo_parking_msg::core::float32_t     speed_limit_request;
    holo_parking_msg::core::uint8_t       apafail_brkmode_request;
    holo_parking_msg::core::bool_t        steer_auto_mode;
    holo_parking_msg::core::float32_t     steering_angle;
};

}; };

#endif