base: BaseCamp/Library/develop
projects:
  cmw_wrapper_example:
    url: ${git_url}/cmw/cmw_wrapper_example.git
    branch: master
    dependencies:
    - holo_cmw
    - holo_base_msg
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
version: 1
