base: BaseCamp/Application/GH01/release/2022.03
projects:
  holo_map_navigator:
    url: ${git_url}/map/holo_map_navigator.git
    branch: release/GH01/R4/HPP
    dependencies:
    - BaseCampApplication
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_map_parking:
    url: ${git_url}/parking/holo_map_parking.git
    branch: release/GH01/R4/HPP
    dependencies:
    - holo_map_navigator
    - holo_io
    - holo_parking_base
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_map_parking/tools:
    url: holo_map_parking/tools
    branch: release/GH01/R4/HPP
    dependencies:
    - holo_map_parking
    - holo_parking_msg
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_io:
    url: ${git_url}/base/holo_io.git
    branch:  release/GH01/R4/HPP
    dependencies:
    - BaseCampApplication
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_parking_base:
    url: ${git_url}/parking/holo_parking_base.git
    branch:  release/GH01/R4/HPP
    dependencies:
    - BaseCampApplication
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_parking_msg:
    url: ${git_url}/parking/holo_parking_msg.git
    branch:  GH01-A58-develop
    dependencies:
    - holo_parking_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  # TODO: holo_dnn_base & holo_dnn_base/apps & holo_dnn_tda4 has CycularDependencyError
  holo_dnn_tda4:
    url:  ${git_url}/bcper/holo_dnn_tda4.git
    branch:  release/GH01/R4/HPP
    dependencies:
    - holo_dnn_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_perception_parking:
    url: ${git_url}/parking/holo_perception_parking.git
    branch:  release/GH01/R4/HPP
    dependencies:
    - BaseCampApplication
    - holo_parking_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_parking:
    url: ${git_url}/parking/holo_localization_parking.git
    branch:  release/GH01/R4/HPP
    dependencies:
    - BaseCampApplication
    - holo_io
    - holo_parking_base
    commands:
      configure:
        arguments_tda4_qnx-7.0.0:
        - -DHOLO_LOCALIZATION_BUILD_WITH_TIDL=ON
        - ${SOURCE_ROOT}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_planning_parking:
    url: ${git_url}/parking/holo_planning_parking.git
    branch:  release/GH01/R4/HPP
    dependencies:
    - BaseCampApplication
    - holo_io
    - holo_parking_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_parking_cmw_app:
    url: ${git_url}/parking/holo_parking_cmw_app.git
    branch:  release/GH01/R4/HPP
    dependencies:
    - holo_parking_msg
    - holo_localization_parking
    - holo_perception_parking
    - holo_planning_parking
    commands:
      configure:
        arguments:
        - -DHOLO_BUILD_PARKING_APP=ON
        - ${SOURCE_ROOT}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_map_parking_cmw_app:
    url: ${git_url}/bcmap/holo_map_parking_cmw_app.git
    branch:  release/GH01/R4/HPP
    dependencies:
    - BaseCampApplication
    - holo_map_navigator
    - holo_parking_msg
    commands:
      configure:
        arguments:
        - -DHOLO_BUILD_PARKING_MSG=ON
        - ${SOURCE_ROOT}
        arguments_tda4_qnx-7.0.0:
        - -DHOLO_BUILD_PARKING_MSG=ON
        - ${SOURCE_ROOT}
        arguments_x86_64_ubuntu-18.04:
        - -DHOLO_BUILD_PARKING_MSG=OFF
        - ${SOURCE_ROOT}
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_map_parking_cmw_app/tools:
    url: holo_map_parking_cmw_app/tools
    branch:  release/GH01/R4/HPP
    dependencies:
    - holo_map_parking_cmw_app
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_x_client:
    url: ${git_url}/sim/holo_x_client.git
    branch:  release/GH01/R4/HPP
    dependencies:
    - BaseCampApplication
    - holo_parking_msg
    - holo_io
    commands:
      configure:
        arguments:
        - -DUSE_PPS_WRAPPER=ON
        - -DHOLO_BUILD_GH01_A58=ON
        - ${SOURCE_ROOT}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_bag:
    url: ${git_url}/win/holo_bag.git
    branch:  release/GH01/R4/HPP
    dependencies:
    - BaseCampApplication
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_bag/cmw_app:
    url: holo_bag/cmw_app
    dependencies:
    - holo_bag
    - holo_parking_msg
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_winterfell:
    url: ${git_url}/win/holo_winterfell.git
    branch:  GH01-A58-develop
    dependencies:
    - BaseCampApplication
    - holo_bag
    - holo_parking_base
    commands:
      configure:
        arguments:
        - -DHOLO_BUILD_ON_TDA4=ON
        - ${SOURCE_ROOT}
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_winterfell/cmw_app:
    url: holo_winterfell/cmw_app
    dependencies:
    - holo_winterfell
    - holo_parking_msg
    commands:
      configure:
        arguments:
        - -DHOLO_BUILD_ON_TDA4=ON
        - ${SOURCE_ROOT}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_params:
    url: ${git_url}/vs/holo_params.git
    branch:  release/GH01/R4/HPP
    commands:
      configure:
        command: 'cmake'
        arguments:
        - -DVID=gh01-1
        - ${SOURCE_ROOT}
        retcode: [0]
    steps:
        - configure
        - build
        - install
    package:
        manifest: ${BUILD_ROOT}/install_manifest.txt
        files: []
        directories: []
  ParkingApps:
    dependencies_x86_64_ubuntu-18.04:
    - holo_parking_cmw_app
    - holo_map_parking_cmw_app
    - holo_x_client
    - holo_params
    dependencies_tda4_qnx-7.0.0:
    - holo_parking_cmw_app
    - holo_map_parking_cmw_app
    - holo_x_client
    - holo_bag/cmw_app
    - holo_params
    - holo_winterfell/cmw_app
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
  ParkingHpp:
    dependencies:
    - ParkingApps
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
version: 1
