// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p19
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:152

#ifndef _TAO_IDL__HOME_YUEPF_DOCUMENTS_CODE_APA_PROJECT_BUILD_TDA4_UBUNTU_18_04_DEBUG_HOLO_PARKING_MSG_INCLUDE_HOLO_PARKING_MSG_VISION_POINTFEATUREFLISTTYPESUPPORTC_6K7VCV_H_
#define _TAO_IDL__HOME_YUEPF_DOCUMENTS_CODE_APA_PROJECT_BUILD_TDA4_UBUNTU_18_04_DEBUG_HOLO_PARKING_MSG_INCLUDE_HOLO_PARKING_MSG_VISION_POINTFEATUREFLISTTYPESUPPORTC_6K7VCV_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "dds/DCPS/ZeroCopyInfoSeq_T.h"
#include "dds/DCPS/ZeroCopySeq_T.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "PointFeaturefListC.h"
#include "dds/DdsDcpsInfrastructureC.h"
#include "dds/DdsDcpsPublicationC.h"
#include "dds/DdsDcpsSubscriptionExtC.h"
#include "dds/DdsDcpsTopicC.h"
#include "dds/DdsDcpsTypeSupportExtC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 2 || TAO_BETA_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:38

namespace holo_parking_msg
{

  // TAO_IDL - Generated from
  // be/be_visitor_module/module_ch.cpp:38

  namespace vision
  {

    // TAO_IDL - Generated from
    // be/be_visitor_sequence/sequence_ch.cpp:102

    typedef ::TAO::DCPS::ZeroCopyDataSeq< holo_parking_msg::vision::PointFeaturefList, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> PointFeaturefListSeq;
    

    // TAO_IDL - Generated from
    // be/be_visitor_typecode/typecode_decl.cpp:37

    extern  ::CORBA::TypeCode_ptr const _tc_PointFeaturefListSeq;

    // TAO_IDL - Generated from
    // be/be_interface.cpp:751

#if !defined (_HOLO_PARKING_MSG_VISION_POINTFEATUREFLISTTYPESUPPORT__VAR_OUT_CH_)
#define _HOLO_PARKING_MSG_VISION_POINTFEATUREFLISTTYPESUPPORT__VAR_OUT_CH_

    class PointFeaturefListTypeSupport;
    typedef PointFeaturefListTypeSupport *PointFeaturefListTypeSupport_ptr;

    typedef
      TAO_Objref_Var_T<
          PointFeaturefListTypeSupport
        >
      PointFeaturefListTypeSupport_var;
    
    typedef
      TAO_Objref_Out_T<
          PointFeaturefListTypeSupport
        >
      PointFeaturefListTypeSupport_out;

#endif /* end #if !defined */

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:43

    class  PointFeaturefListTypeSupport
      : public virtual ::OpenDDS::DCPS::TypeSupport
    
    {
    public:

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      typedef PointFeaturefListTypeSupport_ptr _ptr_type;
      typedef PointFeaturefListTypeSupport_var _var_type;
      typedef PointFeaturefListTypeSupport_out _out_type;

      static void _tao_any_destructor (void *);

      // The static operations.
      static PointFeaturefListTypeSupport_ptr _duplicate (PointFeaturefListTypeSupport_ptr obj);

      static void _tao_release (PointFeaturefListTypeSupport_ptr obj);

      static PointFeaturefListTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
      static PointFeaturefListTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
      static PointFeaturefListTypeSupport_ptr _nil (void);

      // TAO_IDL - Generated from
      // be/be_visitor_interface/interface_ch.cpp:140

      virtual ::CORBA::Boolean _is_a (const char *type_id);
      virtual const char* _interface_repository_id (void) const;
      virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
    
    protected:
      // Abstract or local interface only.
      PointFeaturefListTypeSupport (void);

      

      virtual ~PointFeaturefListTypeSupport (void);
    
    private:
      // Private and unimplemented for concrete interfaces.
      ACE_UNIMPLEMENTED_FUNC (PointFeaturefListTypeSupport (const PointFeaturefListTypeSupport &))
#if defined (ACE_HAS_CPP11)
      ACE_UNIMPLEMENTED_FUNC (PointFeaturefListTypeSupport (PointFeaturefListTypeSupport &&))
#endif /* ACE_HAS_CPP11 */
      ACE_UNIMPLEMENTED_FUNC (PointFeaturefListTypeSupport &operator= (const PointFeaturefListTypeSupport &))
#if defined (ACE_HAS_CPP11)
      ACE_UNIMPLEMENTED_FUNC (PointFeaturefListTypeSupport &operator= (PointFeaturefListTypeSupport &&))
#endif /* ACE_HAS_CPP11 */
    };

    // TAO_IDL - Generated from
    // be/be_visitor_typecode/typecode_decl.cpp:37

    extern  ::CORBA::TypeCode_ptr const _tc_PointFeaturefListTypeSupport;

    // TAO_IDL - Generated from
    // be/be_interface.cpp:751

#if !defined (_HOLO_PARKING_MSG_VISION_POINTFEATUREFLISTDATAWRITER__VAR_OUT_CH_)
#define _HOLO_PARKING_MSG_VISION_POINTFEATUREFLISTDATAWRITER__VAR_OUT_CH_

    class PointFeaturefListDataWriter;
    typedef PointFeaturefListDataWriter *PointFeaturefListDataWriter_ptr;

    typedef
      TAO_Objref_Var_T<
          PointFeaturefListDataWriter
        >
      PointFeaturefListDataWriter_var;
    
    typedef
      TAO_Objref_Out_T<
          PointFeaturefListDataWriter
        >
      PointFeaturefListDataWriter_out;

#endif /* end #if !defined */

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:43

    class  PointFeaturefListDataWriter
      : public virtual ::DDS::DataWriter
    
    {
    public:

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      typedef PointFeaturefListDataWriter_ptr _ptr_type;
      typedef PointFeaturefListDataWriter_var _var_type;
      typedef PointFeaturefListDataWriter_out _out_type;

      static void _tao_any_destructor (void *);

      // The static operations.
      static PointFeaturefListDataWriter_ptr _duplicate (PointFeaturefListDataWriter_ptr obj);

      static void _tao_release (PointFeaturefListDataWriter_ptr obj);

      static PointFeaturefListDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
      static PointFeaturefListDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
      static PointFeaturefListDataWriter_ptr _nil (void);

      virtual ::DDS::InstanceHandle_t register_instance (
        const ::holo_parking_msg::vision::PointFeaturefList & instance) = 0;

      virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
        const ::holo_parking_msg::vision::PointFeaturefList & instance,
        const ::DDS::Time_t & timestamp) = 0;

      virtual ::DDS::ReturnCode_t unregister_instance (
        const ::holo_parking_msg::vision::PointFeaturefList & instance,
        ::DDS::InstanceHandle_t handle) = 0;

      virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
        const ::holo_parking_msg::vision::PointFeaturefList & instance,
        ::DDS::InstanceHandle_t handle,
        const ::DDS::Time_t & timestamp) = 0;

      virtual ::DDS::ReturnCode_t write (
        const ::holo_parking_msg::vision::PointFeaturefList & instance_data,
        ::DDS::InstanceHandle_t handle) = 0;

      virtual ::DDS::ReturnCode_t write_w_timestamp (
        const ::holo_parking_msg::vision::PointFeaturefList & instance_data,
        ::DDS::InstanceHandle_t handle,
        const ::DDS::Time_t & source_timestamp) = 0;

      virtual ::DDS::ReturnCode_t dispose (
        const ::holo_parking_msg::vision::PointFeaturefList & instance_data,
        ::DDS::InstanceHandle_t instance_handle) = 0;

      virtual ::DDS::ReturnCode_t dispose_w_timestamp (
        const ::holo_parking_msg::vision::PointFeaturefList & instance_data,
        ::DDS::InstanceHandle_t instance_handle,
        const ::DDS::Time_t & source_timestamp) = 0;

      virtual ::DDS::ReturnCode_t get_key_value (
        ::holo_parking_msg::vision::PointFeaturefList & key_holder,
        ::DDS::InstanceHandle_t handle) = 0;

      virtual ::DDS::InstanceHandle_t lookup_instance (
        const ::holo_parking_msg::vision::PointFeaturefList & instance_data) = 0;

      // TAO_IDL - Generated from
      // be/be_visitor_interface/interface_ch.cpp:140

      virtual ::CORBA::Boolean _is_a (const char *type_id);
      virtual const char* _interface_repository_id (void) const;
      virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
    
    protected:
      // Abstract or local interface only.
      PointFeaturefListDataWriter (void);

      

      virtual ~PointFeaturefListDataWriter (void);
    
    private:
      // Private and unimplemented for concrete interfaces.
      ACE_UNIMPLEMENTED_FUNC (PointFeaturefListDataWriter (const PointFeaturefListDataWriter &))
#if defined (ACE_HAS_CPP11)
      ACE_UNIMPLEMENTED_FUNC (PointFeaturefListDataWriter (PointFeaturefListDataWriter &&))
#endif /* ACE_HAS_CPP11 */
      ACE_UNIMPLEMENTED_FUNC (PointFeaturefListDataWriter &operator= (const PointFeaturefListDataWriter &))
#if defined (ACE_HAS_CPP11)
      ACE_UNIMPLEMENTED_FUNC (PointFeaturefListDataWriter &operator= (PointFeaturefListDataWriter &&))
#endif /* ACE_HAS_CPP11 */
    };

    // TAO_IDL - Generated from
    // be/be_visitor_typecode/typecode_decl.cpp:37

    extern  ::CORBA::TypeCode_ptr const _tc_PointFeaturefListDataWriter;

    // TAO_IDL - Generated from
    // be/be_interface.cpp:751

#if !defined (_HOLO_PARKING_MSG_VISION_POINTFEATUREFLISTDATAREADER__VAR_OUT_CH_)
#define _HOLO_PARKING_MSG_VISION_POINTFEATUREFLISTDATAREADER__VAR_OUT_CH_

    class PointFeaturefListDataReader;
    typedef PointFeaturefListDataReader *PointFeaturefListDataReader_ptr;

    typedef
      TAO_Objref_Var_T<
          PointFeaturefListDataReader
        >
      PointFeaturefListDataReader_var;
    
    typedef
      TAO_Objref_Out_T<
          PointFeaturefListDataReader
        >
      PointFeaturefListDataReader_out;

#endif /* end #if !defined */

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:43

    class  PointFeaturefListDataReader
      : public virtual ::OpenDDS::DCPS::DataReaderEx
    
    {
    public:

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      typedef PointFeaturefListDataReader_ptr _ptr_type;
      typedef PointFeaturefListDataReader_var _var_type;
      typedef PointFeaturefListDataReader_out _out_type;

      static void _tao_any_destructor (void *);

      // The static operations.
      static PointFeaturefListDataReader_ptr _duplicate (PointFeaturefListDataReader_ptr obj);

      static void _tao_release (PointFeaturefListDataReader_ptr obj);

      static PointFeaturefListDataReader_ptr _narrow (::CORBA::Object_ptr obj);
      static PointFeaturefListDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
      static PointFeaturefListDataReader_ptr _nil (void);

      virtual ::DDS::ReturnCode_t read (
        ::holo_parking_msg::vision::PointFeaturefListSeq & received_data,
        ::DDS::SampleInfoSeq & info_seq,
        ::CORBA::Long max_samples,
        ::DDS::SampleStateMask sample_states,
        ::DDS::ViewStateMask view_states,
        ::DDS::InstanceStateMask instance_states) = 0;

      virtual ::DDS::ReturnCode_t take (
        ::holo_parking_msg::vision::PointFeaturefListSeq & received_data,
        ::DDS::SampleInfoSeq & info_seq,
        ::CORBA::Long max_samples,
        ::DDS::SampleStateMask sample_states,
        ::DDS::ViewStateMask view_states,
        ::DDS::InstanceStateMask instance_states) = 0;

      virtual ::DDS::ReturnCode_t read_w_condition (
        ::holo_parking_msg::vision::PointFeaturefListSeq & data_values,
        ::DDS::SampleInfoSeq & sample_infos,
        ::CORBA::Long max_samples,
        ::DDS::ReadCondition_ptr a_condition) = 0;

      virtual ::DDS::ReturnCode_t take_w_condition (
        ::holo_parking_msg::vision::PointFeaturefListSeq & data_values,
        ::DDS::SampleInfoSeq & sample_infos,
        ::CORBA::Long max_samples,
        ::DDS::ReadCondition_ptr a_condition) = 0;

      virtual ::DDS::ReturnCode_t read_next_sample (
        ::holo_parking_msg::vision::PointFeaturefList & received_data,
        ::DDS::SampleInfo & sample_info) = 0;

      virtual ::DDS::ReturnCode_t take_next_sample (
        ::holo_parking_msg::vision::PointFeaturefList & received_data,
        ::DDS::SampleInfo & sample_info) = 0;

      virtual ::DDS::ReturnCode_t read_instance (
        ::holo_parking_msg::vision::PointFeaturefListSeq & received_data,
        ::DDS::SampleInfoSeq & info_seq,
        ::CORBA::Long max_samples,
        ::DDS::InstanceHandle_t a_handle,
        ::DDS::SampleStateMask sample_states,
        ::DDS::ViewStateMask view_states,
        ::DDS::InstanceStateMask instance_states) = 0;

      virtual ::DDS::ReturnCode_t take_instance (
        ::holo_parking_msg::vision::PointFeaturefListSeq & received_data,
        ::DDS::SampleInfoSeq & info_seq,
        ::CORBA::Long max_samples,
        ::DDS::InstanceHandle_t a_handle,
        ::DDS::SampleStateMask sample_states,
        ::DDS::ViewStateMask view_states,
        ::DDS::InstanceStateMask instance_states) = 0;

      virtual ::DDS::ReturnCode_t read_instance_w_condition (
        ::holo_parking_msg::vision::PointFeaturefListSeq & received_data,
        ::DDS::SampleInfoSeq & sample_infos,
        ::CORBA::Long max_samples,
        ::DDS::InstanceHandle_t a_handle,
        ::DDS::ReadCondition_ptr a_condition) = 0;

      virtual ::DDS::ReturnCode_t take_instance_w_condition (
        ::holo_parking_msg::vision::PointFeaturefListSeq & received_data,
        ::DDS::SampleInfoSeq & sample_infos,
        ::CORBA::Long max_samples,
        ::DDS::InstanceHandle_t a_handle,
        ::DDS::ReadCondition_ptr a_condition) = 0;

      virtual ::DDS::ReturnCode_t read_next_instance (
        ::holo_parking_msg::vision::PointFeaturefListSeq & received_data,
        ::DDS::SampleInfoSeq & info_seq,
        ::CORBA::Long max_samples,
        ::DDS::InstanceHandle_t a_handle,
        ::DDS::SampleStateMask sample_states,
        ::DDS::ViewStateMask view_states,
        ::DDS::InstanceStateMask instance_states) = 0;

      virtual ::DDS::ReturnCode_t take_next_instance (
        ::holo_parking_msg::vision::PointFeaturefListSeq & received_data,
        ::DDS::SampleInfoSeq & info_seq,
        ::CORBA::Long max_samples,
        ::DDS::InstanceHandle_t a_handle,
        ::DDS::SampleStateMask sample_states,
        ::DDS::ViewStateMask view_states,
        ::DDS::InstanceStateMask instance_states) = 0;

      virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
        ::holo_parking_msg::vision::PointFeaturefListSeq & data_values,
        ::DDS::SampleInfoSeq & sample_infos,
        ::CORBA::Long max_samples,
        ::DDS::InstanceHandle_t previous_handle,
        ::DDS::ReadCondition_ptr a_condition) = 0;

      virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
        ::holo_parking_msg::vision::PointFeaturefListSeq & data_values,
        ::DDS::SampleInfoSeq & sample_infos,
        ::CORBA::Long max_samples,
        ::DDS::InstanceHandle_t previous_handle,
        ::DDS::ReadCondition_ptr a_condition) = 0;

      virtual ::DDS::ReturnCode_t return_loan (
        ::holo_parking_msg::vision::PointFeaturefListSeq & received_data,
        ::DDS::SampleInfoSeq & info_seq) = 0;

      virtual ::DDS::ReturnCode_t get_key_value (
        ::holo_parking_msg::vision::PointFeaturefList & key_holder,
        ::DDS::InstanceHandle_t handle) = 0;

      virtual ::DDS::InstanceHandle_t lookup_instance (
        const ::holo_parking_msg::vision::PointFeaturefList & instance_data) = 0;

      // TAO_IDL - Generated from
      // be/be_visitor_interface/interface_ch.cpp:140

      virtual ::CORBA::Boolean _is_a (const char *type_id);
      virtual const char* _interface_repository_id (void) const;
      virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
    
    protected:
      // Abstract or local interface only.
      PointFeaturefListDataReader (void);

      

      virtual ~PointFeaturefListDataReader (void);
    
    private:
      // Private and unimplemented for concrete interfaces.
      ACE_UNIMPLEMENTED_FUNC (PointFeaturefListDataReader (const PointFeaturefListDataReader &))
#if defined (ACE_HAS_CPP11)
      ACE_UNIMPLEMENTED_FUNC (PointFeaturefListDataReader (PointFeaturefListDataReader &&))
#endif /* ACE_HAS_CPP11 */
      ACE_UNIMPLEMENTED_FUNC (PointFeaturefListDataReader &operator= (const PointFeaturefListDataReader &))
#if defined (ACE_HAS_CPP11)
      ACE_UNIMPLEMENTED_FUNC (PointFeaturefListDataReader &operator= (PointFeaturefListDataReader &&))
#endif /* ACE_HAS_CPP11 */
    };

    // TAO_IDL - Generated from
    // be/be_visitor_typecode/typecode_decl.cpp:37

    extern  ::CORBA::TypeCode_ptr const _tc_PointFeaturefListDataReader;
  
  // TAO_IDL - Generated from
  // be/be_visitor_module/module_ch.cpp:67
  
  } // module holo_parking_msg::vision

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:67

} // module holo_parking_msg

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:62

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_HOLO_PARKING_MSG_VISION_POINTFEATUREFLISTTYPESUPPORT__TRAITS_)
#define _HOLO_PARKING_MSG_VISION_POINTFEATUREFLISTTYPESUPPORT__TRAITS_

  template<>
  struct  Objref_Traits< ::holo_parking_msg::vision::PointFeaturefListTypeSupport>
  {
    static ::holo_parking_msg::vision::PointFeaturefListTypeSupport_ptr duplicate (
        ::holo_parking_msg::vision::PointFeaturefListTypeSupport_ptr p);
    static void release (
        ::holo_parking_msg::vision::PointFeaturefListTypeSupport_ptr p);
    static ::holo_parking_msg::vision::PointFeaturefListTypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::holo_parking_msg::vision::PointFeaturefListTypeSupport_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_HOLO_PARKING_MSG_VISION_POINTFEATUREFLISTDATAWRITER__TRAITS_)
#define _HOLO_PARKING_MSG_VISION_POINTFEATUREFLISTDATAWRITER__TRAITS_

  template<>
  struct  Objref_Traits< ::holo_parking_msg::vision::PointFeaturefListDataWriter>
  {
    static ::holo_parking_msg::vision::PointFeaturefListDataWriter_ptr duplicate (
        ::holo_parking_msg::vision::PointFeaturefListDataWriter_ptr p);
    static void release (
        ::holo_parking_msg::vision::PointFeaturefListDataWriter_ptr p);
    static ::holo_parking_msg::vision::PointFeaturefListDataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::holo_parking_msg::vision::PointFeaturefListDataWriter_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_HOLO_PARKING_MSG_VISION_POINTFEATUREFLISTDATAREADER__TRAITS_)
#define _HOLO_PARKING_MSG_VISION_POINTFEATUREFLISTDATAREADER__TRAITS_

  template<>
  struct  Objref_Traits< ::holo_parking_msg::vision::PointFeaturefListDataReader>
  {
    static ::holo_parking_msg::vision::PointFeaturefListDataReader_ptr duplicate (
        ::holo_parking_msg::vision::PointFeaturefListDataReader_ptr p);
    static void release (
        ::holo_parking_msg::vision::PointFeaturefListDataReader_ptr p);
    static ::holo_parking_msg::vision::PointFeaturefListDataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::holo_parking_msg::vision::PointFeaturefListDataReader_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_ch.cpp:44



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace holo_parking_msg
{
  
  namespace vision
  {
     void operator<<= ( ::CORBA::Any &, PointFeaturefListTypeSupport_ptr); // copying
     void operator<<= ( ::CORBA::Any &, PointFeaturefListTypeSupport_ptr *); // non-copying
     ::CORBA::Boolean operator>>= (const ::CORBA::Any &, PointFeaturefListTypeSupport_ptr &);
  }
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, holo_parking_msg::vision::PointFeaturefListTypeSupport_ptr); // copying
 void operator<<= (::CORBA::Any &, holo_parking_msg::vision::PointFeaturefListTypeSupport_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, holo_parking_msg::vision::PointFeaturefListTypeSupport_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_ch.cpp:44



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace holo_parking_msg
{
  
  namespace vision
  {
     void operator<<= ( ::CORBA::Any &, PointFeaturefListDataWriter_ptr); // copying
     void operator<<= ( ::CORBA::Any &, PointFeaturefListDataWriter_ptr *); // non-copying
     ::CORBA::Boolean operator>>= (const ::CORBA::Any &, PointFeaturefListDataWriter_ptr &);
  }
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, holo_parking_msg::vision::PointFeaturefListDataWriter_ptr); // copying
 void operator<<= (::CORBA::Any &, holo_parking_msg::vision::PointFeaturefListDataWriter_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, holo_parking_msg::vision::PointFeaturefListDataWriter_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_ch.cpp:44



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace holo_parking_msg
{
  
  namespace vision
  {
     void operator<<= ( ::CORBA::Any &, PointFeaturefListDataReader_ptr); // copying
     void operator<<= ( ::CORBA::Any &, PointFeaturefListDataReader_ptr *); // non-copying
     ::CORBA::Boolean operator>>= (const ::CORBA::Any &, PointFeaturefListDataReader_ptr &);
  }
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, holo_parking_msg::vision::PointFeaturefListDataReader_ptr); // copying
 void operator<<= (::CORBA::Any &, holo_parking_msg::vision::PointFeaturefListDataReader_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, holo_parking_msg::vision::PointFeaturefListDataReader_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_codegen.cpp:1703
#if defined (__ACE_INLINE__)
#include "PointFeaturefListTypeSupportC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

