/* -*- C++ -*- */
/* Generated by /home/yuepf/Documents/code/Apa_Project/output/tda4_ubuntu-18.04/debug/host/bin/opendds_idl version 3.16 (ACE version 6.2a_p19) running on input file /home/yuepf/Documents/code/Apa_Project/src/holo_parking_msg/opendds_msg/message/holo_parking_msg/vision/PointFeaturefList.idl */
#ifndef OPENDDS_IDL_GENERATED_POINTFEATUREFLISTTYPESUPPORTIMPL_H_CC7Q4W
#define OPENDDS_IDL_GENERATED_POINTFEATUREFLISTTYPESUPPORTIMPL_H_CC7Q4W
#include "PointFeaturefListC.h"
#include "dds/DCPS/Definitions.h"
#include "dds/DdsDcpsC.h"
#include "dds/Version.h"
#if DDS_MAJOR_VERSION != 3 || DDS_MINOR_VERSION != 16 || DDS_MICRO_VERSION != 0
#error This file should be regenerated with opendds_idl
#endif
#include "PointFeaturefListTypeSupportC.h"
#include "dds/DCPS/Serializer.h"
#include "dds/DCPS/TypeSupportImpl.h"
#include "dds/DCPS/ValueWriter.h"
#include "dds/DCPS/XTypes/TypeObject.h"
#include "holo_parking_msg/common/CommonC.h"
#include "holo_parking_msg/vision/PointFeaturefC.h"
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL



/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin MODULE: OpenDDS */


/* End MODULE: OpenDDS */


/* Begin MODULE: holo_parking_msg */



/* Begin MODULE: core */



/* Begin TYPEDEF: bool_t */


/* End TYPEDEF: bool_t */


/* Begin TYPEDEF: char_t */


/* End TYPEDEF: char_t */


/* Begin TYPEDEF: _cxx_wchar_t */


/* End TYPEDEF: _cxx_wchar_t */


/* Begin TYPEDEF: int8_t */


/* End TYPEDEF: int8_t */


/* Begin TYPEDEF: uint8_t */


/* End TYPEDEF: uint8_t */


/* Begin TYPEDEF: int16_t */


/* End TYPEDEF: int16_t */


/* Begin TYPEDEF: uint16_t */


/* End TYPEDEF: uint16_t */


/* Begin TYPEDEF: int32_t */


/* End TYPEDEF: int32_t */


/* Begin TYPEDEF: uint32_t */


/* End TYPEDEF: uint32_t */


/* Begin TYPEDEF: int64_t */


/* End TYPEDEF: int64_t */


/* Begin TYPEDEF: uint64_t */


/* End TYPEDEF: uint64_t */


/* Begin TYPEDEF: float32_t */


/* End TYPEDEF: float32_t */


/* Begin TYPEDEF: float64_t */


/* End TYPEDEF: float64_t */


/* Begin TYPEDEF: BoolSequence */


/* End TYPEDEF: BoolSequence */


/* Begin TYPEDEF: CharSequence */


/* End TYPEDEF: CharSequence */


/* Begin TYPEDEF: WcharSequence */


/* End TYPEDEF: WcharSequence */


/* Begin TYPEDEF: Int8Sequence */


/* End TYPEDEF: Int8Sequence */


/* Begin TYPEDEF: Uint8Sequence */


/* End TYPEDEF: Uint8Sequence */


/* Begin TYPEDEF: Int16Sequence */


/* End TYPEDEF: Int16Sequence */


/* Begin TYPEDEF: Uint16Sequence */


/* End TYPEDEF: Uint16Sequence */


/* Begin TYPEDEF: Int32Sequence */


/* End TYPEDEF: Int32Sequence */


/* Begin TYPEDEF: Uint32Sequence */


/* End TYPEDEF: Uint32Sequence */


/* Begin TYPEDEF: Int64Sequence */


/* End TYPEDEF: Int64Sequence */


/* Begin TYPEDEF: Uint64Sequence */


/* End TYPEDEF: Uint64Sequence */


/* Begin TYPEDEF: Float32Sequence */


/* End TYPEDEF: Float32Sequence */


/* Begin TYPEDEF: Float64Sequence */


/* End TYPEDEF: Float64Sequence */

/* End MODULE: core */

/* End MODULE: holo_parking_msg */


/* Begin MODULE: holo_parking_msg */



/* Begin MODULE: common */



/* Begin TYPEDEF: SensorId */


/* End TYPEDEF: SensorId */


/* Begin STRUCT: Timestamp */


/* End STRUCT: Timestamp */

/* End MODULE: common */

/* End MODULE: holo_parking_msg */


/* Begin MODULE: holo_parking_msg */



/* Begin MODULE: vision */



/* Begin TYPEDEF: float32_t */


/* End TYPEDEF: float32_t */


/* Begin TYPEDEF: DescriptorType */


/* End TYPEDEF: DescriptorType */


/* Begin STRUCT: PointFeaturef */


/* End STRUCT: PointFeaturef */

/* End MODULE: vision */

/* End MODULE: holo_parking_msg */


/* Begin MODULE: holo_parking_msg */



/* Begin MODULE: vision */



/* Begin TYPEDEF: SensorId */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

struct holo_parking_msg_vision_SensorId_xtag {};
template<> const XTypes::TypeIdentifier & getMinimalTypeIdentifier<holo_parking_msg_vision_SensorId_xtag>();

template<> const XTypes::TypeMap& getMinimalTypeMap<holo_parking_msg_vision_SensorId_xtag>();

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End TYPEDEF: SensorId */


/* Begin TYPEDEF: Timestamp */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

struct holo_parking_msg_vision_Timestamp_xtag {};
template<> const XTypes::TypeIdentifier & getMinimalTypeIdentifier<holo_parking_msg_vision_Timestamp_xtag>();

template<> const XTypes::TypeMap& getMinimalTypeMap<holo_parking_msg_vision_Timestamp_xtag>();

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End TYPEDEF: Timestamp */


/* Begin TYPEDEF: PointFeaturefVector */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

void serialized_size(const Encoding& encoding, size_t& size, const holo_parking_msg::vision::PointFeaturefVector& seq);

bool operator<<(Serializer& strm, const holo_parking_msg::vision::PointFeaturefVector& seq);

bool operator>>(Serializer& strm, holo_parking_msg::vision::PointFeaturefVector& seq);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

bool gen_skip_over(Serializer& ser, holo_parking_msg::vision::PointFeaturefVector*);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

struct holo_parking_msg_vision_PointFeaturefVector_xtag {};
template<> const XTypes::TypeIdentifier & getMinimalTypeIdentifier<holo_parking_msg_vision_PointFeaturefVector_xtag>();

template<> const XTypes::TypeMap& getMinimalTypeMap<holo_parking_msg_vision_PointFeaturefVector_xtag>();

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End TYPEDEF: PointFeaturefVector */


/* Begin STRUCT: PointFeaturefList */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

void set_default(holo_parking_msg::vision::PointFeaturefList& stru);

void serialized_size(const Encoding& encoding, size_t& size, const holo_parking_msg::vision::PointFeaturefList& stru);

bool operator<<(Serializer& strm, const holo_parking_msg::vision::PointFeaturefList& stru);

bool operator>>(Serializer& strm, holo_parking_msg::vision::PointFeaturefList& stru);

void serialized_size(const Encoding& encoding, size_t& size, const NestedKeyOnly<const holo_parking_msg::vision::PointFeaturefList>& stru);

bool operator<<(Serializer& strm, const NestedKeyOnly<const holo_parking_msg::vision::PointFeaturefList>& stru);

bool operator>>(Serializer& strm, const NestedKeyOnly<holo_parking_msg::vision::PointFeaturefList>& stru);

template <>
struct MarshalTraits<holo_parking_msg::vision::PointFeaturefList> {
  static void representations_allowed_by_type(DDS::DataRepresentationIdSeq& seq)
  {
    seq.length(3);
    seq[0] = DDS::XCDR_DATA_REPRESENTATION;
    seq[1] = DDS::XCDR2_DATA_REPRESENTATION;
    seq[2] = DDS::XML_DATA_REPRESENTATION;
  }

  static SerializedSizeBound serialized_size_bound(const Encoding& encoding)
  {
    switch (encoding.kind()) {
    case Encoding::KIND_UNALIGNED_CDR:
      return SerializedSizeBound();
    case Encoding::KIND_XCDR1:
      return SerializedSizeBound();
    case Encoding::KIND_XCDR2:
      return SerializedSizeBound();
    default:
      OPENDDS_ASSERT(false);
      return SerializedSizeBound();
    }
  }

  static SerializedSizeBound key_only_serialized_size_bound(const Encoding& encoding)
  {
    switch (encoding.kind()) {
    case Encoding::KIND_UNALIGNED_CDR:
      return SerializedSizeBound(0);
    case Encoding::KIND_XCDR1:
      return SerializedSizeBound();
    case Encoding::KIND_XCDR2:
      return SerializedSizeBound();
    default:
      OPENDDS_ASSERT(false);
      return SerializedSizeBound();
    }
  }

  static bool to_message_block(ACE_Message_Block&, const holo_parking_msg::vision::PointFeaturefList&) { return false; }
  static bool from_message_block(holo_parking_msg::vision::PointFeaturefList&, const ACE_Message_Block&) { return false; }
  static Extensibility extensibility() { return APPENDABLE; }
  static Extensibility max_extensibility_level() { return APPENDABLE; }
};
void serialized_size(const Encoding& encoding, size_t& size, const KeyOnly<const holo_parking_msg::vision::PointFeaturefList> stru);

bool operator<<(Serializer& strm, KeyOnly<const holo_parking_msg::vision::PointFeaturefList> stru);

bool operator>>(Serializer& strm, KeyOnly<holo_parking_msg::vision::PointFeaturefList> stru);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace holo_parking_msg {
namespace vision {
/// This structure supports use of std::map with one or more keys.
struct  PointFeaturefList_OpenDDS_KeyLessThan {
  bool operator()(const holo_parking_msg::vision::PointFeaturefList&, const holo_parking_msg::vision::PointFeaturefList&) const
  {
    // With no keys, return false to allow use of
    // map with just one entry
    return false;
  }
};
}
}

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

void vwrite(OpenDDS::DCPS::ValueWriter& value_writer, const holo_parking_msg::vision::PointFeaturefList& value);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace holo_parking_msg {
namespace vision {
class PointFeaturefListTypeSupportImpl;
}
}

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS {
namespace DCPS {
template <>
struct DDSTraits<holo_parking_msg::vision::PointFeaturefList> {
  typedef holo_parking_msg::vision::PointFeaturefList MessageType;
  typedef holo_parking_msg::vision::PointFeaturefListSeq MessageSequenceType;
  typedef holo_parking_msg::vision::PointFeaturefListTypeSupport TypeSupportType;
  typedef holo_parking_msg::vision::PointFeaturefListTypeSupportImpl TypeSupportTypeImpl;
  typedef holo_parking_msg::vision::PointFeaturefListDataWriter DataWriterType;
  typedef holo_parking_msg::vision::PointFeaturefListDataReader DataReaderType;
  typedef holo_parking_msg::vision::PointFeaturefList_OpenDDS_KeyLessThan LessThanType;
  typedef OpenDDS::DCPS::KeyOnly<const holo_parking_msg::vision::PointFeaturefList> KeyOnlyType;

  static const char* type_name() { return "holo_parking_msg::vision::PointFeaturefList"; }
  static bool gen_has_key() { return false; }
  static size_t key_count() { return 0; }
};
} // namespace DCPS
} // namespace OpenDDS
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace holo_parking_msg {
namespace vision {
class  PointFeaturefListTypeSupportImpl
  : public virtual OpenDDS::DCPS::LocalObject<PointFeaturefListTypeSupport>
  , public virtual OpenDDS::DCPS::TypeSupportImpl
{
public:
  typedef OpenDDS::DCPS::DDSTraits<PointFeaturefList> TraitsType;
  typedef OpenDDS::DCPS::MarshalTraits<PointFeaturefList> MarshalTraitsType;
  typedef PointFeaturefListTypeSupport TypeSupportType;
  typedef PointFeaturefListTypeSupport::_var_type _var_type;
  typedef PointFeaturefListTypeSupport::_ptr_type _ptr_type;

  PointFeaturefListTypeSupportImpl() {}
  virtual ~PointFeaturefListTypeSupportImpl() {}

  virtual ::DDS::DataWriter_ptr create_datawriter();
  virtual ::DDS::DataReader_ptr create_datareader();
#ifndef OPENDDS_NO_MULTI_TOPIC
  virtual ::DDS::DataReader_ptr create_multitopic_datareader();
#endif /* !OPENDDS_NO_MULTI_TOPIC */
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
  virtual const OpenDDS::DCPS::MetaStruct& getMetaStructForType();
#endif /* !OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE */
  virtual bool has_dcps_key();
  const char* default_type_name() const;

  void representations_allowed_by_type(::DDS::DataRepresentationIdSeq& seq);

  virtual const OpenDDS::XTypes::TypeIdentifier& getMinimalTypeIdentifier() const;
  virtual const OpenDDS::XTypes::TypeMap& getMinimalTypeMap() const;

  virtual OpenDDS::DCPS::Extensibility getExtensibility() const;

  static PointFeaturefListTypeSupport::_ptr_type _narrow(CORBA::Object_ptr obj);
};
}
}

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

class MetaStruct;

template<typename T>
const MetaStruct& getMetaStruct();

template<>
const MetaStruct& getMetaStruct<holo_parking_msg::vision::PointFeaturefList>();
bool gen_skip_over(Serializer& ser, holo_parking_msg::vision::PointFeaturefList*);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

struct holo_parking_msg_vision_PointFeaturefList_xtag {};
template<> const XTypes::TypeIdentifier & getMinimalTypeIdentifier<holo_parking_msg_vision_PointFeaturefList_xtag>();

template<> const XTypes::TypeMap& getMinimalTypeMap<holo_parking_msg_vision_PointFeaturefList_xtag>();

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End STRUCT: PointFeaturefList */

/* End MODULE: vision */

/* End MODULE: holo_parking_msg */
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif /* OPENDDS_IDL_GENERATED_POINTFEATUREFLISTTYPESUPPORTIMPL_H_CC7Q4W */
