#ifndef HOLO_BASE_MSG_OPENDDS_MSG_TRAITS_H_
#define HOLO_BASE_MSG_OPENDDS_MSG_TRAITS_H_

#include "common/apa_control_command_traits.h"
#include "common/app_status_traits.h"
#include "common/control_traits.h"
#include "common/cpu_states_traits.h"
#include "common/ddt_traits.h"
#include "common/extrinsic_traits.h"
#include "common/freespace_traits.h"
#include "common/gnss_traits.h"
#include "common/imu_traits.h"
#include "common/lane_scene_traits.h"
#include "common/odm_states_traits.h"
#include "common/odometry_traits.h"
#include "common/path_traits.h"
#include "common/road_frame2_traits.h"
#include "common/vehicle_state_traits.h"
#include "common/weather_traits.h"
#include "geometry/box_traits.h"
#include "geometry/line_traits.h"
#include "geometry/point_traits.h"
#include "geometry/pose_traits.h"
#include "geometry/rot_traits.h"
#include "map/advice_traits.h"
#include "map/geofence_traits.h"
#include "map/road_ref_point_attributes_traits.h"
#include "numerics/matrix_traits.h"
#include "numerics/vector_traits.h"
#include "obstacle/obstaclelist_traits.h"
#include "planning/planning_state_traits.h"
#include "point_cloud/point_cloud_traits.h"
#include "prediction/intention_traits.h"
#include "traits.h"
#include "utils/tlv_traits.h"
#include "vision/image_objects_traits.h"

#endif
