# define map database manager parameters
mdm_params:
    # all file will located under directory ${HOLO_CONFIG_ROOT}
    map_data_dir: "holo_localization_parking/vslam/"
    map_names: ["route_1"]
    mode: "offline_optimization" #{online_data_association, offline_optimization}
    keyframe_selection_params:
        minimum_distance_interval: 2.0 # meter
        minimum_angle_interval: 10.0 # degree
        minimum_observed_landmark_num: 20
# define global optimizer parameters
go_params:
    loop_detector:
        loop_detection_method: "byPose" # {byPose, byNetVlad}
        netvlad_params:
            framework: pytorch # {pytorch, tensorflow}
            image_resize_width: 640
            image_resize_height: 480
            network_weight: "/opt/holo/hpp/netvlad.pt"
    triangulation:
        minimum_track_length: 5
        max_acceptable_reproject_error: 4.0
        minimum_disparity_angle: 1.0
        maximum_landmark_distance: 80
        minimum_landmark_distance: 2.0
        minimum_triangulation_baseline: 0.5
    # factor noise
    sigmas:
        bias_between_sigma: [1e-3, 1e-3, 4e-4, 5e-6, 5e-6, 2e-6]
        velocity_factor_sigma: [0.034, 0.034, 0.034]
        velocity_factor_sigma_when_turns: [0.034, 0.1, 0.034]
        wheel_integration_factor_sigma: [0.0349, 0.0349, 0.0698, 1e-2, 1e-2, 0.1]
        zero_velocity_between_pose_sigma: [1e-3, 1e-3, 1e-3, 0.00175, 0.00175, 0.00175]
        loop_closing_between_pose_sigma: [0.0349, 0.0349, 0.0349, 0.1, 0.1, 0.1] # 2deg, 10cm
        prior_pose_sigma: [0.0349, 0.0349, 0.00349, 1e-3, 1e-3, 1e-3] # [roll(2deg), pitch(2deg), yaw, x, y, z]
        prior_velocity_sigma: [1e-9, 1e-9, 1e-9] # [vx, vy, vz]
        prior_bias_sigma: [0.1, 0.1, 0.2, 4e-4, 4e-4, 1e-4] # [acc, gyro]
    pim_params:
        gravity: 9.81
        gyro_noise_sigma: [1e-2, 1e-2, 3e-3]
        acc_noise_sigma: [0.2, 0.5, 0.3]
    #frame to frame verification parameters
    # see header file of this class for more details about these parameters
    f2fc_params:
        minimum_frame_interval: 100
        descriptor_distance_th: 1.2
        ratio_test_th: 1.0
        matches_threshold: 10
        ransanc_iterations_number: 100
        projection_error_threshold: 8e-3
        confidence: 0.99
        minimum_inliers_number: 8
    # frame to covisibility map verification parameters
    # see header file of this class for more details about these parameters
    f2cmc_params:
        max_covisibility_intensity: 60
        min_covisibility_intensity: 3
        window_size: 80.0
        descriptor_dist_th: 1.0
        ratio_test_th: 1.0
        view_distance_th: 100.0
        view_direction_th: 45.0
        matches_threshold: 80
        pose_only_unit3_factor_sigma: [0.05, 0.05]
        pose_only_unit3_factor_huber_loss: 0.5
        projection_error_threshold: 5e-3
        minimum_inliers_number: 45
    projection_error_after_gba: 3.5 # inliers projection error at image center after global BA
    max_landmark_distance: 150.0 # max landmark distance[m]. used to determine outliers after global BA
    mode: "single_map_optimization" # {single_map_optimization, multi_map_merging}
    enable_position_factor: false
    enable_visualizer: false
    verbose: true
    minimum_measurement_distance_interval: 1.0 # meter
    minimum_measurement_angle_interval: 3.0 # degree
    enable_loop_detection: false
    factor_number_in_one_frame: 20
