#ifndef HOLO_PARKING_MSG_PSD_STATUS_IDL_
#define HOLO_PARKING_MSG_PSD_STATUS_IDL_

#include <holo_parking_msg/common/Common.idl>

module holo_parking_msg
{
    module parking_manager
    {
#pragma DCPS_DATA_TYPE "holo_parking_msg::parking_manager::hmi_command"
        struct PsdStatus
        {
            holo_parking_msg::core::uint8_t slot_state;
            holo_parking_msg::core::uint8_t slot_node_state;
            holo_parking_msg::core::uint8_t app_run_state;
        };
    };
};

#endif   /// HOLO_PARKING_MSG_PSD_STATUS_IDL_
