
if(NOT OPENCV_FOUND)
    if (ENV{OPENCV_WORLD})
        set(OPENCV_FIND_COMPONENTS world)
    endif()
    if(OPENCV_FIND_REQUIRED)
        find_package(OpenCV ${OPENCV_FIND_VERSION} REQUIRED COMPONENTS ${OPENCV_FIND_COMPONENTS})
    else()
        find_package(OpenCV ${OPENCV_FIND_VERSION} QUIET COMPONENTS ${OPENCV_FIND_COMPONENTS})
    endif()
    if(OpenCV_FOUND)
        set(OPENCV_FOUND TRUE)

        foreach(lib ${OpenCV_LIBS})
            string(REGEX REPLACE "opencv_(.*)" "\\1" comp ${lib})
            if(NOT TARGET OPENCV::${comp})
                add_library(OPENCV::${comp} INTERFACE IMPORTED)
                set_target_properties(OPENCV::${comp} PROPERTIES
                    INTERFACE_LINK_LIBRARIES "${lib}")
            endif()
            set(_OPENCV_INTERFACE_TARGETS ${_OPENCV_INTERFACE_TARGETS} OPENCV::${comp})
        endforeach()
    endif()

    if(OPENCV_FOUND)
        if(NOT TARGET OPENCV::opencv)
            add_library(OPENCV::opencv INTERFACE IMPORTED)
            set_target_properties(OPENCV::opencv PROPERTIES
                INTERFACE_LINK_LIBRARIES "${_OPENCV_INTERFACE_TARGETS}")
        endif()
    endif()
endif()
