base: 
- BaseCamp/Library/release/2021.09
projects:
  holo_cmw:
    branch: feature/GH02/0930
    commands:
      configure:
        arguments:
        - -DHOLO_CMW_BUILD_ROS_WRAPPER=OFF
        - -DHOLO_CMW_BUILD_OPENDDS_WRAPPER=OFF
        - -DHOLO_CMW_BUILD_UMB_WRAPPER=OFF
        - -DHOLO_CMW_BUILD_MDC_CM_WRAPPER=ON
        - ${SOURCE_ROOT}
  holo_base_msg:
    branch: feature/GH02/0930
  gh02_msg:
    url: ${git_url}/gh/gh02_msg.git
    branch: feature/GH02/0930
    dependencies:
    - BaseCamp
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  gh02_bridge:
    url: ${git_url}/gh/gh02_bridge.git
    branch: feature/GH02/0930
    dependencies:
    - BaseCamp
    - gh02_msg
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_map_local_service_server:
    url: ${git_url}/map/holo_map_local_service_server.git
    branch: release/v0.2
    dependencies:
    - CS
    - MAP
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_map_local_service_client/tools:
    url: holo_map_local_service_client/tools
    branch: release/v0.2
    dependencies:
    - CS
    - MAP
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_fusion_cmw_app:
    url: ${git_url}/mlc/holo_localization_fusion_cmw_app.git
    branch: feature/GH02/0930
    dependencies:
    - CS
    - MLC
    - MAP
    - gh02_msg
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  ######### remove when wh01 merge to holo_base
  wh01_c:
    url: ${git_url}/wh01/wh01_c.git
    branch: dragonglass-develop
    dependencies:
    - BaseCamp
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  wh01_sensors:
    url: ${git_url}/wh01/wh01_sensors.git
    branch: feature/GH02/0930
    dependencies:
    - BaseCamp
    - wh01_c
    - gh02_msg
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
      
