#ifndef HOLO_BASE_MSG_COMMON_APP_STATUS_IDL_
#define HOLO_BASE_MSG_COMMON_APP_STATUS_IDL_

#include <holo_base_msg/core/Types.idl>
#include <holo_base_msg/common/Common.idl>

module holo_base_msg { module common {

#pragma DCPS_DATA_TYPE  "holo_base_msg::common::AppStatus"
struct AppStatus
{
    holo_base_msg::common::Timestamp   stamp;
    holo_base_msg::core::uint8_t       nodeid;
    holo_base_msg::core::Uint8Sequence status_codes;
};

}; };

#endif
