#ifndef HOLO_BASE_MASSAGE_COMMON_FREESPACE_IDL_
#define HOLO_BASE_MASSAGE_COMMON_FREESPACE_IDL_


#include<holo_base_msg/common/Common.idl>
#include<holo_base_msg/geometry/Point.idl>
#include<holo_base_msg/core/Types.idl>

module holo_base_msg{ module common{

    module freespace3f
    {
        struct SegmentInfo
        {
            holo_base_msg::core::uint32_t start;
            holo_base_msg::core::uint32_t end;
            holo_base_msg::core::uint32_t type;
        };

        struct FreespaceInterior
        {
            sequence<holo_base_msg::geometry::Point3f> points;
            sequence<SegmentInfo>                      boundaries;
        };

        struct FreespaceExterior
        {
            sequence<holo_base_msg::geometry::Point3f> points;
            sequence<SegmentInfo>                      boundaries;
            sequence<FreespaceInterior>                interiors;
        };

#pragma DCPS_DATA_TYPE "holo_base_msg::common::freespace3f::Freespace"
        struct Freespace
        {
            sequence<FreespaceExterior>       exteriors;
            holo_base_msg::common::Timestamp  stamp;
            holo_base_msg::common::Coordinate coordinate;
        };
    };
};
};

#endif
