base:
- BaseCamp/Application/GH01/release/2022.03
projects:
  holo_3rdparty:
    branch: dragonglass-develop
    commands:
      configure:
        arguments:
        - -DHOLO_3RDPARTY_FORCE_BUILD=ON
        - -DHOLO_3RDPARTY_BUILD_DEPENDENCIES=ON
        - -DGTSAM_VERSION=4.0.2
        - ${SOURCE_ROOT}
      build:
        arguments:
        - sqlite3
        - boost
        - eigen3
        - glog
        - jpeg
        - nanopb
        - flann
        - rply
        - opencv
        - ffmpeg
        - apriltag
        - qpOASES
        - qpOASES_e
        - protobuf
        - gtsam
        - gtest-1.8.1
        - opendds
        - log4cplus
        - lz4
        - libyuv
        - ceres
        - osqp
  holo_cmw:
    branch: dragonglass-develop
    commands:
      configure:
        arguments_tda4_qnx-7.0.0:
        - -DHOLO_CMW_BUILD_DDS_MICRO_WRAPPER=OFF
        - -DHOLO_CMW_BUILD_OPENDDS_WRAPPER=OFF
        - -DHOLO_CMW_BUILD_PPS_WRAPPER=ON
        - ${SOURCE_ROOT}
        arguments_tda4_ubuntu-18.04:
        - ${SOURCE_ROOT}
        arguments_x86_64_ubuntu-18.04:
        - -DHOLO_CMW_BUILD_DDS_MICRO_WRAPPER=ON
        - -DHOLO_CMW_BUILD_OPENDDS_WRAPPER=OFF
        - ${SOURCE_ROOT}
        arguments_x86_64_ubuntu-18.04-base:
        - -DHOLO_CMW_BUILD_DDS_MICRO_WRAPPER=ON
        - -DHOLO_CMW_BUILD_OPENDDS_WRAPPER=OFF
        - ${SOURCE_ROOT}
        arguments_MDC610-1.1801.001-A180000.1.B010:
        - -DHOLO_CMW_BUILD_OPENDDS_WRAPPER=OFF
        - -DHOLO_CMW_BUILD_MDC_CM_WRAPPER=ON
        - ${SOURCE_ROOT}
    steps: null
  holo_map_navigator:
    url: ${git_url}/map/holo_map_navigator.git
    branch: gh01-develop
    dependencies:
    - CS
    - holo_3d
    - holo_map_base
    - holo_map_format
    - holo_map_common
    - holo_map_local_service_client
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_map_parking:
    url: ${git_url}/parking/holo_map_parking.git
    branch: dragonglass-develop
    dependencies:
    - holo_map_navigator
    - holo_io
    - holo_parking_base
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_map_parking/tools:
    url: holo_map_parking/tools
    branch: dragonglass-develop
    dependencies:
    - holo_map_parking
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_io:
    url: ${git_url}/base/holo_io.git
    branch: dragonglass-develop
    dependencies:
    - BaseCampApplication
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_perception_base:
    url: ${git_url}/per/holo_perception_base.git
    branch: dragonglass-develop
  holo_dnn_base:
    url: ${git_url}/bcper/holo_dnn_base.git
    branch: dragonglass-develop
  holo_dnn_mdc:
    url: ${git_url}/per/holo_dnn_mdc.git
    branch: dragonglass-develop
  holo_perception_3d:
    url: ${git_url}/bcper/holo_perception_3d.git
    branch: dragonglass-develop
  # TODO: ['holo_map_local_service_server', 'gh02_msg', 'holo_parking_base', 'BaseCampApplication', 'BaseCampMapApplication'] has CycularDependencyError
  holo_parking_base:
    url: ${git_url}/parking/holo_parking_base.git
    branch: dragonglass-develop
    dependencies:
    - BaseCamp
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_dnn_base/apps:
    url: ""
    branch: dragonglass-develop
    dependencies:
    - holo_dnn_base
    - holo_dnn_mdc
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_perception_parking:
    url: ${git_url}/parking/holo_perception_parking.git
    branch: dragonglass-develop
    dependencies:
    - BaseCampApplication
    - holo_parking_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_parking:
    url: ${git_url}/parking/holo_localization_parking.git
    branch: dragonglass-develop
    dependencies:
    - BaseCampApplication
    - holo_io
    - holo_parking_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_planning_parking:
    url: ${git_url}/parking/holo_planning_parking.git
    branch: dragonglass-develop
    dependencies:
    - BaseCampApplication
    - holo_io
    - holo_parking_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_parking_cmw_app:
    url: ${git_url}/parking/holo_parking_cmw_app.git
    branch: gh02-develop
    dependencies:
    - gh02_msg
    - holo_localization_parking
    - holo_perception_parking
    - holo_planning_parking
    commands:
      configure:
        arguments:
        - -DHOLO_BUILD_PARKING_APP=ON
        - ${SOURCE_ROOT}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_map_parking_cmw_app:
    url: ${git_url}/bcmap/holo_map_parking_cmw_app.git
    branch: dragonglass-develop
    dependencies:
    - BaseCampApplication
    - holo_map_navigator
    - gh02_msg
    - holo_map_parking
    commands:
      configure:
        arguments:
        - -DHOLO_BUILD_PARKING_MDC_MSG=ON
        - ${SOURCE_ROOT}
        arguments_tda4_qnx-7.0.0:
        - -DHOLO_BUILD_PARKING_MDC_MSG=ON
        - ${SOURCE_ROOT}
        arguments_x86_64_ubuntu-18.04:
        - -DHOLO_BUILD_PARKING_MDC_MSG=ON
        - ${SOURCE_ROOT}
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_map_parking_cmw_app/tools:
    url: holo_map_parking_cmw_app/tools
    branch: dragonglass-develop
    dependencies:
    - holo_map_parking_cmw_app
    commands:
      configure:
        arguments:
        - -DHOLO_BUILD_PARKING_MDC_MSG=ON
        - ${SOURCE_ROOT}
        arguments_tda4_qnx-7.0.0:
        - -DHOLO_BUILD_PARKING_MDC_MSG=ON
        - ${SOURCE_ROOT}
        arguments_x86_64_ubuntu-18.04:
        - -DHOLO_BUILD_PARKING_MDC_MSG=ON
        - ${SOURCE_ROOT}
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_x_client:
    url: ${git_url}/sim/holo_x_client.git
    branch: gh01-develop
    dependencies:
    - BaseCampApplication
    - holo_io
    commands:
      configure:
        arguments:
        - -DUSE_PPS_WRAPPER=ON
        - ${SOURCE_ROOT}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_bag:
    url: ${git_url}/win/holo_bag.git
    branch: gh01-develop
    dependencies:
    - BaseCampApplication
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_bag/cmw_app:
    url: holo_bag/cmw_app
    dependencies:
    - holo_bag
    - holo_cmw
    - holo_sensors_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  odm:
    url: ${git_url}/fun/odm.git
    branch: gh01-develop
    dependencies:
    - BaseCampApplication
    - holo_parking_base
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  odm/cmw_app:
    url: odm/cmw_app
    dependencies:
    - BaseCampApplication
    - odm
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_winterfell:
    url: ${git_url}/win/holo_winterfell.git
    branch: gh01-develop
    dependencies:
    - holo_base
    - holo_bag
    - holo_parking_base
    commands:
      configure:
        arguments:
        - -DHOLO_BUILD_ON_TDA4=ON
        - ${SOURCE_ROOT}
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_winterfell/cmw_app:
    url: holo_winterfell/cmw_app
    dependencies:
    - holo_winterfell
    - holo_cmw
    - holo_parking_base
    commands:
      configure:
        arguments:
        - -DHOLO_BUILD_ON_TDA4=ON
        - ${SOURCE_ROOT}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_params:
    url: ${git_url}/vs/holo_params.git
    branch: dragonglass-develop
    commands:
      configure:
        command: 'cmake'
        arguments:
        - -DVID=aionlx-up-1
        - ${SOURCE_ROOT}
        retcode: [0]
    steps:
        - configure
        - build
        - install
    package:
        manifest: ${BUILD_ROOT}/install_manifest.txt
        files: []
        directories: []
  holo_sensors_base:
    url: ${git_url}/vs/holo_sensors_base.git
    branch: dragonglass-develop
    dependencies:
    - CS
    - holo_sensors_c
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_sensors_cmw_app:
    url: ${git_url}/vs/holo_sensors_cmw_app.git
    branch: gh02parking-develop
    dependencies:
    - CS
    - VS
    - gh02_msg
    commands:
      configure:
        command: 'cmake'
        arguments:
        - ${SOURCE_ROOT}
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  gh02_msg:
    url: ${git_url}/gh/gh02_msg.git
    branch: gh02parking-develop
    dependencies:
    - holo_base
    - holo_cmw
    - holo_parking_base
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      configure:
        arguments:
        - -DHOLO_BUILD_CM_TRAITS=ON
        - ${SOURCE_ROOT}
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  gh02_c:
    url: ${git_url}/gh/gh02_c.git
    branch: dragonglass-develop
    dependencies:
    - holo_base_c
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  gh02_sensors:
    url: ${git_url}/gh/gh02_sensors.git
    branch: gh02parking-develop
    dependencies:
    - holo_base
    - holo_sensors_base
    - holo_cmw
    - gh02_c
    - gh02_msg
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_map_local_service_server:
    dependencies:
    - CS
    - MAP
    - gh02_msg
    commands:
      configure:
        arguments:
          - -DHOLO_BUILD_WITH_GH02_MSG=ON
          - ${SOURCE_ROOT}
  holo_map_local_service_client/tools:
    dependencies:
    - CS
    - MAP
    - gh02_msg
    commands:
      configure:
        arguments:
          - -DHOLO_BUILD_WITH_GH02_MSG=ON
          - ${SOURCE_ROOT}
  ParkingBaseCamp:
    dependencies:
    - holo_3rdparty
    - holo_base_c
    - holo_base
    - holo_calibration
    - holo_cmw
    - holo_base_msg
    - holo_sensors_c
    - holo_sensors_base
    - holo_localization_base
    - holo_perception_base
    - holo_planning_base
    - holo_control_base
    - holo_sensors_cmw_app
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
  holo_vehicles:
    url: ${git_url}/bcvs/holo_vehicles.git
    branch: gh02parking-develop
    dependencies:
    - holo_base
    - holo_base_msg
    - holo_sensors_base
    - holo_cmw
    - gh02_c
    - gh02_msg
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_base_msg:
    branch: dragonglass-develop
  ParkingApps:
    dependencies:
    - holo_parking_cmw_app
    - holo_map_parking_cmw_app
    - odm/cmw_app
    - holo_params
    dependencies_x86_64_ubuntu-18.04:
    - holo_parking_cmw_app
    - holo_map_parking_cmw_app
    - holo_x_client
    - odm/cmw_app
    - holo_params
    dependencies_tda4_qnx-7.0.0:
    - holo_parking_cmw_app
    - holo_map_parking_cmw_app
    - holo_x_client
    - holo_bag/cmw_app
    - holo_params
    - holo_winterfell/cmw_app
    dependencies_MDC610-1.1801.001-A180000.1.B010:
    - holo_parking_cmw_app
    - holo_map_parking_cmw_app
    - gh02_sensors
    - holo_vehicles
    - holo_params
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
  ParkingHpp:
    dependencies:
    - ParkingBaseCamp
    - ParkingApps
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
version: 1
