#ifndef HOLO_BASE_MSG_NUMERICS_VECTOR_IDL_
#define HOLO_BASE_MSG_NUMERICS_VECTOR_IDL_

#include <holo_base_msg/core/Types.idl>

module holo_base_msg { module numerics {

typedef sequence<holo_base_msg::core::float64_t> Vectord;

typedef holo_base_msg::core::float64_t  Vector2d[2];
typedef holo_base_msg::core::float64_t  Vector3d[3];
typedef holo_base_msg::core::float64_t  Vector4d[4];
typedef holo_base_msg::core::float64_t  Vector5d[5];
typedef holo_base_msg::core::float64_t  Vector6d[6];
typedef holo_base_msg::core::float64_t  Vector7d[7];
typedef holo_base_msg::core::float64_t  Vector8d[8];

typedef sequence<holo_base_msg::core::float32_t> Vectorf;

typedef holo_base_msg::core::float32_t  Vector2f[2];
typedef holo_base_msg::core::float32_t  Vector3f[3];
typedef holo_base_msg::core::float32_t  Vector4f[4];
typedef holo_base_msg::core::float32_t  Vector5f[5];
typedef holo_base_msg::core::float32_t  Vector6f[6];
typedef holo_base_msg::core::float32_t  Vector7f[7];
typedef holo_base_msg::core::float32_t  Vector8f[8];

}; };

#endif

