base: BaseCampNext/develop
projects:
  holonext_perception:
    url: ${git_url}/holonextapp/holonext_perception.git
    branch: develop
    dependencies:
    - holonext_3rdparty
    - holonext_base
    - holo_3d
    - holonext_perception_base
    - holo_dnn
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holonext_perception/cmw_app:
    url: holonext_perception/cmw_app
    dependencies:
    - holonext_perception
    - holo_cmw
    - holonext_base_msg
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_planning_pilot:
    url: ${git_url}/pc/holo_planning_pilot.git
    branch: holonext-develop
    dependencies:
    - holo_base
    - holo_planning_base
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_planning_pilot/cmw_app:
    url: holo_planning_pilot/cmw_app
    dependencies:
    - holo_planning_pilot
    - holo_cmw
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holonext_localization:
    url: ${git_url}/holonextapp/holonext_localization.git
    branch: develop
    dependencies:
    - holonext_3rdparty
    - holonext_base
    - holonext_localization_base
    - holo_3d
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holonext_localization/cmw_app:
    url: holonext_localization/cmw_app
    branch: develop
    dependencies:
    - holonext_localization
    - holo_cmw
    - holonext_base_msg
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holonext_map:
    url: ${git_url}/holonextapp/holonext_map.git
    branch: develop
    dependencies:
    - holonext_base
    - holo_map_base
    - holo_map_format
    - holo_map_common
    - holo_map_core
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holonext_map/cmw_app:
    url: ${git_url}/holonextapp/holonext_map.git
    branch: develop
    dependencies:
    - holonext_map
    - holo_cmw
    - holonext_base_msg
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holonext_sensors:
    url: ${git_url}/holonextapp/holonext_sensors.git
    branch: develop
    dependencies:
    - holonext_base
    - holonext_sensors_base
    - holo_sensors
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holonext_sensors/cmw_app:
    url: holonext_sensors/cmw_app
    dependencies:
    - holonext_sensors
    - holo_cmw
    - holonext_base_msg
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holonext_control:
    url: ${git_url}/holonextapp/holonext_control.git
    branch: develop
    dependencies:
    - holonext_base
    - holo_control_base
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holonext_control/cmw_app:
    url: holonext_control/cmw_app
    dependencies:
    - holonext_control
    - holo_cmw
    - holonext_base_msg
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_params:
    url: ${git_url}/vs/holo_params.git
    branch: dragonglass-develop
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  HoloNextApps:
    dependencies:
    - holonext_perception/cmw_app
    - holo_planning_pilot/cmw_app
    - holonext_localization/cmw_app
    - holonext_map/cmw_app
    - holonext_sensors/cmw_app
    - holonext_control/cmw_app
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
  HoloNext:
    dependencies:
    - BaseCampNext
    - HoloNextApps
    - holo_params
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
version: 1
