var: {}
env:
  GTEST_OUTPUT: 'json:'
cfg_args: []
cfg_args_cmake:
- -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON
- -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON
- -DCMAKE_BUILD_TYPE=RELEASE
- -DHOLO_BUILD_TEST=OFF
- -DHOLO_CPU_PROFILE=OFF
- -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
- -DHOLO_BUILD_PLATFORM=${BUILD_PLATFORM}
- -DHOLO_BUILD_PRODUCT=${BUILD_PRODUCT}
- -DHOLO_BUILD_VERSION=${build_id}
- -DCMAKE_VERBOSE_MAKEFILE=${cmake_verbose}
version: 1
