base: BaseCamp/Library/develop
projects:
  holo_3rdparty:
    branch: feature/c52/opendds
    commands:
      configure:
        arguments:
        - -DHOLO_3RDPARTY_FORCE_BUILD=ON
        - -DOPENCV_WITH_GTK=ON
        - -DOPENCV_SKIP_CACHE=ON
        - -DOPENDDS_VERSION=3.13.2
        - ${SOURCE_ROOT}
      build:
        arguments:
        - proj4
        - yaml-cpp
        - eigen3
        - opencv
        - libsocket
        - protobuf
        - glog
        - jpeg
        - nanopb
        - gtsam
        - gtest-1.8.1
        - opendds
        - log4cplus
        - lz4
    steps: null
    cache: null
    package:
      manifest: null
      files: []
      directories:
      - ${HOLO_ROOT}/3rdparty
      - ${HOLO_ROOT}/../host
  c52_msg:
    url: ${git_url}/holopolaris/c52_msg.git
    branch: dragonglass-develop
    dependencies:
    - holo_base
    - holo_base_msg
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_cmw:
    url: ${git_url}/bccs/holo_cmw.git
    branch: dragonglass-develop
    dependencies:
    - holo_base
    - holo_utils
    commands:
      configure:
        arguments:
        - -DOPENDDS_WRAPPER_BUILD_TOOLS=OFF
        - -DDEPEND_OPENDDS_VERSION=3.13.2
        - ${SOURCE_ROOT}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  c52_msg_cmw_app:
    url: ${git_url}/holopolaris/c52_msg_cmw_app.git
    branch: polaris/project/c52
    dependencies:
    - holo_base
    - holo_base_msg
    - holo_sensors_base
    - holo_cmw
    - c52_msg
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_fusion_cmw_app:
    url: ${git_url}/mlc/holo_localization_fusion_cmw_app.git
    branch: polaris/project/c52_new
    dependencies:
    - holo_cmw
    - holo_base_msg
    - c52_msg
    - holo_localization_fusion
    - holo_map_local_service_client
    - holo_map_local_service_server
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_vision_cmw_app:
    url: ${git_url}/mlc/holo_localization_vision_cmw_app.git
    branch: dragonglass-develop
    dependencies:
    - holo_cmw
    - holo_base_msg
    - holo_sensors_base
    - holo_localization_vision
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_map_adapter:
    url: ${git_url}/map/holo_map_adapter.git
    branch: dragonglass-develop
    dependencies:
    - holo_base
    - holo_cmw
    - holo_base_msg
    - holo_map_base
    - holo_map_format
    - holo_map_common
    commands:
      configure:
        arguments:
        - -DHOLO_BUILD_WITH_MAP_SDK_BAIDU=ON
        - -DHOLO_BUILD_WITH_MAP_SDK_PLATFORM_ARM=ON
        - -DHOLO_BUILD_WITH_BAIDU_HDMAP_ENGINE_C52_V_3_1_0_7_20210824=ON
        - -DHOLO_BUILD_WITH_CMW=OFF
        - ${SOURCE_ROOT}
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_map_local_service_server:
    url: ${git_url}/map/holo_map_local_service_server.git
    branch: dragonglass-develop
    dependencies:
    - CS
    - MAP
    - c52_msg
    commands:
      configure:
        arguments:
        - -DHOLO_BUILD_C52_MSG=ON
        - ${SOURCE_ROOT}
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_map_local_service_client/tools:
    url: holo_map_local_service_client/tools
    branch: dragonglass-develop
    dependencies:
    - CS
    - MAP
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_bag:
    url: ${git_url}/win/holo_bag.git
    branch: feature/hsx/c52_msg
    dependencies:
    - holo_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_bag/cmw_app:
    url: holo_bag/cmw_app
    dependencies:
    - holo_bag
    - holo_cmw
    - holo_sensors_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  PolarisApps:
    dependencies:
    - c52_msg_cmw_app
    - holo_localization_fusion_cmw_app
    - holo_localization_vision_cmw_app
    - holo_bag/cmw_app
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
version: 1
