base: Pilot/develop
projects:
  holo_3rdparty:
    commands:
      build:
        arguments:
        - gtest-1.8.1
        - glog
        - eigen3
        - gperf
        - opencv
        - gtsam
        - qpOASES_e
        - qpOASES
        - yaml-cpp
        - protobuf
        - sqlite3
        - ffmpeg
        - x264
        - jpeg
        - nanopb
        - opendds
        - openssl
        - mosquitto
        - log4cplus
    steps: null
    package:
      manifest: null
      files: []
      directories:
      - ${HOLO_ROOT}/3rdparty
      - ${HOLO_ROOT}/../host
  holo_cmw:
    commands:
      configure:
        arguments:
        - -DHOLO_CMW_BUILD_OPENDDS_CMW=ON
        - -DHOLO_CMW_BUILD_ROS_WRAPPER=OFF
        - -DHOLO_CMW_BUILD_OPENDDS_WRAPPER=ON
        - -DHOLO_CMW_BUILD_UMB_WRAPPER=OFF
        - ${SOURCE_ROOT}
    steps: null
  holo_perception_pilot:
    branch: wh01-develop
    dependencies:
    - holo_3rdparty
    - holo_base
    - holo_perception_base
    commands: {}
    steps: null
  holo_perception_pilot/cmw_app:
    url: holo_perception_pilot/cmw_app
    dependencies:
    - holo_base
    - holo_base_msg
    - holo_perception_base
    - holo_perception_pilot
    - holo_cmw
    - holo_sensors_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_sensors_cmw_app:
    commands:
      configure:
        arguments:
        - -DHOLO_BUILD_OPENDDS_APP=ON
        - -DHOLO_BUILD_UMB_APP=OFF
        - -DHOLO_BUILD_ON_ACU=OFF
        - ${SOURCE_ROOT}
    steps: null
  wh01_c:
    url: ${git_url}/wh01/wh01_c.git
    branch: dragonglass-develop
    dependencies:
    - holo_base_c
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  wh01_msg:
    url: ${git_url}/wh01/wh01_msg.git
    branch: dragonglass-develop
    dependencies:
    - holo_base
    - holo_base_msg
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  wh01_sensors:
    url: ${git_url}/wh01/wh01_sensors.git
    branch: feature/mdc-interface
    dependencies:
    - holo_base
    - holo_sensors_base
    - holo_base_msg
    - wh01_c
    - wh01_msg
    - wh01_hmi
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_planning_pilot:
    url: ${git_url}/pc/holo_planning_pilot.git
    branch: dragonglass-develop
    dependencies:
    - holo_base
    - holo_planning_base
    - wh01_msg
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_planning_pilot/cmw_app:
    url: holo_planning_pilot/cmw_app
    dependencies:
    - holo_planning_pilot
    - holo_cmw
    - holo_base_msg
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_control:
    url: ${git_url}/pc/holo_control.git
    branch: dragonglass-develop
    dependencies:
    - holo_base
    - holo_control_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_control/cmw_app:
    url: holo_control/cmw_app
    dependencies:
    - holo_control
    - holo_base_msg
    - holo_cmw
    - wh01_msg
    - wh01_c
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  wh01_hmi:
    url: ${git_url}/wh01/wh01_hmi.git
    branch: feature/pg/hsa
    dependencies:
    - holo_base
    - wh01_c
    - wh01_msg
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  odm:
    url: ${git_url}/fun/odm.git
    branch: dragonglass-develop
    dependencies:
    - holo_base
    - holo_cmw
    - wh01_msg
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  odm/cmw_app:
    url: odm/cmw_app
    dependencies:
    - odm
    - holo_cmw
    - holo_base_msg
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_diagnosis_c:
    url: ${git_url}/vs/holo_diagnosis_c.git
    branch: dragonglass-develop
    dependencies:
    - holo_base_c
    commands:
      doc:
        command: make
        arguments:
        - doc
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_diagnosis_base:
    url: ${git_url}/vs/holo_diagnosis_base.git
    branch: dragonglass-develop
    dependencies:
    - holo_diagnosis_c
    - holo_base
    commands:
      doc:
        command: make
        arguments:
        - doc
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_diagnosis_cmw_app:
    url: ${git_url}/vs/holo_diagnosis_cmw_app.git
    branch: dragonglass-develop
    dependencies:
    - holo_diagnosis_base
    - holo_base_msg
    - holo_cmw
    commands:
      doc:
        command: make
        arguments:
        - doc
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_bag:
    url: ${git_url}/win/holo_bag.git
    branch: dragonglass-develop
    dependencies:
    - holo_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_bag/cmw_app:
    url: holo_bag/cmw_app
    dependencies:
    - holo_bag
    - holo_cmw
    - holo_sensors_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_winterfell:
    url: ${git_url}/win/holo_winterfell.git
    branch: dragonglass-develop
    dependencies:
    - holo_base
    - holo_bag
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_winterfell/cmw_app:
    url: holo_winterfell/cmw_app
    dependencies:
    - holo_winterfell
    - holo_cmw
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_io:
    url: ${git_url}/base/holo_io.git
    branch: dragonglass-develop
    dependencies:
    - holo_base
    - holo_base_msg
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_io/cmw_app:
    url: holo_io/cmw_app
    dependencies:
    - holo_io
    - holo_cmw
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_benchmark:
    url: ${git_url}/mlc/holo_localization_benchmark.git
    branch: dragonglass-develop
    dependencies:
    - holo_localization_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_benchmark/cmw_app:
    url: holo_localization_benchmark/cmw_app
    dependencies:
    - holo_io
    - holo_cmw
    - holo_localization_benchmark
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_msg:
    url: ${git_url}/win/holo_msg.git
    branch: dragonglass-develop
    dependencies:
    - holo_cmw
    - holo_base_metadata
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_x_client:
    url: ${git_url}/~gaochengbin/holo_x_client.git
    branch: zgg/holo_cmw_V2_opendds
    dependencies:
    - holo_base
    - holo_cmw
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_map_navigator_cmw_app:
    url: ${git_url}/map/holo_map_navigator_cmw_app.git
    branch: dragonglass-develop
    dependencies:
    - holo_base
    - holo_base_msg
    - holo_cmw
    - holo_map_local_service_client
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  BaseCampWH01:
    dependencies:
    - holo_3rdparty
    - holo_base_c
    - holo_base
    - holo_cmw
    - holo_base_msg
    - holo_sensors_c
    - holo_sensors_base
    - holo_localization_base
    - holo_localization_fusion
    - holo_localization_semantic
    - holo_localization_vision
    - holo_map_base
    - holo_map_common
    - holo_map_format
    - holo_map_adapter
    - holo_map_local_service_server
    - holo_map_local_service_client
    - holo_perception_base
    - holo_planning_base
    - holo_control_base
    - holo_sensors_cmw_app
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
  WH01:
    dependencies:
    - BaseCampWH01
    - holo_perception_pilot/cmw_app
    - holo_localization_fusion_cmw_app
    - holo_map_cmw_app
    - holo_sensors_cmw_app
    - holo_planning_pilot/cmw_app
    - holo_control/cmw_app
    - wh01_hmi
    - odm/cmw_app
    - wh01_sensors
    - holo_x_client
    - holo_bag/cmw_app
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
  WH01_benchmark:
    dependencies:
    - WH01
    - holo_bag/cmw_app
    - holo_io/cmw_app
    - holo_localization_benchmark/cmw_app
    - holo_msg
    commands:
      configure:
        command: ''
        arguments:
        - -DHOLO_LOCAL_MAP_FUSION_BENCHMARK=ON
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
version: 1
