base: Pilot/WH01/develop
projects:
  holo_bag_filter:
    url: ${git_url}/~gaochengbin/holo_bag_filter.git
    branch: dragonglass-develop
    dependencies:
    - holo_bag
    - wh01_msg
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_swit_checker:
    url: ${git_url}/~gaochengbin/holo_swit_checker.git
    branch: master
    dependencies:
    - wh01_msg
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_test_tools:
    url: ${git_url}/~wutianyu/holo_test_tools.git
    branch: master
    dependencies:
    - holo_bag
    - wh01_msg
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
version: 1
