#ifndef HOLO_BASE_MSG_CORE_TYPES_IDL_
#define HOLO_BASE_MSG_CORE_TYPES_IDL_

module holo_base_msg{ module core {

typedef boolean                         bool_t;
typedef char                            char_t;
typedef wchar                           wchar_t;
typedef char                            int8_t;
typedef octet                           uint8_t;
typedef short                           int16_t;
typedef unsigned short                  uint16_t;
typedef long                            int32_t;
typedef unsigned long                   uint32_t;
typedef long long                       int64_t;
typedef unsigned long long              uint64_t;
typedef float                           float32_t;
typedef double                          float64_t;


typedef sequence<boolean>             BoolSequence;
typedef sequence<char>                CharSequence;
typedef sequence<wchar>               WcharSequence;
typedef sequence<char>                Int8Sequence;
typedef sequence<octet>               Uint8Sequence;
typedef sequence<short>               Int16Sequence;
typedef sequence<unsigned short>      Uint16Sequence;
typedef sequence<long>                Int32Sequence;
typedef sequence<unsigned long>       Uint32Sequence;
typedef sequence<long long>           Int64Sequence;
typedef sequence<unsigned long long>  Uint64Sequence;
typedef sequence<float>               Float32Sequence;
typedef sequence<double>              Float64Sequence;

}; };

#endif

