var:
  PATH: ${SYSROOT}/../resources/toolchain/armhf/gcc-7.4.1/bin:${HOLO_ROOT}/../host/bin::/usr/local/bin:/bin:/sbin:/usr/bin:/usr/sbin
  TOOLCHAIN_PREFIX: arm-linux-gnueabihf-
  TARGET_ROOT: ${CROSSTOOL_ROOT}/ubuntu-18.04-armhf
  PKG_CONFIG_PATH: ${SYSROOT}/usr/lib/pkgconfig:${SYSROOT}/usr/share/pkgconfig:${SYSROOT}/usr/lib/arm-linux-gnueabihf/pkgconfig
  LDFLAGS: -Wl,-rpath-link,${SYSROOT}/usr/lib/arm-linux-gnueabihf:${SYSROOT}/lib/arm-linux-gnueabihf:${HOLO_ROOT}/3rdparty/lib:${HOLO_ROOT}/lib
env:
  PATH: ${PATH}
  LANG: $ENV{LANG}
  TERM: $ENV{TERM}
  PWD: $ENV{PWD}
  SHELL: $ENV{SHELL}
  USER: $ENV{USER}
  HOME: $ENV{HOME}
  PKG_CONFIG_PATH: ${SYSROOT}/usr/lib/pkgconfig:${SYSROOT}/usr/share/pkgconfig:${SYSROOT}/usr/lib/arm-linux-gnueabihf/pkgconfig
  PKG_CONFIG_LIBDIR: ${SYSROOT}/usr/lib/pkgconfig:${SYSROOT}/usr/share/pkgconfig:${SYSROOT}/usr/lib/arm-linux-gnueabihf/pkgconfig
  PKG_CONFIG_SYSROOT_DIR: ${SYSROOT}
  ROS_LANG_DISABLE: geneus:genlisp:gennodejs
  ROS_PYTHON_VERSION: $ENV{ROS_PYTHON_VERSION}
  CMAKE_PREFIX_PATH: ${HOLO_ROOT}/../host:$SHELL{dirname `find ${SYSROOT}/opt/ros
    -name .catkin`}
  CC: ${TOOLCHAIN_PREFIX}gcc --sysroot=${SYSROOT}
  CXX: ${TOOLCHAIN_PREFIX}g++ --sysroot=${SYSROOT}
  RANLIB: ${TOOLCHAIN_PREFIX}ranlib
  AR: ${TOOLCHAIN_PREFIX}ar
  LD: ${TOOLCHAIN_PREFIX}ld
  NM: ${TOOLCHAIN_PREFIX}nm
  OBJDUMP: ${TOOLCHAIN_PREFIX}objdump
  STRIP: ${TOOLCHAIN_PREFIX}strip
  LDFLAGS: -Wl,-rpath-link,${SYSROOT}/usr/lib/arm-linux-gnueabihf:${SYSROOT}/lib/arm-linux-gnueabihf:${HOLO_ROOT}/3rdparty/lib:${HOLO_ROOT}/lib
  HOLO_3RDPARTY_CACHE_ROOT: /opt/DataStore/libs/armhf/ubuntu-18.04
  CFLAGS: ${CFLAGS}
  CXXFLAGS: ${CXXFLAGS}
  HOLO_ROOT: ${HOLO_ROOT}
toolchain_prefix: arm-linux-gnueabihf-
target_root: ${CROSSTOOL_ROOT}/ubuntu-18.04-armhf
crosstool:
- ubuntu-18.04-armhf.tar.bz2
- resources/toolchain/armhf/gcc-7.4.1.tar.bz2 
version: 1
