#ifndef HOLO_PARKING_MSG_PARKING_MANAGER_PARKING_MANAGER_COMMAND_IDL_
#define HOLO_PARKING_MSG_PARKING_MANAGER_PARKING_MANAGER_COMMAND_IDL_

#include <holo_parking_msg/common/Common.idl>

module holo_parking_msg
{
    module parking_manager
    {
#pragma DCPS_DATA_TYPE "holo_parking_msg::parking_manager::APAParkingManagerCommand"

        struct APAParkingManagerCommand
        {
            holo_parking_msg::common::Timestamp timestamp;
            holo_parking_msg::core::bool_t apa_enable;
            holo_parking_msg::core::uint8_t  apa_searching_method;
            holo_parking_msg::core::uint8_t  slot_method;
            holo_parking_msg::core::uint8_t  park_type;
        };
    };
};

#endif
