base: BaseCamp/Application/Dev/develop
projects:
    holo_cmw:
        branch: dragonglass-develop
        commands:
            configure:
                arguments:
                    - -DHOLO_CMW_BUILD_OPENDDS_CMW=ON
                    - -DHOLO_CMW_BUILD_ROS_WRAPPER=OFF
                    - -DHOLO_CMW_BUILD_UMB_WRAPPER=OFF
                    - ${SOURCE_ROOT}
        steps: null
    holo_sensors_base:
        commands:
            configure:
                arguments:
                    - -DHOLO_BUILD_ON_MDC610=ON
                    - ${SOURCE_ROOT}
    holo_sensors_cmw_app:
        commands:
            configure:
                arguments:
                    - -DHOLO_BUILD_ON_MDC610=ON
                    - ${SOURCE_ROOT}
    holo_localization_semantic:
        branch: feature/up/v0.1
    holo_localization_fusion:
        branch: feature/up/v0.1
        commands: {}
        steps: null
    holo_localization_fusion_cmw_app:
        branch: feature/up/v0.1
        commands: {}
        steps: null
    holo_map_local_service_client:
        branch: feature/wanghaiyang/map-matcher-degrading
        commands: {}
        steps: null
    holo_map_core:
        url: ${git_url}/map/holo_map_core.git
        branch: feature/dg-core
        dependencies:
            - MAP
            - holo_map_local_service_client
        commands:
            configure:
                arguments:
                    - -DHOLO_MAP_ENABLE_URBAN_PILOT=ON
                    - ${SOURCE_ROOT}
            test:
                command: make
                arguments:
                    - test
                    - "||"
                    - "true"
            doc:
                command: make
                arguments:
                    - doc
            coverage:
                command: make
                arguments:
                    - coverage
        steps: null
        package:
            manifest: ${BUILD_ROOT}/install_manifest.txt
            files: []
            directories: []
    holo_map_cmw_app:
        url: ${git_url}/map/holo_map_cmw_app.git
        branch: feature/dg-core
        dependencies:
            - CS
            - holo_map_core
        commands:
            doc:
                command: make
                arguments:
                    - doc
        steps: null
        package:
            manifest: ${BUILD_ROOT}/install_manifest.txt
            files: []
            directories: []
    wh01_msg:
        url: ${git_url}/wh01/wh01_msg.git
        branch: dragonglass-develop
        dependencies:
            - holo_base
            - holo_base_msg
        commands:
            test:
                command: make
                arguments:
                    - test
                    - "||"
                    - "true"
            doc:
                command: make
                arguments:
                    - doc
            coverage:
                command: make
                arguments:
                    - coverage
        steps: null
        package:
            manifest: ${BUILD_ROOT}/install_manifest.txt
            files: []
            directories: []
    holo_scenario_modeling:
        url: ${git_url}/pc/holo_scenario_modeling.git
        branch: feature/dg-core
        dependencies:
            - holo_base
            - holo_planning_base
        commands: {}
        steps: null
        package:
            manifest: ${BUILD_ROOT}/install_manifest.txt
            files: []
            directories: []
    holo_planning_base:
        branch: feature/dg-core
        commands: {}
        steps: null
    holo_planning_pilot:
        url: ${git_url}/pc/holo_planning_pilot.git
        branch: feature/dg-core
        dependencies:
            - holo_base
            - holo_planning_base
            - wh01_msg
            - holo_scenario_modeling
        commands:
            test:
                command: make
                arguments:
                    - test
                    - "||"
                    - "true"
            doc:
                command: make
                arguments:
                    - doc
            coverage:
                command: make
                arguments:
                    - coverage
        steps: null
        package:
            manifest: ${BUILD_ROOT}/install_manifest.txt
            files: []
            directories: []
    holo_planning_pilot/cmw_app:
        url: holo_planning_pilot/cmw_app
        dependencies:
            - holo_planning_pilot
            - holo_cmw
            - holo_base_msg
        commands: {}
        steps: null
        package:
            manifest: ${BUILD_ROOT}/install_manifest.txt
            files: []
            directories: []
    holo_control:
        url: ${git_url}/pc/holo_control.git
        branch: dragonglass-develop
        dependencies:
            - CS
            - PC
        commands: {}
        steps: null
        package:
            manifest: ${BUILD_ROOT}/install_manifest.txt
            files: []
            directories: []
    holo_3rdparty:
        commands:
            build:
                arguments:
                    - dragonglass
                    - rply
    holo_3d:
        url: ${git_url}/mlc/holo_3d.git
        branch: dragonglass-develop
        dependencies:
            - holo_3rdparty
            - holo_base
        commands:
            test:
                command: make
                arguments:
                    - test
            doc:
                command: make
                arguments:
                    - doc
            coverage:
                command: make
                arguments:
                    - coverage
    # holo_dnn_base:
    #     branch: feature/ly/mdc_610_point_cloud
    # holo_dnn_mdc:
    #     branch: feature/ly/mdc_610_point_cloud
    holo_perception_pilot:
        dependencies:
            - PER
            - holo_3d
            - holo_dnn_base/apps
            - holo_map_local_service_client
    holo_perception_pilot/cmw_app:
        dependencies:
            - PER
            - holo_sensors_base
            - VS
            - holo_perception_pilot
    wh01_c:
        url: ${git_url}/wh01/wh01_c.git
        branch: dragonglass-develop
        dependencies:
            - holo_base_c
        commands:
            test:
                command: make
                arguments:
                    - test
                    - "||"
                    - "true"
            doc:
                command: make
                arguments:
                    - doc
            coverage:
                command: make
                arguments:
                    - coverage
        steps: null
        package:
            manifest: ${BUILD_ROOT}/install_manifest.txt
            files: []
            directories: []
    wh01_hmi:
        url: ${git_url}/wh01/wh01_hmi.git
        branch: feature/hsa/stable
        dependencies:
            - BaseCamp
            - wh01_c
            - wh01_msg
        commands:
            test:
                command: make
                arguments:
                    - test
                    - "||"
                    - "true"
            doc:
                command: make
                arguments:
                    - doc
            coverage:
                command: make
                arguments:
                    - coverage
        steps: null
        package:
            manifest: ${BUILD_ROOT}/install_manifest.txt
            files: []
            directories: []
    wh01_sensors:
        url: ${git_url}/wh01/wh01_sensors.git
        branch: feature/yzt/adapt_new_control_command
        dependencies:
            - holo_base
            - holo_sensors_base
            - holo_base_msg
            - wh01_c
            - wh01_msg
            - wh01_hmi
        commands:
            test:
                command: make
                arguments:
                    - test
                    - "||"
                    - "true"
            doc:
                command: make
                arguments:
                    - doc
            coverage:
                command: make
                arguments:
                    - coverage
        steps: null
        package:
            manifest: ${BUILD_ROOT}/install_manifest.txt
            files: []
            directories: []
    holo_control/cmw_app:
        url: holo_control/cmw_app
        dependencies:
            - CS
            - PC
            - holo_control
        commands: {}
        steps: null
        package:
            manifest: ${BUILD_ROOT}/install_manifest.txt
            files: []
            directories: []
    holo_bag:
        url: ${git_url}/win/holo_bag.git
        branch: dragonglass-develop
        dependencies:
            - holo_base
        commands: {}
        steps: null
        package:
            manifest: ${BUILD_ROOT}/install_manifest.txt
            files: []
            directories: []
    holo_bag/cmw_app:
        url: holo_bag/cmw_app
        dependencies:
            - holo_bag
            - holo_cmw
            - holo_sensors_base
        commands: {}
        steps: null
        package:
            manifest: ${BUILD_ROOT}/install_manifest.txt
            files: []
            directories: []
    holo_x_client:
        url: ${git_url}/~gaochengbin/holo_x_client.git
        branch: zgg/holo_cmw_V2_opendds
        dependencies:
            - holo_base
            - holo_cmw
            - holo_base_msg
            - holo_sensors_base
        commands: {}
        steps: null
        package:
            manifest: ${BUILD_ROOT}/install_manifest.txt
            files: []
            directories: []
    holo_params:
        url: ${git_url}/vs/holo_params.git
        branch: dragonglass-develop
        commands: {}
        steps: null
        package:
            manifest: ${BUILD_ROOT}/install_manifest.txt
            files: []
            directories: []
    UPSensors:
        dependencies:
            - wh01_sensors
            - wh01_hmi
        commands:
            configure:
                command: ""
                arguments:
                    - ${SOURCE_ROOT}
            build:
                command: ""
                arguments: []
            install:
                command: ""
                arguments: []
        steps: null
    BaseCampUP:
        dependencies:
            - BaseCampApplication
        commands:
            configure:
                command: ""
                arguments:
                    - ${SOURCE_ROOT}
            build:
                command: ""
                arguments: []
            install:
                command: ""
                arguments: []
        steps: null
    DgCore:
        dependencies:
            - BaseCampUP
            - holo_planning_pilot/cmw_app
            - holo_control/cmw_app
            - holo_sensors_cmw_app
            - holo_map_cmw_app
            - UPSensors
        commands:
            configure:
                command: ""
                arguments:
                    - ${SOURCE_ROOT}
            build:
                command: ""
                arguments: []
            install:
                command: ""
                arguments: []
        steps: null
version: 1
