base:
- BaseCamp/Application/BYH01/develop
projects:
  holo_io:
    url: ${git_url}/base/holo_io.git
    branch: dragonglass-develop
    dependencies:
    - BaseCampApplication
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []   
  holo_parking_base:
    url: ${git_url}/parking/holo_parking_base.git
    branch: dragonglass-develop
    dependencies:
    - BaseCamp
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []  
  holo_parking_msg:
    url: ${git_url}/parking/holo_parking_msg.git
    branch: dragonglass-develop
    dependencies:
    - BaseCampApplication
    - holo_parking_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_parking:
    url: ${git_url}/parking/holo_localization_parking.git
    branch: dragonglass-develop
    dependencies:
    - BaseCampApplication
    - holo_io
    commands:
      configure:
        arguments:
        - -DHOLO_LOCALIZATION_BUILD_WITH_TIDL=OFF
        - ${SOURCE_ROOT}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_planning_parking:
    url: ${git_url}/parking/holo_planning_parking.git
    branch: dragonglass-develop
    dependencies:
    - BaseCampApplication
    - holo_io
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_perception_parking:
    url: ${git_url}/parking/holo_perception_parking.git
    branch: dragonglass-develop
    dependencies:
    - BaseCampApplication
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_parking_cmw_app:
    url: ${git_url}/parking/holo_parking_cmw_app.git
    branch: byh01-develop
    dependencies:
    - holo_parking_msg
    - holo_localization_parking
    - holo_perception_parking
    - holo_planning_parking
    commands:
      configure:
        arguments:
        - -DHOLO_BUILD_PARKING_APP=ON
        #- -DTI_PSDK_VERSION=07.02.00.06
        - ${SOURCE_ROOT}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []     
  holo_params:
    url: ${git_url}/vs/holo_params.git
    branch: dragonglass-develop
    commands:
      configure:
        command: 'cmake'
        arguments:
        - -DVID=gh01-1
        - ${SOURCE_ROOT}
        retcode: [0]
    steps:
        - configure
        - build
        - install
    package:
        manifest: ${BUILD_ROOT}/install_manifest.txt
        files: []
        directories: []
  ParkingApps:
    dependencies:
    - holo_parking_cmw_app
    - holo_params
    dependencies_x86_64_ubuntu-18.04:
    - holo_parking_cmw_app
    - holo_params
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
  ParkingAPA:
    dependencies:
    - ParkingApps
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
version: 1
