#ifndef HOLO_BASE_MSG_NUMERICS_MATRIX_IDL_
#define HOLO_BASE_MSG_NUMERICS_MATRIX_IDL_

#include <holo_base_msg/core/Types.idl>

module holo_base_msg { module numerics {

typedef sequence<holo_base_msg::core::float64_t> MatrixdData;

struct Matrixd {
    holo_base_msg::core::int32_t            rows;
    holo_base_msg::core::int32_t            cols;
    MatrixdData                             data;
};

typedef holo_base_msg::core::float64_t  Matrix22d[2][2];
typedef holo_base_msg::core::float64_t  Matrix33d[3][3];
typedef holo_base_msg::core::float64_t  Matrix44d[4][4];
typedef holo_base_msg::core::float64_t  Matrix55d[5][5];
typedef holo_base_msg::core::float64_t  Matrix66d[6][6];

typedef sequence<holo_base_msg::core::float32_t> MatrixfData;

#pragma DCPS_DATA_TYPE "holo_base_msg::numerics::Matrixf"
struct Matrixf {
    holo_base_msg::core::int32_t         rows;
    holo_base_msg::core::int32_t         cols;
    MatrixfData                          data;
};

typedef holo_base_msg::core::float32_t  Matrix22f[2][2];
typedef holo_base_msg::core::float32_t  Matrix33f[3][3];
typedef holo_base_msg::core::float32_t  Matrix44f[4][4];
typedef holo_base_msg::core::float32_t  Matrix55f[5][5];
typedef holo_base_msg::core::float32_t  Matrix66f[6][6];

}; };

#endif

