base: BaseCamp/Library/develop
projects:
  holo_3rdparty:
    commands:
      configure:
        arguments:
        - -DHOLO_3RDPARTY_FORCE_BUILD=ON
        - -DOPENCV_WITH_GTK=ON
        - -DOPENCV_SKIP_CACHE=ON
        - -DGTSAM_VERSION=4.0.2
        - ${SOURCE_ROOT}
      build:
        arguments:
        - sqlite3
        - yaml-cpp
        - eigen3
        - glog
        - nanopb
        - flann
        - rply
        - opencv
        - ffmpeg
        - apriltag
        - qpOASES
        - qpOASES_e
        - protobuf
        - gtsam
        - gtest-1.8.1
        - opendds
        - log4cplus
        - lz4
    steps: null
    package:
      manifest: null
      files: []
      directories:
      - ${HOLO_ROOT}/3rdparty
      - ${HOLO_ROOT}/../host
  holo_cmw:
    commands:
      configure:
        arguments_tda4_qnx-7.0.0:
        - -DHOLO_CMW_BUILD_PPS_WRAPPER=ON
        - ${SOURCE_ROOT}
        arguments_tda4_ubuntu-18.04:
        - -DHOLO_CMW_BUILD_OPENDDS_WRAPPER=ON
        - ${SOURCE_ROOT}
        arguments_x86_64_ubuntu-18.04:
        - -DHOLO_CMW_BUILD_OPENDDS_WRAPPER=ON
        - ${SOURCE_ROOT}
        arguments_x86_64_ubuntu-18.04-base:
        - -DHOLO_CMW_BUILD_OPENDDS_WRAPPER=ON
        - ${SOURCE_ROOT}
    steps: null
  holo_sensors_base:
    url: ${git_url}/vs/holo_sensors_base.git
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_sensors_cmw_app:
    url: ${git_url}/vs/holo_sensors_cmw_app.git
    branch: dragonglass-develop
    dependencies:
    - CS
    - VS
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_map_local_service_server:
    url: ${git_url}/map/holo_map_local_service_server.git
    branch: dragonglass-develop
    dependencies:
    - CS
    - MAP
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_map_local_service_client/tools:
    url: holo_map_local_service_client/tools
    branch: dragonglass-develop
    dependencies:
    - CS
    - MAP
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  BaseCampMapApplication:
    dependencies:
    - holo_map_local_service_server
    - holo_map_local_service_client/tools
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
  holo_localization_fusion_cmw_app:
    url: ${git_url}/mlc/holo_localization_fusion_cmw_app.git
    branch: dragonglass-develop
    dependencies:
    - CS
    - MLC
    - MAP
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_vision_cmw_app:
    url: ${git_url}/mlc/holo_localization_vision_cmw_app.git
    branch: dragonglass-develop
    dependencies:
    - CS
    - MLC
    - VS
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_calibration:
    url: ${git_url}/mlc/holo_calibration.git
    branch: dragonglass-develop
    dependencies:
    - BaseCamp
    - holo_localization_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_calibration_cmw_app:
    url: ${git_url}/mlc/holo_calibration_cmw_app.git
    branch: dragonglass-develop
    dependencies:
    - holo_cmw
    - holo_calibration
    commands:
      configure:
        arguments:
        - ${SOURCE_ROOT}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  BaseCampMlcApplication:
    dependencies:
    - holo_localization_fusion_cmw_app
    - holo_localization_vision_cmw_app
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
  holo_perception_parking:
    url: ${git_url}/parking/holo_perception_parking.git
    branch: dragonglass-develop
    dependencies:
    - CS
    - PER
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_perception_parking/cmw_app:
    url: holo_perception_parking/cmw_app
    dependencies:
    - CS
    - PER
    - holo_perception_parking
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  BaseCampPerApplication:
    dependencies:
    - holo_perception_parking/cmw_app
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
  BaseCampVsApplication:
    dependencies:
    - holo_sensors_cmw_app
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
  BaseCampApplication:
    dependencies:
    - BaseCampMapApplication
    - BaseCampMlcApplication
    - BaseCampVsApplication
    - BaseCampPerApplication
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
version: 1
