base: 
- BaseCamp/Library/release/2021.07
- BaseCamp/Library/CS/release/2021.02
- BaseCamp/Library/VS/tag/wh01-r1
projects:

  holo_3rdparty:
    commands:
      build:
        arguments:
        - gtest-1.8.1
        - glog
        - eigen3
        - gperf
        - opencv
        - gtsam
        - qpOASES_e
        - qpOASES
        - yaml-cpp
        - protobuf
        - sqlite3
        - ffmpeg
        - x264
        - jpeg
        - nanopb
        - umb
        - openssl
        - mosquitto
        - log4cplus
    steps: null
    package:
      manifest: null
      files: []
      directories:
      - ${HOLO_ROOT}/3rdparty
      - ${HOLO_ROOT}/../host

  holo_cmw:
    commands:
      configure:
        arguments:
        - -DHOLO_CMW_BUILD_OPENDDS_CMW=OFF
        - -DHOLO_CMW_BUILD_ROS_WRAPPER=OFF
        - -DHOLO_CMW_BUILD_OPENDDS_WRAPPER=OFF
        - -DHOLO_CMW_BUILD_UMB_WRAPPER=ON
        - ${SOURCE_ROOT}
    steps: null

  holo_map_local_service_server:
    url: ${git_url}/map/holo_map_local_service_server.git
    branch: release/v0.1
    dependencies:
    - CS
    - MAP
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []

  holo_map_local_service_client/tools:
    url: holo_map_local_service_client/tools
    branch: release/v0.1
    dependencies:
    - CS
    - MAP
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []

  BaseCampMapApplication:
    dependencies:
    - holo_map_local_service_server
    - holo_map_local_service_client/tools
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null

  holo_localization_fusion_cmw_app:
    url: ${git_url}/mlc/holo_localization_fusion_cmw_app.git
    branch: release/v0.1
    dependencies:
    - CS
    - MLC
    - MAP
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []

  holo_localization_vision_cmw_app:
    url: ${git_url}/mlc/holo_localization_vision_cmw_app.git
    branch: release/v0.1
    dependencies:
    - CS
    - MLC
    - VS
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []

  BaseCampMlcApplication:
    dependencies:
    - holo_localization_fusion_cmw_app
    - holo_localization_vision_cmw_app
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null

  holo_perception_pilot:
    url: ${git_url}/per/holo_perception_pilot.git
    branch: wh01-develop
    dependencies:
    - CS
    - PER
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []

  holo_perception_pilot/cmw_app:
    url: holo_perception_pilot/cmw_app
    dependencies:
    - CS
    - PER
    - holo_perception_pilot
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []

  BaseCampPerApplication:
    dependencies:
    - holo_perception_pilot/cmw_app
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null

  holo_sensors_cmw_app:
    url: ${git_url}/vs/holo_sensors_cmw_app.git
    branch: wh01/r1
    dependencies:
    - CS
    - VS
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []

  BaseCampVsApplication:
    dependencies:
    - holo_sensors_cmw_app
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null

  holo_control:
    url: ${git_url}/pc/holo_control.git
    branch: release/v0.1
    dependencies:
    - CS
    - PC
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []

  holo_control/cmw_app:
    url: holo_control/cmw_app
    dependencies:
    - CS
    - PC
    - holo_control
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []

  BaseCampPcApplication:
    dependencies:
    - holo_control/cmw_app
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null

  BaseCampApplication:
    dependencies:
    - BaseCampMapApplication
    - BaseCampMlcApplication
    - BaseCampVsApplication
    - BaseCampPerApplication
    - BaseCampPcApplication
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
version: 1
