base: BaseCamp/Library/CS/thirdparty/develop
projects:
  holo_cmake_scripts:
    url: ${git_url}/bccs/holo_cmake_scripts.git
    branch: dragonglass-develop
    commands:
      build:
        command: ''
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_3rdparty:
    env:
      PKG_CONFIG_PATH: ${HOLO_ROOT}/lib/pkgconfig:${HOLO_ROOT}/3rdparty/lib/pkgconfig:${PKG_CONFIG_PATH}
      CFLAGS: -I${HOLO_ROOT}/3rdparty/include ${CFLAGS}
      CXXFLAGS: -I${HOLO_ROOT}/3rdparty/include ${CXXFLAGS}
      LDFLAGS: -L${HOLO_ROOT}/3rdparty/lib -Wl,-rpath-link,${HOLO_ROOT}/3rdparty/lib
        ${LDFLAGS}
      PATH: ${HOLO_ROOT}/../host/bin:${PATH}
    url: ${git_url}/bccs/holo_3rdparty.git
    branch: dragonglass-develop
    dependencies:
    - holo_cmake_scripts
    commands:
      configure:
        arguments:
        - -DHOLO_3RDPARTY_FORCE_BUILD=ON
        - -DGTSAM_VERSION=4.0.2
        - -DOPENCV_BUILD_opencv_objdetect=ON
        - ${SOURCE_ROOT}
        arguments_aarch64_linux-c52:
        - -DHOLO_3RDPARTY_FORCE_BUILD=ON
        - -DOPENCV_WITH_GTK=ON
        - -DOPENCV_SKIP_CACHE=ON
        - -DOPENDDS_VERSION=3.13.2
        - ${SOURCE_ROOT}
      install:
        command: ''
        arguments: []
    steps: null
    package:
      manifest: null
      files: []
      directories:
      - ${HOLO_ROOT}/3rdparty
      - ${HOLO_ROOT}/../host
  holo_base_c:
    url: ${git_url}/bccs/holo_base_c.git
    branch: dragonglass-develop
    dependencies:
    - holo_3rdparty
    - holo_cmake_scripts
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_utils:
    url: ${git_url}/bccs/holo_utils.git
    branch: dragonglass-develop
    dependencies:
    - holo_3rdparty
    - holo_cmake_scripts
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_base:
    url: ${git_url}/bccs/holo_base.git
    branch: dragonglass-develop
    dependencies:
    - holo_3rdparty
    - holo_base_c
    - holo_utils
    - holo_metadata_cpp
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_cmw:
    env:
      PYTHONPATH: ${SYSROOT}/usr/lib/python2.7/dist-packages
    url: ${git_url}/bccs/holo_cmw.git
    branch: dragonglass-develop
    dependencies:
    - holo_base
    - holo_utils
    commands:
      configure:
        command: cmake
        arguments:
        - -DHOLO_CMW_BUILD_OPENDDS_WRAPPER=ON
        - ${SOURCE_ROOT}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_base_msg:
    env:
      PYTHONPATH: ${SYSROOT}/usr/lib/python2.7/dist-packages
    url: ${git_url}/cmw/holo_base_msg.git
    branch: dragonglass-develop
    dependencies:
    - holo_base
    - holo_cmw
    commands:
      test:
        command: make
        arguments:
        - test
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_metadata_cpp:
    url: ${git_url}/bccs/holo_metadata_cpp.git
    branch: dragonglass-develop
    dependencies:
    - holo_3rdparty
    - holo_cmake_scripts
    commands:
      test:
        command: make
        arguments:
        - test
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_metadata_py:
    url: ${git_url}/bccs/holo_metadata_py.git
    branch: dragonglass-develop
    dependencies: [holo_cmake_scripts]
    commands:
      configure:
        command: ''
      build:
        env:
          PYTHONUSERBASE: ${HOLO_ROOT}
        command: './setup.py'
        arguments: ["build"]
        parallel_arg: ""
        working_directory: ${SOURCE_ROOT}
      install:
        env:
          PYTHONUSERBASE: ${HOLO_ROOT}
        command: 'make'
        arguments: ["install"]
        parallel_arg: ""
        working_directory: ${SOURCE_ROOT}
    steps: null
    package:
      manifest: ${SOURCE_ROOT}/install_manifest.txt
      files: []
      directories: []

  holobag_tools:
    url: ${git_url}/bccs/holobag_tools.git
    branch: dragonglass-develop
    dependencies: [holo_cmake_scripts, holo_metadata_py]
    commands:
      configure:
        command: ''
      build:
        env:
          PYTHONUSERBASE: ${HOLO_ROOT}
        command: './setup.py'
        arguments: ["build"]
        parallel_arg: ""
        working_directory: ${SOURCE_ROOT}
      install:
        env:
          PYTHONUSERBASE: ${HOLO_ROOT}
        command: 'make'
        arguments: ["install"]
        parallel_arg: ""
        working_directory: ${SOURCE_ROOT}
    steps: null
    package:
      manifest: ${SOURCE_ROOT}/install_manifest.txt
      files: []
      directories: []

  CS:
    dependencies:
    - holo_cmake_scripts
    - holo_3rdparty
    - holo_base_c
    - holo_utils
    - holo_base
    - holo_cmw
    - holo_base_msg
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null

version: 1
