base: Pilot/develop
projects:
  holo_3rdparty:
    commands:
      build:
        arguments:
        - dragonglass
        - qpOASES
        - nanopb
        - flann
        - rply
        - boost
        - vptree
    steps: null
    package:
      manifest: null
      files: []
      directories:
      - ${HOLO_ROOT}/3rdparty
      - ${HOLO_ROOT}/../host
  holonext_3rdparty:
    env:
      CFLAGS: -I${HOLO_ROOT}/3rdparty/include ${CFLAGS}
      CXXFLAGS: -I${HOLO_ROOT}/3rdparty/include ${CXXFLAGS}
      LDFLAGS: -L${HOLO_ROOT}/3rdparty/lib -Wl,-rpath-link,${HOLO_ROOT}/3rdparty/lib
        ${LDFLAGS}
      PATH: ${HOLO_ROOT}/../host/bin:${PATH}
    url: ${git_url}/holonext/holonext_3rdparty.git
    branch: master
    commands:
      configure:
        arguments:
        - -DHOLONEXT_3RDPARTY_FORCE_BUILD=ON
        - ${SOURCE_ROOT}
      build:
        arguments:
        - pcl
      install:
        command: ''
        arguments: []
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holonext_base:
    url: ${git_url}/holonext/holonext_base.git
    branch: develop
    dependencies:
    - holo_3rdparty
    - holo_base_c
    - holo_base
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_dnn_base:
    url: ${git_url}/bcper/holo_dnn_base.git
    branch: dragonglass-develop
    dependencies:
    - holo_base
    - holo_perception_base
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_dnn_xavier:
    url: ${git_url}/per/holo_dnn_xavier.git
    branch: dragonglass-develop
    dependencies:
    - holo_base
    - holo_perception_base
    - holo_dnn_base
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_3d:
    url: ${git_url}/mlc/holo_3d.git
    branch: dragonglass-develop
    dependencies:
    - holo_3rdparty
    - holo_base
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holonext_localization_base:
    url: ${git_url}/holonext/holonext_localization_base.git
    branch: develop
    dependencies:
    - holonext_base
    - holo_localization_base
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_map_core:
    url: ${git_url}/map/holo_map_core.git
    branch: holonext-develop
    dependencies:
    - holo_base
    - holo_map_base
    - holo_map_format
    - holo_map_common
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holonext_perception_base:
    url: ${git_url}/holonext/holonext_perception_base.git
    branch: develop
    dependencies:
    - holonext_3rdparty
    - holonext_base
    - holo_3d
    - holo_perception_base
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holonext_control_base:
    url: ${git_url}/holonext/holonext_control_base.git
    branch: develop
    dependencies:
    - holonext_base
    - holo_control_base
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holonext_sensors_base:
    url: ${git_url}/holonext/holonext_sensors_base.git
    branch: develop
    dependencies:
    - holonext_base
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holonext_base_msg:
    url: ${git_url}/holonext/holonext_base_msg.git
    branch: develop
    dependencies:
    - holonext_base
    - holo_cmw
    - holo_base_msg
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  BaseCampNext:
    dependencies:
    - holo_3rdparty
    - holonext_3rdparty
    - holonext_base
    - holo_3d
    - holonext_localization_base
    - holo_map_core
    - holonext_perception_base
    - holonext_control_base
    - holonext_sensors_base
    - holonext_base_msg
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
version: 1
