base: BaseCamp/Application/Dev/develop
projects:
  holo_base:
    branch: feature/tmp/gh02_interface
  holo_cmw:
    branch: feature/mdc_cm
    commands:
      configure:
        arguments:
        - -DHOLO_CMW_BUILD_ROS_WRAPPER=OFF
        - -DHOLO_CMW_BUILD_OPENDDS_WRAPPER=OFF
        - -DHOLO_CMW_BUILD_UMB_WRAPPER=OFF
        - -DHOLO_CMW_BUILD_DDS_MICRO_WRAPPER=OFF
        - -DHOLO_CMW_BUILD_MDC_CM_WRAPPER=ON
        - ${SOURCE_ROOT}
    steps: null
  holo_base_msg:
    branch: feature/GH02/0930
  gh02_msg:
    url: ${git_url}/gh/gh02_msg.git
    branch: dragonglass-develop
    dependencies:
      - BaseCamp
    commands:
      test:
        command: make
        arguments:
         - test
         - '||'
         - 'true'
      configure:
        arguments:
         - -DHOLO_BUILD_CM_TRAITS=ON
         - ${SOURCE_ROOT}
      doc:
        command: make
        arguments:
         - doc
      coverage:
        command: make
        arguments:
         - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_x_client:
    commands:
      configure:
        arguments:
        - -DUSE_OPENDDS_WARPPER=OFF
        - -DUSE_MDC_CM_WARPPER=ON
        - ${SOURCE_ROOT}
    url: ${git_url}/sim/holo_x_client.git
    dependencies: [BaseCamp,gh02_msg]
    branch: dragonglass-develop
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
