base: BaseCamp/Library/release/2021.09
projects:
  holo_map_local_service_server:
    url: ${git_url}/map/holo_map_local_service_server.git
    branch: release/v0.2
    dependencies:
    - CS
    - MAP
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_map_local_service_client/tools:
    url: holo_map_local_service_client/tools
    branch: release/v0.2
    dependencies:
    - CS
    - MAP
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  BaseCampMapApplication:
    dependencies:
    - holo_map_local_service_server
    - holo_map_local_service_client/tools
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
  holo_localization_fusion_cmw_app:
    url: ${git_url}/mlc/holo_localization_fusion_cmw_app.git
    branch: release/v0.2
    dependencies:
    - CS
    - MLC
    - MAP
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_vision_cmw_app:
    url: ${git_url}/mlc/holo_localization_vision_cmw_app.git
    branch: v0.1.1
    dependencies:
    - CS
    - MLC
    - VS
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  BaseCampMlcApplication:
    dependencies:
    - holo_localization_fusion_cmw_app
    - holo_localization_vision_cmw_app
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
  holo_sensors_cmw_app:
    url: ${git_url}/vs/holo_sensors_cmw_app.git
    branch: release/v0.3
    dependencies:
    - CS
    - VS
    commands:
      configure:
        arguments_tda4_qnx-7.0.0:
        - -DHOLO_BUILD_ON_TDA4=ON
        - -DHOLO_BUILD_ON_QNX=ON
        - ${SOURCE_ROOT}
        arguments_tda4_ubuntu-18.04:
        - -DHOLO_BUILD_ON_TDA4=ON
        - ${SOURCE_ROOT}
        arguments_MDC610-1.0.012-B0120000.B011:
        - -DHOLO_BUILD_ON_MDC610=ON
        - ${SOURCE_ROOT}
        arguments_mdc300_ubuntu-16.04:
        - -DHOLO_BUILD_ON_MDC300=ON
        - ${SOURCE_ROOT}
        arguments_mdc300-mini_ubuntu-16.04:
        - -DHOLO_BUILD_ON_MDC300=ON
        - ${SOURCE_ROOT}
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  BaseCampVsApplication:
    dependencies:
    - holo_sensors_cmw_app
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
  holo_control:
    url: ${git_url}/pc/holo_control.git
    branch: release/v0.2
    dependencies:
    - CS
    - PC
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_control/cmw_app:
    url: holo_control/cmw_app
    dependencies:
    - CS
    - PC
    - holo_control
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_pctoolkits/cmw_app:
    url: holo_pctoolkits/cmw_app
    dependencies:
    - CS
    - PC
    - holo_pctoolkits
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  BaseCampPcApplication:
    dependencies:
    - holo_control/cmw_app
    - holo_pctoolkits/cmw_app
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
  BaseCampApplication:
    dependencies:
    - BaseCampMapApplication
    - BaseCampMlcApplication
    - BaseCampVsApplication
    - BaseCampPcApplication
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
version: 1
