base: BaseCamp/Library/develop
projects:
  holo_3rdparty:
    commands:
      configure:
        arguments:
        - -DHOLO_3RDPARTY_FORCE_BUILD=ON
        - -DOPENCV_WITH_GTK=ON
        - -DOPENCV_SKIP_CACHE=ON
        - -DOPENDDS_VERSION=3.14
        - -DGTSAM_VERSION=4.0.2
        - ${SOURCE_ROOT}
      build:
        arguments:
        - proj4
        - yaml-cpp
        - eigen3
        - glog
        - nanopb
        - flann
        - rply
        - opencv
        - ffmpeg
        - apriltag
        - qpOASES
        - qpOASES_e
        - protobuf
        - gtsam
        - gtest-1.8.1
        - opendds
        - log4cplus
        - lz4
        - jpeg
    steps: null
    package:
      manifest: null
      files: []
      directories:
      - ${HOLO_ROOT}/3rdparty
      - ${HOLO_ROOT}/../host
  holo_cmw:
    branch: bugfix/hhm/fanya
    commands:
      configure:
        arguments:
        - -DHOLO_CMW_BUILD_ROS_WRAPPER=OFF
        - -DHOLO_CMW_BUILD_OPENDDS_WRAPPER=ON
        - -DHOLO_CMW_BUILD_UMB_WRAPPER=OFF
        - -DHOLO_CMW_BUILD_DDS_MICRO_WRAPPER=OFF
        - ${SOURCE_ROOT}
    steps: null

  holo_x_client:
      url: ${git_url}/~gaochengbin/holo_x_client.git
      dependencies: [holo_cmw, holo_base_msg, holo_sensors_base]
      branch: zgg/holo_cmw_V2_opendds


