base: BaseCamp/Library/release/2021.02
projects:
  holo_3rdparty:
    commands:
      configure:
        arguments:
        - -DHOLO_3RDPARTY_FORCE_BUILD=ON
        - -DOPENCV_WITH_GTK=ON
        - -DOPENCV_SKIP_CACHE=ON
        - -DGTSAM_VERSION=4.0.2
        - ${SOURCE_ROOT}
      build:
        arguments:
        - proj4
        - yaml-cpp
        - eigen3
        - glog
        - nanopb
        - flann
        - rply
        - opencv
        - ffmpeg
        - qpOASES
        - qpOASES_e
        - protobuf
        - gtsam
        - gtest-1.8.1
        - opendds
        - torch
    steps: null
    package:
      manifest: null
      files: []
      directories:
      - ${HOLO_ROOT}/3rdparty
      - ${HOLO_ROOT}/../host
  holo_cmw:
    commands:
      configure:
        arguments:
        - -DHOLO_CMW_BUILD_ROS_WRAPPER=ON
        - ${SOURCE_ROOT}
    steps: null
  holo_sensors_base:
    url: ${git_url}/vs/holo_sensors_base.git
    branch: gh01/r1
    dependencies:
    - holo_3rdparty
    - holo_base
    - holo_sensors_c
    - holo_parking_base
    commands:
      configure:
        arguments:
        - ${SOURCE_ROOT}
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_sensors_cmw_app:
    url: ${git_url}/vs/holo_sensors_cmw_app.git
    branch: gh01/r1
    dependencies:
    - holo_sensors_base
    - holo_cmw
    - holo_base_msg
    - holo_parking_msg
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_io:
    url: ${git_url}/base/holo_io.git
    branch: gh01/r1
    dependencies:
    - holo_base
    - holo_cmw
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_parking_base:
    url: ${git_url}/parking/holo_parking_base.git
    branch: gh01/r1
    dependencies:
    - holo_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_parking_msg:
    url: ${git_url}/parking/holo_parking_msg.git
    branch: gh01/r1
    dependencies:
    - holo_cmw
    - holo_parking_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_perception_parking:
    url: ${git_url}/parking/holo_perception_parking.git
    branch: gh01/r1
    dependencies:
    - holo_base
    - holo_base_msg
    - holo_sensors_base
    - holo_perception_base
    - holo_dnn
    - holo_parking_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_perception_parking/cmw_app:
    url: holo_perception_parking/cmw_app
    dependencies:
    - holo_perception_parking
    - holo_cmw
    - holo_parking_msg
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_parking:
    url: ${git_url}/parking/holo_localization_parking.git
    branch: gh01/r1
    dependencies:
    - holo_base
    - holo_3d
    - holo_io
    - holo_localization_base
    - holo_base_msg
    - holo_parking_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_parking/cmw_app:
    url: holo_localization_parking/cmw_app
    dependencies:
    - holo_localization_parking
    - holo_cmw
    - holo_parking_msg
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_3d:
    url: ${git_url}/mlc/holo_3d.git
    branch: gh01/r1
    dependencies:
    - holo_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_deep:
    url: ${git_url}/mlc/holo_localization_deep.git
    branch: gh01/r1
    dependencies:
    - holo_base
    - holo_3d
    - holo_localization_base
    - holo_base_msg
    - holo_parking_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_deep/cmw_app:
    url: holo_localization_deep/cmw_app
    branch: gh01/r1
    dependencies:
    - holo_localization_deep
    - holo_cmw
    - holo_parking_msg
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_planning_parking:
    url: ${git_url}/parking/holo_planning_parking.git
    branch: gh01/r1
    dependencies:
    - holo_base
    - holo_planning_base
    - holo_base_msg
    - holo_io
    - holo_parking_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_planning_parking/cmw_app:
    url: holo_planning_parking/cmw_app
    dependencies:
    - holo_planning_parking
    - holo_cmw
    - holo_parking_msg
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_control_parking:
    url: ${git_url}/parking/holo_control_parking.git
    branch: gh01/r1
    dependencies:
    - holo_base
    - holo_base_msg
    - holo_parking_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_control_parking/cmw_app:
    url: holo_control_parking/cmw_app
    dependencies:
    - holo_control_parking
    - holo_cmw
    - holo_parking_msg
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  ParkingBaseCamp:
    dependencies:
    - holo_3rdparty
    - holo_base_c
    - holo_base
    - holo_cmw
    - holo_base_msg
    - holo_sensors_c
    - holo_sensors_base
    - holo_localization_base
    - holo_perception_base
    - holo_dnn
    - holo_planning_base
    - holo_control_base
    - holo_sensors_cmw_app
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
  ParkingApps:
    dependencies:
    - holo_localization_deep/cmw_app
    - holo_localization_parking/cmw_app
    - holo_planning_parking/cmw_app
    - holo_control_parking/cmw_app
    - holo_perception_parking/cmw_app
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
  ParkingHpp:
    dependencies:
    - ParkingBaseCamp
    - ParkingApps
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
version: 1
