base: null
commands:
  configure:
    command: cmake
    arguments:
    - ${SOURCE_ROOT}
    retcode: [0]
  build:
    command: make
    arguments: []
    parallel_arg: -j
    retcode: [0]
  install:
    command: make
    arguments:
    - install
    parallel_arg: -j
    retcode: [0]
  test:
    command: ''
    arguments: []
  doc:
    command: ''
    arguments: []
  coverage:
    command: ''
    arguments: []
steps:
- configure
- build
- install
projects:
  holo_3rdparty:
    env:
      CFLAGS: -I${HOLO_ROOT}/3rdparty/include ${CFLAGS}
      CXXFLAGS: -I${HOLO_ROOT}/3rdparty/include ${CXXFLAGS}
      LDFLAGS: -L${HOLO_ROOT}/3rdparty/lib -Wl,-rpath-link,${HOLO_ROOT}/3rdparty/lib
        ${LDFLAGS}
      PATH: ${HOLO_ROOT}/../host/bin:${PATH}
    url: ${git_url}/bccs/holo_3rdparty.git
    branch: dragonglass-develop
    commands:
      configure:
        arguments:
        - -DHOLO_3RDPARTY_FORCE_BUILD=ON
        - ${SOURCE_ROOT}
      build:
        arguments:
        - dragonglass
      install:
        command: ''
        arguments: []
    steps: null
    package:
      manifest: null
      files: []
      directories:
      - ${HOLO_ROOT}/3rdparty
      - ${HOLO_ROOT}/../host
  holo_cmake_scripts:
    url: ${git_url}/bccs/holo_cmake_scripts.git
    branch: master
    commands:
      build:
        command: ''
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_base_c:
    url: ${git_url}/bccs/holo_base_c.git
    branch: dragonglass-master
    dependencies:
    - holo_3rdparty
    - holo_cmake_scripts
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_sensors_c:
    url: ${git_url}/vs/holo_sensors_c.git
    branch: dragonglass-master
    dependencies:
    - holo_base_c
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_base:
    url: ${git_url}/bccs/holo_base.git
    branch: dragonglass-master
    dependencies:
    - holo_3rdparty
    - holo_base_c
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_cmw:
    url: ${git_url}/bccs/holo_cmw.git
    branch: dragonglass-master
    dependencies:
    - holo_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_base_msg:
    url: ${git_url}/cmw/holo_base_msg.git
    branch: dragonglass-master
    dependencies:
    - holo_base
    - holo_cmw
    commands:
      test:
        command: make
        arguments:
        - test
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_c:
    url: ${git_url}/mlc/holo_localization_c.git
    branch: dragonglass-master
    dependencies:
    - holo_base_c
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_base:
    url: ${git_url}/mlc/holo_localization_base.git
    branch: dragonglass-master
    dependencies:
    - holo_3rdparty
    - holo_base
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_fusion:
    url: ${git_url}/mlc/holo_localization_fusion.git
    branch: dragonglass-master
    dependencies:
    - holo_localization_base
    - holo_localization_semantic
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_semantic:
    url: ${git_url}/mlc/holo_localization_semantic.git
    branch: dragonglass-master
    dependencies:
    - holo_localization_base
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_vision:
    url: ${git_url}/mlc/holo_localization_vision.git
    branch: dragonglass-master
    dependencies:
    - holo_localization_base
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_map_base:
    url: ${git_url}/map/holo_map_base.git
    branch: dragonglass-master
    dependencies:
    - holo_base
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_map_common:
    url: ${git_url}/map/holo_map_common.git
    branch: dragonglass-master
    dependencies:
    - holo_base
    - holo_map_base
    - holo_map_format
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_map_format:
    url: ${git_url}/map/holo_map_format.git
    branch: dragonglass-master
    dependencies:
    - holo_base
    - holo_map_base
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_map_adapter:
    url: ${git_url}/map/holo_map_adapter.git
    branch: dragonglass-master
    dependencies:
    - holo_base
    - holo_map_base
    - holo_map_format
    - holo_map_common
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_map_local_service_server:
    url: ${git_url}/map/holo_map_local_service_server.git
    branch: dragonglass-master
    dependencies:
    - holo_base
    - holo_cmw
    - holo_base_msg
    - holo_map_base
    - holo_map_format
    - holo_map_common
    - holo_map_adapter
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_map_local_service_client:
    url: ${git_url}/map/holo_map_local_service_client.git
    branch: dragonglass-master
    dependencies:
    - holo_base
    - holo_map_base
    - holo_map_format
    - holo_map_common
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_map_local_service_client/tools:
    url: holo_map_local_service_client/tools
    branch: dragonglass-master
    dependencies:
    - holo_base
    - holo_cmw
    - holo_base_msg
    - holo_map_base
    - holo_map_format
    - holo_map_common
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_sensors:
    url: ${git_url}/vs/holo_sensors.git
    branch: dragonglass-master
    dependencies:
    - holo_3rdparty
    - holo_base
    - holo_sensors_c
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_perception_base:
    url: ${git_url}/per/holo_perception_base.git
    branch: dragonglass-master
    dependencies:
    - holo_3rdparty
    - holo_base
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_dnn_base:
    url: ${git_url}/bcper/holo_dnn_base.git
    branch: dragonglass-master
    dependencies:
    - holo_base
    - holo_perception_base
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_planning_base:
    url: ${git_url}/pc/holo_planning_base.git
    branch: dragonglass-master
    dependencies:
    - holo_base
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_control_base:
    url: ${git_url}/pc/holo_control_base.git
    branch: dragonglass-master
    dependencies:
    - holo_base_c
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  BaseCamp:
    dependencies:
    - holo_3rdparty
    - holo_base_c
    - holo_base
    - holo_cmw
    - holo_base_msg
    - holo_sensors_c
    - holo_sensors
    - holo_localization_base
    - holo_localization_fusion
    - holo_localization_semantic
    - holo_localization_vision
    - holo_map_base
    - holo_map_common
    - holo_map_format
    - holo_map_adapter
    - holo_map_local_service_server
    - holo_map_local_service_client
    - holo_perception_base
    - holo_dnn_base
    - holo_planning_base
    - holo_control_base
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
version: 1
