base: BaseCamp/Library/develop
projects:
  holo_sensors_cmw_app:
    commands:
      configure:
        arguments:
        - -DHOLO_BUILD_ON_MDC300=ON
        - ${SOURCE_ROOT}
    steps: null
  holo_sensors_mdc:
    url: ${git_url}/vs/holo_sensors_mdc.git
    branch: dragonglass-develop
    dependencies:
    - holo_base
    - holo_sensors_base
    commands:
      configure:
        arguments:
        - -DHOLO_BUILD_WITH_MINI=OFF
        - ${SOURCE_ROOT}
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_sensors_mdc/cmw_app:
    url: holo_sensors_mdc/cmw_app
    branch: dragonglass-develop
    dependencies:
    - holo_base_msg
    - holo_sensors_mdc
    commands:
      configure:
        arguments:
        - -DHOLO_BUILD_WITH_MINI=OFF
        - ${SOURCE_ROOT}
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  SENSORS:
    dependencies:
    - holo_sensors_cmw_app
    - holo_sensors_mdc/cmw_app
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
version: 1
