base: BaseCamp/Library/CS/release/2021.09
projects:
  holo_localization_c:
    url: ${git_url}/mlc/holo_localization_c.git
    branch: release/v0.1
    dependencies:
    - CS
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_base:
    url: ${git_url}/mlc/holo_localization_base.git
    branch: release/v0.2
    dependencies:
    - CS
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_fusion:
    url: ${git_url}/mlc/holo_localization_fusion.git
    branch: release/v0.2
    dependencies:
    - holo_localization_base
    - holo_localization_semantic
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_semantic:
    url: ${git_url}/mlc/holo_localization_semantic.git
    branch: release/v0.2
    dependencies:
    - holo_localization_base
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_vision:
    url: ${git_url}/mlc/holo_localization_vision.git
    branch: release/v0.1
    dependencies:
    - holo_localization_base
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  MLC:
    dependencies:
    - holo_localization_c
    - holo_localization_base
    - holo_localization_fusion
    - holo_localization_semantic
    - holo_localization_vision
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
version: 1
