base: BaseCamp/Library/CS/develop
projects:
  holo_localization_c:
    url: ${git_url}/bcmlc/holo_localization_c.git
    branch: dragonglass-develop
    dependencies:
    - CS
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_base:
    url: ${git_url}/bcmlc/holo_localization_base.git
    branch: dragonglass-develop
    dependencies:
    - CS
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_fusion:
    url: ${git_url}/bcmlc/holo_localization_fusion.git
    branch: dragonglass-develop
    dependencies:
    - holo_localization_base
    - holo_localization_semantic
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_semantic:
    url: ${git_url}/bcmlc/holo_localization_semantic.git
    branch: dragonglass-develop
    dependencies:
    - holo_localization_base
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_vision:
    url: ${git_url}/bcmlc/holo_localization_vision.git
    branch: dragonglass-develop
    dependencies:
    - holo_localization_base
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_3d:
    url: ${git_url}/bcmlc/holo_3d.git
    branch: dragonglass-develop
    dependencies:
    - CS
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_calibration:
    url: ${git_url}/bcmlc/holo_calibration.git
    branch: dragonglass-develop
    dependencies:
    - holo_localization_base
    - holo_3d
    commands:
      configure:
        arguments:
        - -DHOLO_BUILD_APP=ON
        - ${SOURCE_ROOT}
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []

  MLC:
    dependencies:
    - holo_localization_c
    - holo_localization_base
    - holo_localization_fusion
    - holo_localization_semantic
    - holo_3d
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
  MLCWithCalibration:
    dependencies:
    - MLC
    - holo_calibration
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
version: 1
