var:
  PATH: ${SYSROOT}/../resources/toolchain/aarch64/gcc-7.5.0/bin:${HOLO_ROOT}/../host/bin::/usr/local/bin:/bin:/sbin:/usr/bin:/usr/sbin
  TOOLCHAIN_PREFIX: aarch64-linux-gnu-
  TARGET_ROOT: ${CROSSTOOL_ROOT}/dura-yocto
  PKG_CONFIG_PATH: ${SYSROOT}/usr/lib/pkgconfig:${SYSROOT}/usr/share/pkgconfig:${SYSROOT}/usr/lib/aarch64-poky-linux/pkgconfig
  LDFLAGS: -Wl,-rpath-link,${SYSROOT}/usr/lib/aarch64-poky-linux:${SYSROOT}/lib/aarch64-poky-linux:${HOLO_ROOT}/3rdparty/lib:${HOLO_ROOT}/lib
env:
  PATH: ${PATH}
  LANG: $ENV{LANG}
  TERM: $ENV{TERM}
  PWD: $ENV{PWD}
  SHELL: $ENV{SHELL}
  USER: $ENV{USER}
  HOME: $ENV{HOME}
  PKG_CONFIG_PATH: ${SYSROOT}/usr/lib/pkgconfig:${SYSROOT}/usr/share/pkgconfig:${SYSROOT}/usr/lib/aarch64-poky-linux/pkgconfig
  PKG_CONFIG_LIBDIR: ${SYSROOT}/usr/lib/pkgconfig:${SYSROOT}/usr/share/pkgconfig:${SYSROOT}/usr/lib/aarch64-poky-linux/pkgconfig
  PKG_CONFIG_SYSROOT_DIR: ${SYSROOT}
  CC: ${TOOLCHAIN_PREFIX}gcc --sysroot=${SYSROOT}
  CXX: ${TOOLCHAIN_PREFIX}g++ --sysroot=${SYSROOT}
  RANLIB: ${TOOLCHAIN_PREFIX}ranlib
  AR: ${TOOLCHAIN_PREFIX}ar
  LD: ${TOOLCHAIN_PREFIX}ld
  NM: ${TOOLCHAIN_PREFIX}nm
  OBJDUMP: ${TOOLCHAIN_PREFIX}objdump
  STRIP: ${TOOLCHAIN_PREFIX}strip
  LDFLAGS: -Wl,-rpath-link,${SYSROOT}/usr/lib/aarch64-poky-linux:${SYSROOT}/lib/aarch64-poky-linux:${HOLO_ROOT}/3rdparty/lib:${HOLO_ROOT}/lib
  CFLAGS: ${CFLAGS}
  CXXFLAGS: ${CXXFLAGS}
  HOLO_ROOT: ${HOLO_ROOT}
toolchain_prefix: aarch64-linux-gnu-
target_root: ${CROSSTOOL_ROOT}/dura-yocto
crosstool:
- resources/toolchain/aarch64/gcc-7.5.0.tar.bz2
- c52-yocto.tar.bz2 
version: 1
