var:
  PATH: ${SYSROOT}/../resources/toolchain/aarch64/gcc-5.5.0/bin:${HOLO_ROOT}/../host/bin::/usr/local/bin:/bin:/sbin:/usr/bin:/usr/sbin
  TOOLCHAIN_PREFIX: aarch64-linux-gnu-
  TARGET_ROOT: ${CROSSTOOL_ROOT}/ubuntu-16.04-arm64
  PKG_CONFIG_PATH: ${SYSROOT}/usr/lib/pkgconfig:${SYSROOT}/usr/share/pkgconfig:${SYSROOT}/usr/lib/aarch64-linux-gnu/pkgconfig
  LDFLAGS: -Wl,-rpath-link,${SYSROOT}/usr/lib/aarch64-linux-gnu:${SYSROOT}/lib/aarch64-linux-gnu:${HOLO_ROOT}/3rdparty/lib:${HOLO_ROOT}/lib
  LD_LIBRARY_PATH: ${SYSROOT}/usr/lib/aarch64-linux-gnu:${SYSROOT}/lib/aarch64-linux-gnu:${HOLO_ROOT}/3rdparty/lib:${HOLO_ROOT}/lib
env:
  PATH: ${PATH}
  LANG: $ENV{LANG}
  TERM: $ENV{TERM}
  PWD: $ENV{PWD}
  SHELL: $ENV{SHELL}
  USER: $ENV{USER}
  HOME: $ENV{HOME}
  PKG_CONFIG_PATH: ${SYSROOT}/usr/lib/pkgconfig:${SYSROOT}/usr/share/pkgconfig:${SYSROOT}/usr/lib/aarch64-linux-gnu/pkgconfig
  PKG_CONFIG_LIBDIR: ${SYSROOT}/usr/lib/pkgconfig:${SYSROOT}/usr/share/pkgconfig:${SYSROOT}/usr/lib/aarch64-linux-gnu/pkgconfig
  PKG_CONFIG_SYSROOT_DIR: ${SYSROOT}
  ROS_LANG_DISABLE: geneus:genlisp:gennodejs
  ROS_PYTHON_VERSION: $ENV{ROS_PYTHON_VERSION}
  CMAKE_PREFIX_PATH: ${HOLO_ROOT}/../host:$SHELL{dirname `find ${SYSROOT}/opt/ros
    -name .catkin`}
  CC: ${TOOLCHAIN_PREFIX}gcc --sysroot=${SYSROOT}
  CXX: ${TOOLCHAIN_PREFIX}g++ --sysroot=${SYSROOT}
  RANLIB: ${TOOLCHAIN_PREFIX}ranlib
  AR: ${TOOLCHAIN_PREFIX}ar
  LD: ${TOOLCHAIN_PREFIX}ld
  NM: ${TOOLCHAIN_PREFIX}nm
  OBJDUMP: ${TOOLCHAIN_PREFIX}objdump
  STRIP: ${TOOLCHAIN_PREFIX}strip
  LDFLAGS: -Wl,-rpath-link,${SYSROOT}/usr/lib/aarch64-linux-gnu:${SYSROOT}/lib/aarch64-linux-gnu:${HOLO_ROOT}/3rdparty/lib:${HOLO_ROOT}/lib
  LD_LIBRARY_PATH: ${SYSROOT}/usr/lib/aarch64-linux-gnu:${SYSROOT}/lib/aarch64-linux-gnu:${HOLO_ROOT}/3rdparty/lib:${HOLO_ROOT}/lib
  HOLO_3RDPARTY_CACHE_ROOT: /opt/DataStore/libs/aarch64/ubuntu-16.04
  CFLAGS: ${CFLAGS}
  CXXFLAGS: ${CXXFLAGS}
  HOLO_ROOT: ${HOLO_ROOT}
toolchain_prefix: aarch64-linux-gnu-
target_root: ${CROSSTOOL_ROOT}/ubuntu-16.04-arm64
crosstool:
- ubuntu-16.04-arm64.tar.bz2
- resources/toolchain/aarch64/gcc-5.5.0.tar.bz2
version: 1
