var:
  PATH: ${HOLO_ROOT}/../host/bin::/usr/local/bin:/bin:/sbin:/usr/bin:/usr/sbin
  TOOLCHAIN_PREFIX: ''
  TARGET_ROOT: ''
env:
  PATH: ${PATH}
  LANG: $ENV{LANG}
  TERM: $ENV{TERM}
  PWD: $ENV{PWD}
  SHELL: $ENV{SHELL}
  USER: $ENV{USER}
  HOME: $ENV{HOME}
  ROS_LANG_DISABLE: geneus:genlisp:gennodejs
  ROS_PYTHON_VERSION: $ENV{ROS_PYTHON_VERSION}
  CMAKE_PREFIX_PATH: ${HOLO_ROOT}/../host:$SHELL{dirname `find ${SYSROOT}/opt/ros
    -name .catkin`}
  HOLO_3RDPARTY_CACHE_ROOT: /opt/DataStore/libs/$SHELL{uname -p}/$SHELL{lsb_release
    -i|cut -f2|tr '[:upper:]' '[:lower:]'}-$SHELL{lsb_release -r|cut -f2}
  CFLAGS: ${CFLAGS}
  CXXFLAGS: ${CXXFLAGS}
  HOLO_ROOT: ${HOLO_ROOT}
toolchain_prefix: ''
target_root: /
version: 1
