var:
  PATH: ${SYSROOT}/../resources/toolchain/x86_64/gcc-7.5.0/bin:${HOLO_ROOT}/../host/bin::/usr/local/bin:/bin:/sbin:/usr/bin:/usr/sbin
  TOOLCHAIN_PREFIX: x86_64-linux-gnu-
  TARGET_ROOT: ${CROSSTOOL_ROOT}/ubuntu-base-18.04-amd64
  PKG_CONFIG_PATH: ${SYSROOT}/usr/lib/pkgconfig:${SYSROOT}/usr/share/pkgconfig:${SYSROOT}/usr/lib/x86_64-linux-gnu/pkgconfig
  LDFLAGS: -Wl,-rpath-link,${SYSROOT}/usr/lib/x86_64-linux-gnu:${SYSROOT}/lib/x86_64-linux-gnu:${HOLO_ROOT}/3rdparty/lib:${HOLO_ROOT}/lib
  LD_LIBRARY_PATH: ${HOLO_ROOT}/3rdparty/lib:${HOLO_ROOT}/lib
env:
  PATH: ${PATH}
  LANG: $ENV{LANG}
  TERM: $ENV{TERM}
  PWD: $ENV{PWD}
  SHELL: $ENV{SHELL}
  USER: $ENV{USER}
  HOME: $ENV{HOME}
  PKG_CONFIG_PATH: ${SYSROOT}/usr/lib/pkgconfig:${SYSROOT}/usr/share/pkgconfig:${SYSROOT}/usr/lib/x86_64-linux-gnu/pkgconfig
  PKG_CONFIG_LIBDIR: ${SYSROOT}/usr/lib/pkgconfig:${SYSROOT}/usr/share/pkgconfig:${SYSROOT}/usr/lib/x86_64-linux-gnu/pkgconfig
  PKG_CONFIG_SYSROOT_DIR: ${SYSROOT}
  ROS_LANG_DISABLE: geneus:genlisp:gennodejs
  ROS_PYTHON_VERSION: $ENV{ROS_PYTHON_VERSION}
  CMAKE_PREFIX_PATH: "${HOLO_ROOT}/../host:\
                      ${SYSROOT}/../resources/package/multiarch/dds_micro:\
                      ${SYSROOT}/../resources/package/x86_64/mdc_cm/usr/local/AdaptiveAutoSar:\
                      ${SYSROOT}/../resources/package/x86_64/umb-0.0.0"
  CC: ${TOOLCHAIN_PREFIX}gcc --sysroot=${SYSROOT}
  CXX: ${TOOLCHAIN_PREFIX}g++ --sysroot=${SYSROOT}
  RANLIB: ${TOOLCHAIN_PREFIX}ranlib
  AR: ${TOOLCHAIN_PREFIX}ar
  LD: ${TOOLCHAIN_PREFIX}ld
  NM: ${TOOLCHAIN_PREFIX}nm
  OBJDUMP: ${TOOLCHAIN_PREFIX}objdump
  STRIP: ${TOOLCHAIN_PREFIX}strip
  LDFLAGS: "-Wl,-rpath-link,\
            ${HOLO_ROOT}/3rdparty/lib:\
            ${HOLO_ROOT}/lib:\
            ${SYSROOT}/usr/lib/x86_64-linux-gnu:\
            ${SYSROOT}/lib/x86_64-linux-gnu:\
            ${SYSROOT}/../resources/package/multiarch/dds_micro/lib/i86Linux4gcc7.3.0:\
            ${SYSROOT}/../resources/package/x86_64/mdc_cm/usr/local/AdaptiveAutoSar/lib:\
            ${SYSROOT}/../resources/package/x86_64/umb-0.0.0/lib"
  LD_LIBRARY_PATH: "${HOLO_ROOT}/3rdparty/lib:\
                    ${HOLO_ROOT}/lib:\
                    ${SYSROOT}/../resources/package/multiarch/dds_micro/lib/i86Linux4gcc7.3.0:\
                    ${SYSROOT}/../resources/package/x86_64/mdc_cm/usr/local/AdaptiveAutoSar/lib:\
                    ${SYSROOT}/../resources/package/x86_64/umb-0.0.0/lib"
  HOLO_3RDPARTY_CACHE_ROOT: /opt/DataStore/libs/x86_64/ubuntu-18.04
  CFLAGS: ${CFLAGS}
  CXXFLAGS: ${CXXFLAGS}
  HOLO_ROOT: ${HOLO_ROOT}
  MDC_DEVELOPMENT_STUDIO_ROOT: ${CROSSTOOL_ROOT}/resources/toolchain/mdc610/MDC_Development_Studio-Ubuntu18-1.0.017-T
toolchain_prefix: x86_64-linux-gnu-
target_root: ${CROSSTOOL_ROOT}/ubuntu-base-18.04-amd64
crosstool:
- ubuntu-base-18.04-amd64.tar.bz2
- resources/toolchain/x86_64/gcc-7.5.0.tar.bz2
- resources/package/multiarch/dds_micro.tar.bz2
- resources/package/x86_64/mdc_cm.tar.bz2
- resources/package/x86_64/umb-0.0.0.tar.bz2
version: 1
