// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p19
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:152

#ifndef _TAO_IDL__HOME_HOLO_WORKSPACE_BUILD_TDA4_UBUNTU_18_04_DEBUG_HOLO_BASE_MSG_INCLUDE_HOLO_BASE_MSG_MAP_GEOFENCEC_P1XNY3_H_
#define _TAO_IDL__HOME_HOLO_WORKSPACE_BUILD_TDA4_UBUNTU_18_04_DEBUG_HOLO_BASE_MSG_INCLUDE_HOLO_BASE_MSG_MAP_GEOFENCEC_P1XNY3_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/ORB.h"
#include "tao/Basic_Types.h"
#include "tao/Sequence_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "holo_base_msg/core/TypesC.h"
#include "holo_base_msg/common/CommonC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 2 || TAO_BETA_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:38

namespace holo_base_msg
{

  // TAO_IDL - Generated from
  // be/be_visitor_module/module_ch.cpp:38

  namespace map
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:261

    struct Geofence;

    typedef
      ::TAO_Fixed_Var_T<
          Geofence
        >
      Geofence_var;

    typedef
      Geofence &
      Geofence_out;

    // TAO_IDL - Generated from
    // be/be_visitor_structure/structure_ch.cpp:51

    struct  Geofence
    {

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef Geofence_var _var_type;
      typedef Geofence_out _out_type;

      static void _tao_any_destructor (void *);
      
      holo_base_msg::core::uint64_t id;
      holo_base_msg::core::uint8_t function;
      holo_base_msg::core::int32_t start_distance;
      holo_base_msg::core::int32_t end_distance;
    };

    // TAO_IDL - Generated from
    // be/be_visitor_typecode/typecode_decl.cpp:37

    extern  ::CORBA::TypeCode_ptr const _tc_Geofence;

    // TAO_IDL - Generated from
    // be/be_visitor_sequence/sequence_ch.cpp:102

#if !defined (_HOLO_BASE_MSG_MAP_GEOFENCESEQUENCE_CH_)
#define _HOLO_BASE_MSG_MAP_GEOFENCESEQUENCE_CH_

    class GeofenceSequence;

    typedef
      ::TAO_FixedSeq_Var_T<
          GeofenceSequence
        >
      GeofenceSequence_var;

    typedef
      ::TAO_Seq_Out_T<
          GeofenceSequence
        >
      GeofenceSequence_out;

    class  GeofenceSequence
      : public
          ::TAO::unbounded_value_sequence<
              Geofence
            >
    {
    public:
      GeofenceSequence (void);
      GeofenceSequence ( ::CORBA::ULong max);
      GeofenceSequence (
        ::CORBA::ULong max,
        ::CORBA::ULong length,
        Geofence* buffer,
        ::CORBA::Boolean release = false);
#if defined (ACE_HAS_CPP11)
      GeofenceSequence (const GeofenceSequence &) = default;
      GeofenceSequence (GeofenceSequence &&) = default;
      GeofenceSequence& operator= (const GeofenceSequence &) = default;
      GeofenceSequence& operator= (GeofenceSequence &&) = default;
#endif /* ACE_HAS_CPP11 */
      virtual ~GeofenceSequence (void);
      

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef GeofenceSequence_var _var_type;
      typedef GeofenceSequence_out _out_type;

      static void _tao_any_destructor (void *);
    };

#endif /* end #if !defined */

    // TAO_IDL - Generated from
    // be/be_visitor_typecode/typecode_decl.cpp:37

    extern  ::CORBA::TypeCode_ptr const _tc_GeofenceSequence;

    // TAO_IDL - Generated from
    // be/be_type.cpp:261

    struct Geofences;

    typedef
      ::TAO_Var_Var_T<
          Geofences
        >
      Geofences_var;

    typedef
      ::TAO_Out_T<
          Geofences
        >
      Geofences_out;

    // TAO_IDL - Generated from
    // be/be_visitor_structure/structure_ch.cpp:51

    struct  Geofences
    {

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef Geofences_var _var_type;
      typedef Geofences_out _out_type;

      static void _tao_any_destructor (void *);
      
      holo_base_msg::common::Timestamp stamp;
      holo_base_msg::map::GeofenceSequence geofences;
    };

    // TAO_IDL - Generated from
    // be/be_visitor_typecode/typecode_decl.cpp:37

    extern  ::CORBA::TypeCode_ptr const _tc_Geofences;
  
  // TAO_IDL - Generated from
  // be/be_visitor_module/module_ch.cpp:67
  
  } // module holo_base_msg::map

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:67

} // module holo_base_msg

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::holo_base_msg::map::Geofence>
    : public
        Fixed_Size_Arg_Traits_T<
            ::holo_base_msg::map::Geofence,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class Arg_Traits< ::holo_base_msg::map::GeofenceSequence>
    : public
        Var_Size_Arg_Traits_T<
            ::holo_base_msg::map::GeofenceSequence,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::holo_base_msg::map::Geofences>
    : public
        Var_Size_Arg_Traits_T<
            ::holo_base_msg::map::Geofences,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:62

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace holo_base_msg
{
  
  namespace map
  {
     void operator<<= (::CORBA::Any &, const ::holo_base_msg::map::Geofence &); // copying version
     void operator<<= (::CORBA::Any &, ::holo_base_msg::map::Geofence*); // noncopying version
     ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::holo_base_msg::map::Geofence *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::holo_base_msg::map::Geofence *&);
  }
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const holo_base_msg::map::Geofence &); // copying version
 void operator<<= (::CORBA::Any &, holo_base_msg::map::Geofence*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, holo_base_msg::map::Geofence *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const holo_base_msg::map::Geofence *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_sequence/any_op_ch.cpp:50



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace holo_base_msg
{
  
  namespace map
  {
     void operator<<= ( ::CORBA::Any &, const ::holo_base_msg::map::GeofenceSequence &); // copying version
     void operator<<= ( ::CORBA::Any &, ::holo_base_msg::map::GeofenceSequence*); // noncopying version
     ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::holo_base_msg::map::GeofenceSequence *&); // deprecated
     ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::holo_base_msg::map::GeofenceSequence *&);
  }
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= ( ::CORBA::Any &, const holo_base_msg::map::GeofenceSequence &); // copying version
 void operator<<= ( ::CORBA::Any &, holo_base_msg::map::GeofenceSequence*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, holo_base_msg::map::GeofenceSequence *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const holo_base_msg::map::GeofenceSequence *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace holo_base_msg
{
  
  namespace map
  {
     void operator<<= (::CORBA::Any &, const ::holo_base_msg::map::Geofences &); // copying version
     void operator<<= (::CORBA::Any &, ::holo_base_msg::map::Geofences*); // noncopying version
     ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::holo_base_msg::map::Geofences *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::holo_base_msg::map::Geofences *&);
  }
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const holo_base_msg::map::Geofences &); // copying version
 void operator<<= (::CORBA::Any &, holo_base_msg::map::Geofences*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, holo_base_msg::map::Geofences *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const holo_base_msg::map::Geofences *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const holo_base_msg::map::Geofence &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, holo_base_msg::map::Geofence &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:68

#if !defined _TAO_CDR_OP_holo_base_msg_map_GeofenceSequence_H_
#define _TAO_CDR_OP_holo_base_msg_map_GeofenceSequence_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const holo_base_msg::map::GeofenceSequence &_tao_sequence);
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    holo_base_msg::map::GeofenceSequence &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_holo_base_msg_map_GeofenceSequence_H_ */

// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const holo_base_msg::map::Geofences &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, holo_base_msg::map::Geofences &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_codegen.cpp:1703
#if defined (__ACE_INLINE__)
#include "GeofenceC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

