base:
- Pilot/GH02/develop
commands: {}
steps:
- configure
- build
- install
projects:
  # BaseCampApp
  holo_io:
    url: ${git_url}/base/holo_io.git
    branch: dragonglass-develop
    dependencies:
    - holo_base
    - holo_cmw
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_io/cmw_app:
    url: holo_io/cmw_app
    dependencies:
    - holo_io
    - holo_base_msg
    - gh02_msg
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_benchmark:
    url: ${git_url}/mlc/holo_localization_benchmark.git
    branch: dragonglass-develop
    dependencies:
    - holo_localization_base
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_benchmark/cmw_app:
    url: holo_localization_benchmark/cmw_app
    dependencies:
    - holo_localization_benchmark
    - holo_io
    - holo_cmw
    - holo_map_local_service_client
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_params:
    url: ${git_url}/vs/holo_params.git
    branch: dragonglass-develop
    commands:
      configure:
        command: 'cmake'
        arguments:
        - -DVID=gh02-2
        - ${SOURCE_ROOT}
        retcode: [0]
    steps:
        - configure
        - build
        - install
    package:
        manifest: ${BUILD_ROOT}/install_manifest.txt
        files: []
        directories: []
