base: BaseCamp/Library/CS/develop
projects:
  holo_planning_base:
    url: ${git_url}/pc/holo_planning_base.git
    branch: dragonglass-develop
    dependencies:
    - CS
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_control_base:
    url: ${git_url}/pc/holo_control_base.git
    branch: dragonglass-develop
    dependencies:
    - CS
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  PC:
    dependencies:
    - holo_planning_base
    - holo_control_base
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
version: 1
