base: BaseCamp/Library/CS/release/2022.03
projects:
  holo_sensors_c:
    url: ${git_url}/vs/holo_sensors_c.git
    branch: release/v0.4
    dependencies:
    - CS
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_sensors_base:
    url: ${git_url}/vs/holo_sensors_base.git
    branch: release/v0.8
    dependencies:
    - CS
    - holo_sensors_c
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  VS:
    dependencies:
    - holo_sensors_c
    - holo_sensors_base
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
version: 1
