base: Pilot/poc/hw_demo
projects:
  holo_base_c:
    branch: poc/W069
  holo_sensors_base:
    branch: poc/W069
    dependencies:
    - CS
    - holo_sensors_c
    - wh01_msg
  holo_sensors_cmw_app:
    branch: poc/W069
  wh01_msg:
    dependencies:
    - holo_base
    - holo_base_msg
