// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: holo/map/proto/base/object_stop_line.proto

#ifndef PROTOBUF_INCLUDED_holo_2fmap_2fproto_2fbase_2fobject_5fstop_5fline_2eproto
#define PROTOBUF_INCLUDED_holo_2fmap_2fproto_2fbase_2fobject_5fstop_5fline_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "holo/map/proto/common/coordinate.pb.h"
#include "holo/map/proto/common/geo_line.pb.h"
#include "holo/map/proto/common/geo_point.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_holo_2fmap_2fproto_2fbase_2fobject_5fstop_5fline_2eproto 

namespace protobuf_holo_2fmap_2fproto_2fbase_2fobject_5fstop_5fline_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_holo_2fmap_2fproto_2fbase_2fobject_5fstop_5fline_2eproto
namespace holo {
namespace map {
namespace proto {
namespace base {
class ObjectStopLine;
class ObjectStopLineDefaultTypeInternal;
extern ObjectStopLineDefaultTypeInternal _ObjectStopLine_default_instance_;
class ObjectStopLine_ExtraFirstLineEntry_DoNotUse;
class ObjectStopLine_ExtraFirstLineEntry_DoNotUseDefaultTypeInternal;
extern ObjectStopLine_ExtraFirstLineEntry_DoNotUseDefaultTypeInternal _ObjectStopLine_ExtraFirstLineEntry_DoNotUse_default_instance_;
class ObjectStopLine_ExtraSecondLineEntry_DoNotUse;
class ObjectStopLine_ExtraSecondLineEntry_DoNotUseDefaultTypeInternal;
extern ObjectStopLine_ExtraSecondLineEntry_DoNotUseDefaultTypeInternal _ObjectStopLine_ExtraSecondLineEntry_DoNotUse_default_instance_;
}  // namespace base
}  // namespace proto
}  // namespace map
}  // namespace holo
namespace google {
namespace protobuf {
template<> ::holo::map::proto::base::ObjectStopLine* Arena::CreateMaybeMessage<::holo::map::proto::base::ObjectStopLine>(Arena*);
template<> ::holo::map::proto::base::ObjectStopLine_ExtraFirstLineEntry_DoNotUse* Arena::CreateMaybeMessage<::holo::map::proto::base::ObjectStopLine_ExtraFirstLineEntry_DoNotUse>(Arena*);
template<> ::holo::map::proto::base::ObjectStopLine_ExtraSecondLineEntry_DoNotUse* Arena::CreateMaybeMessage<::holo::map::proto::base::ObjectStopLine_ExtraSecondLineEntry_DoNotUse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace holo {
namespace map {
namespace proto {
namespace base {

enum ObjectStopLine_StopLineType {
  ObjectStopLine_StopLineType_STOP_LINE_TYPE_UNDEFINED = 0,
  ObjectStopLine_StopLineType_STOP_LINE_TYPE_STRAIGHT = 1,
  ObjectStopLine_StopLineType_STOP_LINE_TYPE_TURN = 2,
  ObjectStopLine_StopLineType_STOP_LINE_TYPE_BICYCLE = 3,
  ObjectStopLine_StopLineType_STOP_LINE_TYPE_MOTORCYCLE = 4
};
bool ObjectStopLine_StopLineType_IsValid(int value);
const ObjectStopLine_StopLineType ObjectStopLine_StopLineType_StopLineType_MIN = ObjectStopLine_StopLineType_STOP_LINE_TYPE_UNDEFINED;
const ObjectStopLine_StopLineType ObjectStopLine_StopLineType_StopLineType_MAX = ObjectStopLine_StopLineType_STOP_LINE_TYPE_MOTORCYCLE;
const int ObjectStopLine_StopLineType_StopLineType_ARRAYSIZE = ObjectStopLine_StopLineType_StopLineType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ObjectStopLine_StopLineType_descriptor();
inline const ::std::string& ObjectStopLine_StopLineType_Name(ObjectStopLine_StopLineType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ObjectStopLine_StopLineType_descriptor(), value);
}
inline bool ObjectStopLine_StopLineType_Parse(
    const ::std::string& name, ObjectStopLine_StopLineType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ObjectStopLine_StopLineType>(
    ObjectStopLine_StopLineType_descriptor(), name, value);
}
enum ObjectStopLine_StopLineStyle {
  ObjectStopLine_StopLineStyle_STOP_LINE_STYLE_UNDEFINED = 0,
  ObjectStopLine_StopLineStyle_STOP_LINE_STYLE_SINGLE_SOLID_LINE = 1,
  ObjectStopLine_StopLineStyle_STOP_LINE_STYLE_DOUBLE_SOLID_LINE = 2
};
bool ObjectStopLine_StopLineStyle_IsValid(int value);
const ObjectStopLine_StopLineStyle ObjectStopLine_StopLineStyle_StopLineStyle_MIN = ObjectStopLine_StopLineStyle_STOP_LINE_STYLE_UNDEFINED;
const ObjectStopLine_StopLineStyle ObjectStopLine_StopLineStyle_StopLineStyle_MAX = ObjectStopLine_StopLineStyle_STOP_LINE_STYLE_DOUBLE_SOLID_LINE;
const int ObjectStopLine_StopLineStyle_StopLineStyle_ARRAYSIZE = ObjectStopLine_StopLineStyle_StopLineStyle_MAX + 1;

const ::google::protobuf::EnumDescriptor* ObjectStopLine_StopLineStyle_descriptor();
inline const ::std::string& ObjectStopLine_StopLineStyle_Name(ObjectStopLine_StopLineStyle value) {
  return ::google::protobuf::internal::NameOfEnum(
    ObjectStopLine_StopLineStyle_descriptor(), value);
}
inline bool ObjectStopLine_StopLineStyle_Parse(
    const ::std::string& name, ObjectStopLine_StopLineStyle* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ObjectStopLine_StopLineStyle>(
    ObjectStopLine_StopLineStyle_descriptor(), name, value);
}
enum ObjectStopLine_StopLineColor {
  ObjectStopLine_StopLineColor_STOP_LINE_COLOR_UNDEFINED = 0,
  ObjectStopLine_StopLineColor_STOP_LINE_COLOR_WHITE = 1,
  ObjectStopLine_StopLineColor_STOP_LINE_COLOR_YELLOW = 2
};
bool ObjectStopLine_StopLineColor_IsValid(int value);
const ObjectStopLine_StopLineColor ObjectStopLine_StopLineColor_StopLineColor_MIN = ObjectStopLine_StopLineColor_STOP_LINE_COLOR_UNDEFINED;
const ObjectStopLine_StopLineColor ObjectStopLine_StopLineColor_StopLineColor_MAX = ObjectStopLine_StopLineColor_STOP_LINE_COLOR_YELLOW;
const int ObjectStopLine_StopLineColor_StopLineColor_ARRAYSIZE = ObjectStopLine_StopLineColor_StopLineColor_MAX + 1;

const ::google::protobuf::EnumDescriptor* ObjectStopLine_StopLineColor_descriptor();
inline const ::std::string& ObjectStopLine_StopLineColor_Name(ObjectStopLine_StopLineColor value) {
  return ::google::protobuf::internal::NameOfEnum(
    ObjectStopLine_StopLineColor_descriptor(), value);
}
inline bool ObjectStopLine_StopLineColor_Parse(
    const ::std::string& name, ObjectStopLine_StopLineColor* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ObjectStopLine_StopLineColor>(
    ObjectStopLine_StopLineColor_descriptor(), name, value);
}
// ===================================================================

class ObjectStopLine_ExtraFirstLineEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<ObjectStopLine_ExtraFirstLineEntry_DoNotUse, 
    ::google::protobuf::uint32, ::holo::map::proto::common::GeoLine,
    ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<ObjectStopLine_ExtraFirstLineEntry_DoNotUse, 
    ::google::protobuf::uint32, ::holo::map::proto::common::GeoLine,
    ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  ObjectStopLine_ExtraFirstLineEntry_DoNotUse();
  ObjectStopLine_ExtraFirstLineEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const ObjectStopLine_ExtraFirstLineEntry_DoNotUse& other);
  static const ObjectStopLine_ExtraFirstLineEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const ObjectStopLine_ExtraFirstLineEntry_DoNotUse*>(&_ObjectStopLine_ExtraFirstLineEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class ObjectStopLine_ExtraSecondLineEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<ObjectStopLine_ExtraSecondLineEntry_DoNotUse, 
    ::google::protobuf::uint32, ::holo::map::proto::common::GeoLine,
    ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<ObjectStopLine_ExtraSecondLineEntry_DoNotUse, 
    ::google::protobuf::uint32, ::holo::map::proto::common::GeoLine,
    ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  ObjectStopLine_ExtraSecondLineEntry_DoNotUse();
  ObjectStopLine_ExtraSecondLineEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const ObjectStopLine_ExtraSecondLineEntry_DoNotUse& other);
  static const ObjectStopLine_ExtraSecondLineEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const ObjectStopLine_ExtraSecondLineEntry_DoNotUse*>(&_ObjectStopLine_ExtraSecondLineEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class ObjectStopLine : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:holo.map.proto.base.ObjectStopLine) */ {
 public:
  ObjectStopLine();
  virtual ~ObjectStopLine();

  ObjectStopLine(const ObjectStopLine& from);

  inline ObjectStopLine& operator=(const ObjectStopLine& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ObjectStopLine(ObjectStopLine&& from) noexcept
    : ObjectStopLine() {
    *this = ::std::move(from);
  }

  inline ObjectStopLine& operator=(ObjectStopLine&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ObjectStopLine& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ObjectStopLine* internal_default_instance() {
    return reinterpret_cast<const ObjectStopLine*>(
               &_ObjectStopLine_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(ObjectStopLine* other);
  friend void swap(ObjectStopLine& a, ObjectStopLine& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ObjectStopLine* New() const final {
    return CreateMaybeMessage<ObjectStopLine>(NULL);
  }

  ObjectStopLine* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ObjectStopLine>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ObjectStopLine& from);
  void MergeFrom(const ObjectStopLine& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ObjectStopLine* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  typedef ObjectStopLine_StopLineType StopLineType;
  static const StopLineType STOP_LINE_TYPE_UNDEFINED =
    ObjectStopLine_StopLineType_STOP_LINE_TYPE_UNDEFINED;
  static const StopLineType STOP_LINE_TYPE_STRAIGHT =
    ObjectStopLine_StopLineType_STOP_LINE_TYPE_STRAIGHT;
  static const StopLineType STOP_LINE_TYPE_TURN =
    ObjectStopLine_StopLineType_STOP_LINE_TYPE_TURN;
  static const StopLineType STOP_LINE_TYPE_BICYCLE =
    ObjectStopLine_StopLineType_STOP_LINE_TYPE_BICYCLE;
  static const StopLineType STOP_LINE_TYPE_MOTORCYCLE =
    ObjectStopLine_StopLineType_STOP_LINE_TYPE_MOTORCYCLE;
  static inline bool StopLineType_IsValid(int value) {
    return ObjectStopLine_StopLineType_IsValid(value);
  }
  static const StopLineType StopLineType_MIN =
    ObjectStopLine_StopLineType_StopLineType_MIN;
  static const StopLineType StopLineType_MAX =
    ObjectStopLine_StopLineType_StopLineType_MAX;
  static const int StopLineType_ARRAYSIZE =
    ObjectStopLine_StopLineType_StopLineType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  StopLineType_descriptor() {
    return ObjectStopLine_StopLineType_descriptor();
  }
  static inline const ::std::string& StopLineType_Name(StopLineType value) {
    return ObjectStopLine_StopLineType_Name(value);
  }
  static inline bool StopLineType_Parse(const ::std::string& name,
      StopLineType* value) {
    return ObjectStopLine_StopLineType_Parse(name, value);
  }

  typedef ObjectStopLine_StopLineStyle StopLineStyle;
  static const StopLineStyle STOP_LINE_STYLE_UNDEFINED =
    ObjectStopLine_StopLineStyle_STOP_LINE_STYLE_UNDEFINED;
  static const StopLineStyle STOP_LINE_STYLE_SINGLE_SOLID_LINE =
    ObjectStopLine_StopLineStyle_STOP_LINE_STYLE_SINGLE_SOLID_LINE;
  static const StopLineStyle STOP_LINE_STYLE_DOUBLE_SOLID_LINE =
    ObjectStopLine_StopLineStyle_STOP_LINE_STYLE_DOUBLE_SOLID_LINE;
  static inline bool StopLineStyle_IsValid(int value) {
    return ObjectStopLine_StopLineStyle_IsValid(value);
  }
  static const StopLineStyle StopLineStyle_MIN =
    ObjectStopLine_StopLineStyle_StopLineStyle_MIN;
  static const StopLineStyle StopLineStyle_MAX =
    ObjectStopLine_StopLineStyle_StopLineStyle_MAX;
  static const int StopLineStyle_ARRAYSIZE =
    ObjectStopLine_StopLineStyle_StopLineStyle_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  StopLineStyle_descriptor() {
    return ObjectStopLine_StopLineStyle_descriptor();
  }
  static inline const ::std::string& StopLineStyle_Name(StopLineStyle value) {
    return ObjectStopLine_StopLineStyle_Name(value);
  }
  static inline bool StopLineStyle_Parse(const ::std::string& name,
      StopLineStyle* value) {
    return ObjectStopLine_StopLineStyle_Parse(name, value);
  }

  typedef ObjectStopLine_StopLineColor StopLineColor;
  static const StopLineColor STOP_LINE_COLOR_UNDEFINED =
    ObjectStopLine_StopLineColor_STOP_LINE_COLOR_UNDEFINED;
  static const StopLineColor STOP_LINE_COLOR_WHITE =
    ObjectStopLine_StopLineColor_STOP_LINE_COLOR_WHITE;
  static const StopLineColor STOP_LINE_COLOR_YELLOW =
    ObjectStopLine_StopLineColor_STOP_LINE_COLOR_YELLOW;
  static inline bool StopLineColor_IsValid(int value) {
    return ObjectStopLine_StopLineColor_IsValid(value);
  }
  static const StopLineColor StopLineColor_MIN =
    ObjectStopLine_StopLineColor_StopLineColor_MIN;
  static const StopLineColor StopLineColor_MAX =
    ObjectStopLine_StopLineColor_StopLineColor_MAX;
  static const int StopLineColor_ARRAYSIZE =
    ObjectStopLine_StopLineColor_StopLineColor_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  StopLineColor_descriptor() {
    return ObjectStopLine_StopLineColor_descriptor();
  }
  static inline const ::std::string& StopLineColor_Name(StopLineColor value) {
    return ObjectStopLine_StopLineColor_Name(value);
  }
  static inline bool StopLineColor_Parse(const ::std::string& name,
      StopLineColor* value) {
    return ObjectStopLine_StopLineColor_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated uint64 tile_ids = 10 [packed = true];
  int tile_ids_size() const;
  void clear_tile_ids();
  static const int kTileIdsFieldNumber = 10;
  ::google::protobuf::uint64 tile_ids(int index) const;
  void set_tile_ids(int index, ::google::protobuf::uint64 value);
  void add_tile_ids(::google::protobuf::uint64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      tile_ids() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_tile_ids();

  // repeated uint64 associated_lane_ids = 11 [packed = true];
  int associated_lane_ids_size() const;
  void clear_associated_lane_ids();
  static const int kAssociatedLaneIdsFieldNumber = 11;
  ::google::protobuf::uint64 associated_lane_ids(int index) const;
  void set_associated_lane_ids(int index, ::google::protobuf::uint64 value);
  void add_associated_lane_ids(::google::protobuf::uint64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      associated_lane_ids() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_associated_lane_ids();

  // repeated uint64 associated_lane_group_ids = 12 [packed = true];
  int associated_lane_group_ids_size() const;
  void clear_associated_lane_group_ids();
  static const int kAssociatedLaneGroupIdsFieldNumber = 12;
  ::google::protobuf::uint64 associated_lane_group_ids(int index) const;
  void set_associated_lane_group_ids(int index, ::google::protobuf::uint64 value);
  void add_associated_lane_group_ids(::google::protobuf::uint64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      associated_lane_group_ids() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_associated_lane_group_ids();

  // repeated .holo.map.proto.common.GeoPoint first_line = 23;
  int first_line_size() const;
  void clear_first_line();
  static const int kFirstLineFieldNumber = 23;
  ::holo::map::proto::common::GeoPoint* mutable_first_line(int index);
  ::google::protobuf::RepeatedPtrField< ::holo::map::proto::common::GeoPoint >*
      mutable_first_line();
  const ::holo::map::proto::common::GeoPoint& first_line(int index) const;
  ::holo::map::proto::common::GeoPoint* add_first_line();
  const ::google::protobuf::RepeatedPtrField< ::holo::map::proto::common::GeoPoint >&
      first_line() const;

  // map<uint32, .holo.map.proto.common.GeoLine> extra_first_line = 24;
  int extra_first_line_size() const;
  void clear_extra_first_line();
  static const int kExtraFirstLineFieldNumber = 24;
  const ::google::protobuf::Map< ::google::protobuf::uint32, ::holo::map::proto::common::GeoLine >&
      extra_first_line() const;
  ::google::protobuf::Map< ::google::protobuf::uint32, ::holo::map::proto::common::GeoLine >*
      mutable_extra_first_line();

  // repeated .holo.map.proto.common.GeoPoint second_line = 25;
  int second_line_size() const;
  void clear_second_line();
  static const int kSecondLineFieldNumber = 25;
  ::holo::map::proto::common::GeoPoint* mutable_second_line(int index);
  ::google::protobuf::RepeatedPtrField< ::holo::map::proto::common::GeoPoint >*
      mutable_second_line();
  const ::holo::map::proto::common::GeoPoint& second_line(int index) const;
  ::holo::map::proto::common::GeoPoint* add_second_line();
  const ::google::protobuf::RepeatedPtrField< ::holo::map::proto::common::GeoPoint >&
      second_line() const;

  // map<uint32, .holo.map.proto.common.GeoLine> extra_second_line = 26;
  int extra_second_line_size() const;
  void clear_extra_second_line();
  static const int kExtraSecondLineFieldNumber = 26;
  const ::google::protobuf::Map< ::google::protobuf::uint32, ::holo::map::proto::common::GeoLine >&
      extra_second_line() const;
  ::google::protobuf::Map< ::google::protobuf::uint32, ::holo::map::proto::common::GeoLine >*
      mutable_extra_second_line();

  // optional .holo.map.proto.common.Coordinate coordinate = 27;
  bool has_coordinate() const;
  void clear_coordinate();
  static const int kCoordinateFieldNumber = 27;
  private:
  const ::holo::map::proto::common::Coordinate& _internal_coordinate() const;
  public:
  const ::holo::map::proto::common::Coordinate& coordinate() const;
  ::holo::map::proto::common::Coordinate* release_coordinate();
  ::holo::map::proto::common::Coordinate* mutable_coordinate();
  void set_allocated_coordinate(::holo::map::proto::common::Coordinate* coordinate);

  // optional uint64 object_stop_line_id = 1;
  bool has_object_stop_line_id() const;
  void clear_object_stop_line_id();
  static const int kObjectStopLineIdFieldNumber = 1;
  ::google::protobuf::uint64 object_stop_line_id() const;
  void set_object_stop_line_id(::google::protobuf::uint64 value);

  // optional .holo.map.proto.base.ObjectStopLine.StopLineType stop_line_type = 2;
  bool has_stop_line_type() const;
  void clear_stop_line_type();
  static const int kStopLineTypeFieldNumber = 2;
  ::holo::map::proto::base::ObjectStopLine_StopLineType stop_line_type() const;
  void set_stop_line_type(::holo::map::proto::base::ObjectStopLine_StopLineType value);

  // optional .holo.map.proto.base.ObjectStopLine.StopLineStyle stop_line_style = 3;
  bool has_stop_line_style() const;
  void clear_stop_line_style();
  static const int kStopLineStyleFieldNumber = 3;
  ::holo::map::proto::base::ObjectStopLine_StopLineStyle stop_line_style() const;
  void set_stop_line_style(::holo::map::proto::base::ObjectStopLine_StopLineStyle value);

  // optional .holo.map.proto.base.ObjectStopLine.StopLineColor stop_line_color = 4;
  bool has_stop_line_color() const;
  void clear_stop_line_color();
  static const int kStopLineColorFieldNumber = 4;
  ::holo::map::proto::base::ObjectStopLine_StopLineColor stop_line_color() const;
  void set_stop_line_color(::holo::map::proto::base::ObjectStopLine_StopLineColor value);

  // optional uint32 zone_id = 20;
  bool has_zone_id() const;
  void clear_zone_id();
  static const int kZoneIdFieldNumber = 20;
  ::google::protobuf::uint32 zone_id() const;
  void set_zone_id(::google::protobuf::uint32 value);

  // optional uint32 extra_zone_id = 21;
  bool has_extra_zone_id() const;
  void clear_extra_zone_id();
  static const int kExtraZoneIdFieldNumber = 21;
  ::google::protobuf::uint32 extra_zone_id() const;
  void set_extra_zone_id(::google::protobuf::uint32 value);

  // optional bool south_flag = 22;
  bool has_south_flag() const;
  void clear_south_flag();
  static const int kSouthFlagFieldNumber = 22;
  bool south_flag() const;
  void set_south_flag(bool value);

  // @@protoc_insertion_point(class_scope:holo.map.proto.base.ObjectStopLine)
 private:
  void set_has_object_stop_line_id();
  void clear_has_object_stop_line_id();
  void set_has_stop_line_type();
  void clear_has_stop_line_type();
  void set_has_stop_line_style();
  void clear_has_stop_line_style();
  void set_has_stop_line_color();
  void clear_has_stop_line_color();
  void set_has_zone_id();
  void clear_has_zone_id();
  void set_has_extra_zone_id();
  void clear_has_extra_zone_id();
  void set_has_south_flag();
  void clear_has_south_flag();
  void set_has_coordinate();
  void clear_has_coordinate();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > tile_ids_;
  mutable int _tile_ids_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > associated_lane_ids_;
  mutable int _associated_lane_ids_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > associated_lane_group_ids_;
  mutable int _associated_lane_group_ids_cached_byte_size_;
  ::google::protobuf::RepeatedPtrField< ::holo::map::proto::common::GeoPoint > first_line_;
  ::google::protobuf::internal::MapField<
      ObjectStopLine_ExtraFirstLineEntry_DoNotUse,
      ::google::protobuf::uint32, ::holo::map::proto::common::GeoLine,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > extra_first_line_;
  ::google::protobuf::RepeatedPtrField< ::holo::map::proto::common::GeoPoint > second_line_;
  ::google::protobuf::internal::MapField<
      ObjectStopLine_ExtraSecondLineEntry_DoNotUse,
      ::google::protobuf::uint32, ::holo::map::proto::common::GeoLine,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > extra_second_line_;
  ::holo::map::proto::common::Coordinate* coordinate_;
  ::google::protobuf::uint64 object_stop_line_id_;
  int stop_line_type_;
  int stop_line_style_;
  int stop_line_color_;
  ::google::protobuf::uint32 zone_id_;
  ::google::protobuf::uint32 extra_zone_id_;
  bool south_flag_;
  friend struct ::protobuf_holo_2fmap_2fproto_2fbase_2fobject_5fstop_5fline_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// ObjectStopLine

// optional uint64 object_stop_line_id = 1;
inline bool ObjectStopLine::has_object_stop_line_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ObjectStopLine::set_has_object_stop_line_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ObjectStopLine::clear_has_object_stop_line_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ObjectStopLine::clear_object_stop_line_id() {
  object_stop_line_id_ = GOOGLE_ULONGLONG(0);
  clear_has_object_stop_line_id();
}
inline ::google::protobuf::uint64 ObjectStopLine::object_stop_line_id() const {
  // @@protoc_insertion_point(field_get:holo.map.proto.base.ObjectStopLine.object_stop_line_id)
  return object_stop_line_id_;
}
inline void ObjectStopLine::set_object_stop_line_id(::google::protobuf::uint64 value) {
  set_has_object_stop_line_id();
  object_stop_line_id_ = value;
  // @@protoc_insertion_point(field_set:holo.map.proto.base.ObjectStopLine.object_stop_line_id)
}

// optional .holo.map.proto.base.ObjectStopLine.StopLineType stop_line_type = 2;
inline bool ObjectStopLine::has_stop_line_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ObjectStopLine::set_has_stop_line_type() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ObjectStopLine::clear_has_stop_line_type() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ObjectStopLine::clear_stop_line_type() {
  stop_line_type_ = 0;
  clear_has_stop_line_type();
}
inline ::holo::map::proto::base::ObjectStopLine_StopLineType ObjectStopLine::stop_line_type() const {
  // @@protoc_insertion_point(field_get:holo.map.proto.base.ObjectStopLine.stop_line_type)
  return static_cast< ::holo::map::proto::base::ObjectStopLine_StopLineType >(stop_line_type_);
}
inline void ObjectStopLine::set_stop_line_type(::holo::map::proto::base::ObjectStopLine_StopLineType value) {
  assert(::holo::map::proto::base::ObjectStopLine_StopLineType_IsValid(value));
  set_has_stop_line_type();
  stop_line_type_ = value;
  // @@protoc_insertion_point(field_set:holo.map.proto.base.ObjectStopLine.stop_line_type)
}

// optional .holo.map.proto.base.ObjectStopLine.StopLineStyle stop_line_style = 3;
inline bool ObjectStopLine::has_stop_line_style() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ObjectStopLine::set_has_stop_line_style() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ObjectStopLine::clear_has_stop_line_style() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ObjectStopLine::clear_stop_line_style() {
  stop_line_style_ = 0;
  clear_has_stop_line_style();
}
inline ::holo::map::proto::base::ObjectStopLine_StopLineStyle ObjectStopLine::stop_line_style() const {
  // @@protoc_insertion_point(field_get:holo.map.proto.base.ObjectStopLine.stop_line_style)
  return static_cast< ::holo::map::proto::base::ObjectStopLine_StopLineStyle >(stop_line_style_);
}
inline void ObjectStopLine::set_stop_line_style(::holo::map::proto::base::ObjectStopLine_StopLineStyle value) {
  assert(::holo::map::proto::base::ObjectStopLine_StopLineStyle_IsValid(value));
  set_has_stop_line_style();
  stop_line_style_ = value;
  // @@protoc_insertion_point(field_set:holo.map.proto.base.ObjectStopLine.stop_line_style)
}

// optional .holo.map.proto.base.ObjectStopLine.StopLineColor stop_line_color = 4;
inline bool ObjectStopLine::has_stop_line_color() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ObjectStopLine::set_has_stop_line_color() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ObjectStopLine::clear_has_stop_line_color() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ObjectStopLine::clear_stop_line_color() {
  stop_line_color_ = 0;
  clear_has_stop_line_color();
}
inline ::holo::map::proto::base::ObjectStopLine_StopLineColor ObjectStopLine::stop_line_color() const {
  // @@protoc_insertion_point(field_get:holo.map.proto.base.ObjectStopLine.stop_line_color)
  return static_cast< ::holo::map::proto::base::ObjectStopLine_StopLineColor >(stop_line_color_);
}
inline void ObjectStopLine::set_stop_line_color(::holo::map::proto::base::ObjectStopLine_StopLineColor value) {
  assert(::holo::map::proto::base::ObjectStopLine_StopLineColor_IsValid(value));
  set_has_stop_line_color();
  stop_line_color_ = value;
  // @@protoc_insertion_point(field_set:holo.map.proto.base.ObjectStopLine.stop_line_color)
}

// repeated uint64 tile_ids = 10 [packed = true];
inline int ObjectStopLine::tile_ids_size() const {
  return tile_ids_.size();
}
inline void ObjectStopLine::clear_tile_ids() {
  tile_ids_.Clear();
}
inline ::google::protobuf::uint64 ObjectStopLine::tile_ids(int index) const {
  // @@protoc_insertion_point(field_get:holo.map.proto.base.ObjectStopLine.tile_ids)
  return tile_ids_.Get(index);
}
inline void ObjectStopLine::set_tile_ids(int index, ::google::protobuf::uint64 value) {
  tile_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:holo.map.proto.base.ObjectStopLine.tile_ids)
}
inline void ObjectStopLine::add_tile_ids(::google::protobuf::uint64 value) {
  tile_ids_.Add(value);
  // @@protoc_insertion_point(field_add:holo.map.proto.base.ObjectStopLine.tile_ids)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
ObjectStopLine::tile_ids() const {
  // @@protoc_insertion_point(field_list:holo.map.proto.base.ObjectStopLine.tile_ids)
  return tile_ids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
ObjectStopLine::mutable_tile_ids() {
  // @@protoc_insertion_point(field_mutable_list:holo.map.proto.base.ObjectStopLine.tile_ids)
  return &tile_ids_;
}

// repeated uint64 associated_lane_ids = 11 [packed = true];
inline int ObjectStopLine::associated_lane_ids_size() const {
  return associated_lane_ids_.size();
}
inline void ObjectStopLine::clear_associated_lane_ids() {
  associated_lane_ids_.Clear();
}
inline ::google::protobuf::uint64 ObjectStopLine::associated_lane_ids(int index) const {
  // @@protoc_insertion_point(field_get:holo.map.proto.base.ObjectStopLine.associated_lane_ids)
  return associated_lane_ids_.Get(index);
}
inline void ObjectStopLine::set_associated_lane_ids(int index, ::google::protobuf::uint64 value) {
  associated_lane_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:holo.map.proto.base.ObjectStopLine.associated_lane_ids)
}
inline void ObjectStopLine::add_associated_lane_ids(::google::protobuf::uint64 value) {
  associated_lane_ids_.Add(value);
  // @@protoc_insertion_point(field_add:holo.map.proto.base.ObjectStopLine.associated_lane_ids)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
ObjectStopLine::associated_lane_ids() const {
  // @@protoc_insertion_point(field_list:holo.map.proto.base.ObjectStopLine.associated_lane_ids)
  return associated_lane_ids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
ObjectStopLine::mutable_associated_lane_ids() {
  // @@protoc_insertion_point(field_mutable_list:holo.map.proto.base.ObjectStopLine.associated_lane_ids)
  return &associated_lane_ids_;
}

// repeated uint64 associated_lane_group_ids = 12 [packed = true];
inline int ObjectStopLine::associated_lane_group_ids_size() const {
  return associated_lane_group_ids_.size();
}
inline void ObjectStopLine::clear_associated_lane_group_ids() {
  associated_lane_group_ids_.Clear();
}
inline ::google::protobuf::uint64 ObjectStopLine::associated_lane_group_ids(int index) const {
  // @@protoc_insertion_point(field_get:holo.map.proto.base.ObjectStopLine.associated_lane_group_ids)
  return associated_lane_group_ids_.Get(index);
}
inline void ObjectStopLine::set_associated_lane_group_ids(int index, ::google::protobuf::uint64 value) {
  associated_lane_group_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:holo.map.proto.base.ObjectStopLine.associated_lane_group_ids)
}
inline void ObjectStopLine::add_associated_lane_group_ids(::google::protobuf::uint64 value) {
  associated_lane_group_ids_.Add(value);
  // @@protoc_insertion_point(field_add:holo.map.proto.base.ObjectStopLine.associated_lane_group_ids)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
ObjectStopLine::associated_lane_group_ids() const {
  // @@protoc_insertion_point(field_list:holo.map.proto.base.ObjectStopLine.associated_lane_group_ids)
  return associated_lane_group_ids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
ObjectStopLine::mutable_associated_lane_group_ids() {
  // @@protoc_insertion_point(field_mutable_list:holo.map.proto.base.ObjectStopLine.associated_lane_group_ids)
  return &associated_lane_group_ids_;
}

// optional uint32 zone_id = 20;
inline bool ObjectStopLine::has_zone_id() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void ObjectStopLine::set_has_zone_id() {
  _has_bits_[0] |= 0x00000020u;
}
inline void ObjectStopLine::clear_has_zone_id() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void ObjectStopLine::clear_zone_id() {
  zone_id_ = 0u;
  clear_has_zone_id();
}
inline ::google::protobuf::uint32 ObjectStopLine::zone_id() const {
  // @@protoc_insertion_point(field_get:holo.map.proto.base.ObjectStopLine.zone_id)
  return zone_id_;
}
inline void ObjectStopLine::set_zone_id(::google::protobuf::uint32 value) {
  set_has_zone_id();
  zone_id_ = value;
  // @@protoc_insertion_point(field_set:holo.map.proto.base.ObjectStopLine.zone_id)
}

// optional uint32 extra_zone_id = 21;
inline bool ObjectStopLine::has_extra_zone_id() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void ObjectStopLine::set_has_extra_zone_id() {
  _has_bits_[0] |= 0x00000040u;
}
inline void ObjectStopLine::clear_has_extra_zone_id() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void ObjectStopLine::clear_extra_zone_id() {
  extra_zone_id_ = 0u;
  clear_has_extra_zone_id();
}
inline ::google::protobuf::uint32 ObjectStopLine::extra_zone_id() const {
  // @@protoc_insertion_point(field_get:holo.map.proto.base.ObjectStopLine.extra_zone_id)
  return extra_zone_id_;
}
inline void ObjectStopLine::set_extra_zone_id(::google::protobuf::uint32 value) {
  set_has_extra_zone_id();
  extra_zone_id_ = value;
  // @@protoc_insertion_point(field_set:holo.map.proto.base.ObjectStopLine.extra_zone_id)
}

// optional bool south_flag = 22;
inline bool ObjectStopLine::has_south_flag() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void ObjectStopLine::set_has_south_flag() {
  _has_bits_[0] |= 0x00000080u;
}
inline void ObjectStopLine::clear_has_south_flag() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void ObjectStopLine::clear_south_flag() {
  south_flag_ = false;
  clear_has_south_flag();
}
inline bool ObjectStopLine::south_flag() const {
  // @@protoc_insertion_point(field_get:holo.map.proto.base.ObjectStopLine.south_flag)
  return south_flag_;
}
inline void ObjectStopLine::set_south_flag(bool value) {
  set_has_south_flag();
  south_flag_ = value;
  // @@protoc_insertion_point(field_set:holo.map.proto.base.ObjectStopLine.south_flag)
}

// repeated .holo.map.proto.common.GeoPoint first_line = 23;
inline int ObjectStopLine::first_line_size() const {
  return first_line_.size();
}
inline ::holo::map::proto::common::GeoPoint* ObjectStopLine::mutable_first_line(int index) {
  // @@protoc_insertion_point(field_mutable:holo.map.proto.base.ObjectStopLine.first_line)
  return first_line_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::holo::map::proto::common::GeoPoint >*
ObjectStopLine::mutable_first_line() {
  // @@protoc_insertion_point(field_mutable_list:holo.map.proto.base.ObjectStopLine.first_line)
  return &first_line_;
}
inline const ::holo::map::proto::common::GeoPoint& ObjectStopLine::first_line(int index) const {
  // @@protoc_insertion_point(field_get:holo.map.proto.base.ObjectStopLine.first_line)
  return first_line_.Get(index);
}
inline ::holo::map::proto::common::GeoPoint* ObjectStopLine::add_first_line() {
  // @@protoc_insertion_point(field_add:holo.map.proto.base.ObjectStopLine.first_line)
  return first_line_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::holo::map::proto::common::GeoPoint >&
ObjectStopLine::first_line() const {
  // @@protoc_insertion_point(field_list:holo.map.proto.base.ObjectStopLine.first_line)
  return first_line_;
}

// map<uint32, .holo.map.proto.common.GeoLine> extra_first_line = 24;
inline int ObjectStopLine::extra_first_line_size() const {
  return extra_first_line_.size();
}
inline const ::google::protobuf::Map< ::google::protobuf::uint32, ::holo::map::proto::common::GeoLine >&
ObjectStopLine::extra_first_line() const {
  // @@protoc_insertion_point(field_map:holo.map.proto.base.ObjectStopLine.extra_first_line)
  return extra_first_line_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::uint32, ::holo::map::proto::common::GeoLine >*
ObjectStopLine::mutable_extra_first_line() {
  // @@protoc_insertion_point(field_mutable_map:holo.map.proto.base.ObjectStopLine.extra_first_line)
  return extra_first_line_.MutableMap();
}

// repeated .holo.map.proto.common.GeoPoint second_line = 25;
inline int ObjectStopLine::second_line_size() const {
  return second_line_.size();
}
inline ::holo::map::proto::common::GeoPoint* ObjectStopLine::mutable_second_line(int index) {
  // @@protoc_insertion_point(field_mutable:holo.map.proto.base.ObjectStopLine.second_line)
  return second_line_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::holo::map::proto::common::GeoPoint >*
ObjectStopLine::mutable_second_line() {
  // @@protoc_insertion_point(field_mutable_list:holo.map.proto.base.ObjectStopLine.second_line)
  return &second_line_;
}
inline const ::holo::map::proto::common::GeoPoint& ObjectStopLine::second_line(int index) const {
  // @@protoc_insertion_point(field_get:holo.map.proto.base.ObjectStopLine.second_line)
  return second_line_.Get(index);
}
inline ::holo::map::proto::common::GeoPoint* ObjectStopLine::add_second_line() {
  // @@protoc_insertion_point(field_add:holo.map.proto.base.ObjectStopLine.second_line)
  return second_line_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::holo::map::proto::common::GeoPoint >&
ObjectStopLine::second_line() const {
  // @@protoc_insertion_point(field_list:holo.map.proto.base.ObjectStopLine.second_line)
  return second_line_;
}

// map<uint32, .holo.map.proto.common.GeoLine> extra_second_line = 26;
inline int ObjectStopLine::extra_second_line_size() const {
  return extra_second_line_.size();
}
inline const ::google::protobuf::Map< ::google::protobuf::uint32, ::holo::map::proto::common::GeoLine >&
ObjectStopLine::extra_second_line() const {
  // @@protoc_insertion_point(field_map:holo.map.proto.base.ObjectStopLine.extra_second_line)
  return extra_second_line_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::uint32, ::holo::map::proto::common::GeoLine >*
ObjectStopLine::mutable_extra_second_line() {
  // @@protoc_insertion_point(field_mutable_map:holo.map.proto.base.ObjectStopLine.extra_second_line)
  return extra_second_line_.MutableMap();
}

// optional .holo.map.proto.common.Coordinate coordinate = 27;
inline bool ObjectStopLine::has_coordinate() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ObjectStopLine::set_has_coordinate() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ObjectStopLine::clear_has_coordinate() {
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::holo::map::proto::common::Coordinate& ObjectStopLine::_internal_coordinate() const {
  return *coordinate_;
}
inline const ::holo::map::proto::common::Coordinate& ObjectStopLine::coordinate() const {
  const ::holo::map::proto::common::Coordinate* p = coordinate_;
  // @@protoc_insertion_point(field_get:holo.map.proto.base.ObjectStopLine.coordinate)
  return p != NULL ? *p : *reinterpret_cast<const ::holo::map::proto::common::Coordinate*>(
      &::holo::map::proto::common::_Coordinate_default_instance_);
}
inline ::holo::map::proto::common::Coordinate* ObjectStopLine::release_coordinate() {
  // @@protoc_insertion_point(field_release:holo.map.proto.base.ObjectStopLine.coordinate)
  clear_has_coordinate();
  ::holo::map::proto::common::Coordinate* temp = coordinate_;
  coordinate_ = NULL;
  return temp;
}
inline ::holo::map::proto::common::Coordinate* ObjectStopLine::mutable_coordinate() {
  set_has_coordinate();
  if (coordinate_ == NULL) {
    auto* p = CreateMaybeMessage<::holo::map::proto::common::Coordinate>(GetArenaNoVirtual());
    coordinate_ = p;
  }
  // @@protoc_insertion_point(field_mutable:holo.map.proto.base.ObjectStopLine.coordinate)
  return coordinate_;
}
inline void ObjectStopLine::set_allocated_coordinate(::holo::map::proto::common::Coordinate* coordinate) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(coordinate_);
  }
  if (coordinate) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      coordinate = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, coordinate, submessage_arena);
    }
    set_has_coordinate();
  } else {
    clear_has_coordinate();
  }
  coordinate_ = coordinate;
  // @@protoc_insertion_point(field_set_allocated:holo.map.proto.base.ObjectStopLine.coordinate)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace base
}  // namespace proto
}  // namespace map
}  // namespace holo

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::holo::map::proto::base::ObjectStopLine_StopLineType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::holo::map::proto::base::ObjectStopLine_StopLineType>() {
  return ::holo::map::proto::base::ObjectStopLine_StopLineType_descriptor();
}
template <> struct is_proto_enum< ::holo::map::proto::base::ObjectStopLine_StopLineStyle> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::holo::map::proto::base::ObjectStopLine_StopLineStyle>() {
  return ::holo::map::proto::base::ObjectStopLine_StopLineStyle_descriptor();
}
template <> struct is_proto_enum< ::holo::map::proto::base::ObjectStopLine_StopLineColor> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::holo::map::proto::base::ObjectStopLine_StopLineColor>() {
  return ::holo::map::proto::base::ObjectStopLine_StopLineColor_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_holo_2fmap_2fproto_2fbase_2fobject_5fstop_5fline_2eproto
