#ifndef OPENDDS_WRAPPER_BUILTIN_BUILTIN_IDL_
#define OPENDDS_WRAPPER_BUILTIN_BUILTIN_IDL_

module opendds_wrapper
{

struct BuiltinTimestamp
{
    unsigned long sec;
    unsigned long nsec;
};

// @topic
#pragma DCPS_DATA_TYPE "opendds_wrapper::BuiltinUint8"
struct BuiltinUint8
{
    octet value;
};

// @topic
#pragma DCPS_DATA_TYPE "opendds_wrapper::BuiltinUint16"
struct BuiltinUint16
{
    unsigned short value;
};

// @topic
#pragma DCPS_DATA_TYPE "opendds_wrapper::BuiltinUint32"
struct BuiltinUint32
{
    unsigned long value;
};

// @topic
#pragma DCPS_DATA_TYPE "opendds_wrapper::BuiltinUint64"
struct BuiltinUint64
{
    unsigned long long value;
};

// @topic
#pragma DCPS_DATA_TYPE "opendds_wrapper::BuiltinFloat32"
struct BuiltinFloat32
{
    float value;
};

// @topic
#pragma DCPS_DATA_TYPE "opendds_wrapper::BuiltinFloat64"
struct BuiltinFloat64
{
    double value;
};

// @topic
#pragma DCPS_DATA_TYPE "opendds_wrapper::BuiltinString"
struct BuiltinString
{
    string value;
};

typedef sequence<octet> OctetSequence;

// @topic
#pragma DCPS_DATA_TYPE "opendds_wrapper::BuiltinBuffer"
struct BuiltinBuffer
{
    OctetSequence value;
};

};

#endif
