base:
- BaseCamp/Application/Dev/release/2021.12
projects:
  # BaseCampLib
  holo_base:
    branch: feature/tmp/gh02_interface
  holo_cmw:
    branch: feature/mdc_cm
    commands:
      configure:
        arguments:
        - -DHOLO_CMW_BUILD_ROS_WRAPPER=OFF
        - -DHOLO_CMW_BUILD_OPENDDS_WRAPPER=OFF
        - -DHOLO_CMW_BUILD_UMB_WRAPPER=OFF
        - -DHOLO_CMW_BUILD_MDC_CM_WRAPPER=ON
        - ${SOURCE_ROOT}
  holo_base_msg:
    branch: feature/GH02/0930

  # BaseCampApp
  holo_map_adapter/cmw_app:
    dependencies:
    - CS
    - MAP
    - gh02_msg
  holo_map_local_service_server:
    url: ${git_url}/map/holo_map_local_service_server.git
    branch: release/GH02/20220112
    dependencies:
    - CS
    - MAP
    - gh02_msg
    commands:
      configure:
        arguments:
          - -DHOLO_BUILD_WITH_GH02_MSG=ON
          - ${SOURCE_ROOT}
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_map_local_service_client:
    branch: release/GH02/20220112
    commands:
      configure:
        arguments:
          - -DHOLO_BUILD_FOR_URBAN_PILOT=ON
          - ${SOURCE_ROOT}
  holo_map_local_service_client/tools:
    url: holo_map_local_service_client/tools
    branch: release/GH02/20220112
    dependencies:
    - CS
    - MAP
    - gh02_msg
    commands:
      configure:
        arguments:
          - -DHOLO_BUILD_WITH_GH02_MSG=ON
          - ${SOURCE_ROOT}
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_vision_cmw_app:
    branch: release/v0.1
  holo_localization_semantic:
    branch: release/GH02/20220112
  holo_localization_base:
    branch: release/GH02/20220112
  holo_localization_fusion:
    branch: release/GH02/20220112
  holo_localization_fusion_cmw_app:
    branch: release/GH02/20220112
    dependencies:
    - CS
    - MLC
    - MAP
    - gh02_msg
  holo_sensors_c:
    branch: release/GH02/20220112
  holo_sensors_base:
    branch: release/GH02/20220112
  holo_sensors_cmw_app:
    branch: release/GH02/20220112
    dependencies:
        - CS
        - VS
        - gh02_msg
  holo_dnn_mdc:
    branch: release/GH02/20220112
  holo_dnn_base:
    branch: release/GH02/20220112
  holo_perception_base:
    branch: release/GH02/20220112
  holo_perception_pilot:
    branch: release/GH02/20220112
    dependencies:
    - CS
    - PER
    - holo_3d
    - gh02_msg
    - holo_dnn_base/apps
    - holo_map_local_service_client
    commands:
      configure:
        arguments:
        - -DHOLO_BUILD_MDC_CM_APP=ON
        - -DHOLO_BUILD_MAP_SDK=ON
        - ${SOURCE_ROOT}
  holo_perception_pilot/cmw_app:
    url: holo_perception_pilot/cmw_app
    dependencies:
    - PER
    - VS
    - holo_perception_pilot
    commands:
      configure:
        arguments:
        - -DHOLO_BUILD_MDC_CM_APP=ON
        - -DHOLO_BUILD_MAP_SDK=ON
        - ${SOURCE_ROOT}
  holo_control_base:
    branch: release/GH02/20220112
  holo_control_cmw_app:
    branch: release/GH02/20220112
    dependencies:
    - CS
    - PC
    - gh02_msg
  holo_map_navigator:
    url: ${git_url}/map/holo_map_navigator.git
    branch: release/GH02/20220112
    dependencies:
    - CS
    - MAP
    - gh02_msg
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_map_navigator_cmw_app:
    url: ${git_url}/map/holo_map_navigator_cmw_app.git
    branch: release/GH02/20220112
    dependencies:
    - CS
    - MAP
    - holo_map_navigator
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  # CustomProject
  gh02_msg:
    url: ${git_url}/gh/gh02_msg.git
    branch: release/GH02/20220112
    dependencies:
    - holo_base
    - holo_cmw
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      configure:
        arguments:
        - -DHOLO_BUILD_CM_TRAITS=ON
        - ${SOURCE_ROOT}
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  gh02_c:
    url: ${git_url}/gh/gh02_c.git
    branch: release/GH02/20220112
    dependencies:
    - holo_base_c
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  gh02_sensors:
    url: ${git_url}/gh/gh02_sensors.git
    branch: release/GH02/20220112
    dependencies:
    - holo_base
    - holo_sensors_base
    - holo_cmw
    - gh02_c
    - gh02_msg
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  gh02_automaton:
    url: ${git_url}/gh/gh02_automaton.git
    branch: release/GH02/20220112
    dependencies:
    - holo_base
    - holo_base_msg
    - holo_cmw
    - gh02_c
    - gh02_msg
    commands:
      configure:
        arguments:
        - -DHOLO_BUILD_GAC_AUTOMATON=OFF
        - ${SOURCE_ROOT}
      test:
        command: make
        arguments:
        - test
        - "||"
        - "true"
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  gh02_cid:
    url: ${git_url}/gh/gh02_cid.git
    branch: release/GH02/20220112
    dependencies:
    - holo_base
    - holo_base_msg
    - holo_sensors_base
    - holo_cmw
    - gh02_c
    - gh02_msg
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_vehicles:
    url: ${git_url}/bcvs/holo_vehicles.git
    branch: release/GH02/20220112
    dependencies:
    - holo_base
    - holo_base_msg
    - holo_cmw
    - holo_sensors_base
    - gh02_c
    - gh02_msg
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []            
  holo_prediction:
    url: ${git_url}/pc/holo_prediction.git
    branch: release/GH02/20220112
    dependencies:
    - holo_base
    - gh02_msg
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_prediction/cmw_app:
    url: holo_prediction/cmw_app
    dependencies:
    - holo_base
    - holo_base_msg
    - holo_cmw
    - gh02_msg
    - holo_prediction
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_planning_base:
    url: ${git_url}/pc/holo_planning_base.git
    branch: release/GH02/20220112
    dependencies:
    - CS
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_planning_pilot:
    url: ${git_url}/pc/holo_planning_pilot.git
    branch: release/GH02/20220112
    dependencies:
    - holo_base
    - holo_planning_base
    - gh02_msg
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_planning_pilot/cmw_app:
    url: holo_planning_pilot/cmw_app
    dependencies:
    - holo_planning_pilot
    - holo_cmw
    - holo_base_msg
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  ######### remove when wh01 merge to holo_base
  holo_x_client:
    commands:
      configure:
        arguments:
        - -DUSE_OPENDDS_WARPPER=OFF
        - -DUSE_MDC_CM_WARPPER=ON
        - ${SOURCE_ROOT}
    url: ${git_url}/sim/holo_x_client.git
    branch: release/GH02/20220112
    dependencies:
    - holo_utils
    - holo_base_c
    - holo_base
    - holo_cmw
    - holo_base_msg
    - holo_sensors_base
    - gh02_msg
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_map_fusion:
    url: ${git_url}/gh/holo_map_fusion.git
    branch: release/GH02/20220112
    dependencies:
    - holo_base
    - gh02_msg
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_map_base:
    branch: release/GH02/20220112
  holo_map_format:
    branch: release/GH02/20220112
  holo_map_common:
    branch: release/GH02/20220112
  holo_map_adapter:
    branch: release/GH02/20220112
  holo_map_cmw_app:
    url: ${git_url}/map/holo_map_cmw_app.git
    branch: release/GH02/20220112
    dependencies:
    - holo_base
    - holo_cmw
    - holo_map_fusion
    - gh02_msg
    commands:
      doc:
        command: make
        arguments:
        - doc
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  ######## debug tool, remove later
  holo_pctoolkits:
    url: ${git_url}/pc/holo_pctoolkits.git
    branch: dragonglass-develop
    dependencies:
    - CS
    - PC
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_pctoolkits/cmw_app:
    url: holo_pctoolkits/cmw_app
    dependencies:
    - CS
    - PC
    - holo_pctoolkits
    - gh02_msg
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  GH02:
    dependencies:
    - holo_map_adapter/cmw_app
    - holo_map_local_service_server
    - holo_map_local_service_client/tools
    - holo_localization_fusion_cmw_app
    - holo_sensors_cmw_app
    - holo_perception_pilot/cmw_app
    - holo_prediction/cmw_app
    - holo_planning_pilot/cmw_app
    - holo_control_cmw_app
    - holo_map_navigator_cmw_app # temporary include
    - gh02_sensors
    - gh02_automaton
    - gh02_cid
    - holo_map_cmw_app
    - holo_x_client
    - holo_vehicles
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
  holo_params:
    url: ${git_url}/vs/holo_params.git
    branch: release/GH02/20220112
    commands:
      configure:
        command: 'cmake'
        arguments:
        - -DVID=aionlx-up-1
        - ${SOURCE_ROOT}
        retcode: [0]
    steps:
        - configure
        - build
        - install
    package:
        manifest: ${BUILD_ROOT}/install_manifest.txt
        files: []
        directories: []
