#ifndef HOLO_BASE_MSG_COMMON_COMMON_IDL_
#define HOLO_BASE_MSG_COMMON_COMMON_IDL_

#include <holo_base_msg/core/Types.idl>

module holo_base_msg { module common {

typedef holo_base_msg::core::uint32_t Coordinate;

typedef holo_base_msg::core::uint32_t SensorId;

typedef holo_base_msg::core::uint32_t Classification;

struct Duration
{
    holo_base_msg::core::int32_t     sec;
    holo_base_msg::core::uint32_t    nsec;
};

struct Timestamp
{
    holo_base_msg::core::uint32_t    sec;
    holo_base_msg::core::uint32_t    nsec;
};

}; };

#endif

