#ifndef HOLO_BASE_MSG_COMMON_IMU_IDL_
#define HOLO_BASE_MSG_COMMON_IMU_IDL_

#include <holo_base_msg/common/Common.idl>
#include <holo_base_msg/numerics/Vector.idl>

module holo_base_msg { module common {

typedef holo_base_msg::core::uint32_t ImuStatus;

#pragma DCPS_DATA_TYPE "holo_base_msg::common::Imuf"
struct Imuf
{
    Timestamp    stamp;
    Coordinate   coord;
    holo_base_msg::numerics::Vector3f   angular_velocity;
    holo_base_msg::numerics::Vector3f   linear_acceleration;
    ImuStatus    status;
};

#pragma DCPS_DATA_TYPE "holo_base_msg::common::Imud"
struct Imud
{
    Timestamp    stamp;
    Coordinate   coord;
    holo_base_msg::numerics::Vector3d   angular_velocity;
    holo_base_msg::numerics::Vector3d   linear_acceleration;
    ImuStatus    status;
};

#pragma DCPS_DATA_TYPE "holo_base_msg::common::ImuBiasf"
struct ImuBiasf
{
    Timestamp    stamp;
    Coordinate   coord;
    holo_base_msg::numerics::Vector3f   angular_velocity_bias;
    holo_base_msg::numerics::Vector3f   linear_acceleration_bias;
    holo_base_msg::numerics::Vector3f   angular_velocity_bias_cov;
    holo_base_msg::numerics::Vector3f   linear_acceleration_bias_cov;
};

#pragma DCPS_DATA_TYPE "holo_base_msg::common::ImuBiasd"
struct ImuBiasd
{
    Timestamp    stamp;
    Coordinate   coord;
    holo_base_msg::numerics::Vector3d   angular_velocity_bias;
    holo_base_msg::numerics::Vector3d   linear_acceleration_bias;
    holo_base_msg::numerics::Vector3d   angular_velocity_bias_cov;
    holo_base_msg::numerics::Vector3d   linear_acceleration_bias_cov;
};

}; };

#endif

