#ifndef HOLO_BASE_MSG_COMMON_PATH_IDL_
#define HOLO_BASE_MSG_COMMON_PATH_IDL_

#include <holo_base_msg/common/Common.idl>
#include <holo_base_msg/core/Types.idl>
#include <holo_base_msg/geometry/Point.idl>

module holo_base_msg { module common {

struct PathPointf
{
    holo_base_msg::geometry::Point3f    point;
    holo_base_msg::core::float32_t      theta;
    holo_base_msg::core::float32_t      curvature;
    holo_base_msg::core::float32_t      speed;
    holo_base_msg::core::float32_t      acceleration;
};

struct PathPointd
{
    holo_base_msg::geometry::Point3d    point;
    holo_base_msg::core::float64_t      theta;
    holo_base_msg::core::float64_t      curvature;
    holo_base_msg::core::float64_t      speed;
    holo_base_msg::core::float64_t      acceleration;
};

typedef sequence<PathPointf> PathPointfSequence;
typedef sequence<PathPointd> PathPointdSequence;

#pragma DCPS_DATA_TYPE "holo_base_msg::common::Pathf"
struct Pathf
{
    Timestamp                               stamp;
    Coordinate                              coord;
    PathPointfSequence                      point_list;
    holo_base_msg::core::uint32_t             valid_value;
};

#pragma DCPS_DATA_TYPE "holo_base_msg::common::Pathd"
struct Pathd
{
    Timestamp                               stamp;
    Coordinate                              coord;
    PathPointdSequence                      point_list;
    holo_base_msg::core::uint32_t             valid_value;
};

}; };

#endif
