#ifndef HOLO_BASE_MSG_COMMON_VEHPOS_IDL_
#define HOLO_BASE_MSG_COMMON_VEHPOS_IDL_

#include <holo_base_msg/common/Common.idl>
#include <holo_base_msg/core/Types.idl>

module holo_base_msg
{
    module common
    {
#pragma DCPS_DATA_TYPE "holo_base_msg::common::VehPosX3V"
        struct VehPosX3V
        {
            holo_base_msg::core::float32_t curv;
            holo_base_msg::core::float32_t vehPos_X;
            holo_base_msg::core::float32_t vehPos_Y;
            holo_base_msg::core::float32_t vehPos_Yaw;
            holo_base_msg::core::float32_t vehPosPred_X;
            holo_base_msg::core::float32_t vehPosPred_Y;
            holo_base_msg::core::float32_t vehPosPred_Yaw;
            holo_base_msg::core::uint8_t   vehStatus;
        };
    };
};

#endif
