#ifndef HOLO_BASE_MSG_GEOMETRY_POSE_IDL_
#define HOLO_BASE_MSG_GEOMETRY_POSE_IDL_

#include <holo_base_msg/geometry/Rot.idl>
#include <holo_base_msg/geometry/Point.idl>

module holo_base_msg { module geometry {

struct Pose3f
{
    Rot3f      rotation;       // 3D pose
    Point3f    translation;    // 3D position
};

struct Pose3d
{
    Rot3d      rotation;       // 3D pose
    Point3d    translation;    // 3D position
};

struct Pose2f
{
    Rot2f      rotation;       // 2D pose
    Point2f    translation;    // 2D position
};

struct Pose2d
{
    Rot2d      rotation;       // 2D pose
    Point2d    translation;    // 2D position
};

}; };

#endif

