base: BaseCamp/Application/GH01/release/2021.09
projects:
  holo_map_base:
    branch: release/dds/2021.11
  holo_map_format:
    branch: release/dds/2021.11
  holo_map_common:
    branch: release/dds/2021.11
  holo_map_adapter:
    branch: release/dds/2021.11
  holo_map_local_service_client:
    branch: release/dds/2021.11
  holo_map_navigator:
    url: ${git_url}/map/holo_map_navigator.git
    branch: release/dds/2021.11
    dependencies:
    - CS
    - holo_map_base
    - holo_map_format
    - holo_map_common
    - holo_map_local_service_client
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  MAP:
    dependencies:
    - holo_map_base
    - holo_map_common
    - holo_map_format
    - holo_map_adapter
    - holo_map_local_service_client
    - holo_map_navigator
  holo_map_navigator_cmw_app:
    url: ${git_url}/map/holo_map_navigator_cmw_app.git
    branch: release/dds/2021.11
    dependencies:
    - CS
    - MAP
    commands:
      test:
        command: make
        arguments:
        - test
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_map_local_service_server:
    branch: release/dds/2021.11
  holo_map_local_service_client/tools:
    branch: release/dds/2021.11
  holo_io:
    url: ${git_url}/base/holo_io.git
    branch: release/dds/2021.11
    dependencies:
    - BaseCamp
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_parking_base:
    url: ${git_url}/parking/holo_parking_base.git
    branch: release/dds/2021.11
    dependencies:
    - BaseCamp
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_parking_msg:
    url: ${git_url}/parking/holo_parking_msg.git
    branch: release/dds/2021.11
    dependencies:
    - BaseCamp
    - holo_parking_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_perception_parking:
    url: ${git_url}/parking/holo_perception_parking.git
    branch: release/dds/2021.11
    dependencies:
    - BaseCamp
    - holo_parking_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_parking:
    url: ${git_url}/parking/holo_localization_parking.git
    branch: release/dds/2021.11
    dependencies:
    - BaseCamp
    - holo_3d
    - holo_io
    - holo_parking_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_3d:
    url: ${git_url}/mlc/holo_3d.git
    branch: release/v0.1
    dependencies:
    - BaseCamp
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_calibration:
    url: ${git_url}/mlc/holo_calibration.git
    branch: release/v0.1
    dependencies:
    - BaseCamp
    - holo_localization_base
    - holo_3d
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_localization_deep:
    url: ${git_url}/mlc/holo_localization_deep.git
    branch: release/dds/2021.11
    dependencies:
    - BaseCamp
    - holo_3d
    - holo_parking_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_planning_parking:
    url: ${git_url}/parking/holo_planning_parking.git
    branch: release/dds/2021.11
    dependencies:
    - BaseCamp
    - holo_io
    - holo_parking_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_control_parking:
    url: ${git_url}/parking/holo_control_parking.git
    branch: release/dds/2021.11
    dependencies:
    - BaseCamp
    - holo_parking_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_parking_cmw_app:
    url: ${git_url}/parking/holo_parking_cmw_app.git
    branch: release/dds/2021.11
    dependencies:
    - BaseCamp
    - holo_parking_msg
    - holo_localization_deep
    - holo_localization_parking
    - holo_perception_parking
    - holo_planning_parking
    - holo_control_parking
    - holo_localization_c
    commands:
      configure:
        arguments:
        - -DHOLO_BUILD_PARKING_APP=ON
        - ${SOURCE_ROOT}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_calibration_cmw_app:
    url: ${git_url}/mlc/holo_calibration_cmw_app.git
    branch: release/v0.1
    dependencies:
    - holo_cmw
    - holo_calibration
    commands:
      configure:
        arguments:
        - ${SOURCE_ROOT}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_x_client:
      url: ssh://git@bitbucket.holomatic.ai:7999/~gaochengbin/holo_x_client.git
      dependencies: [holo_cmw, holo_base_msg, holo_sensors_base, holo_parking_msg]
      branch: release/dds/2021.11
  holo_bag:
    url: ${git_url}/win/holo_bag.git
    branch: release/dds/2021.11
    dependencies:
    - holo_base
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_bag/cmw_app:
    url: holo_bag/cmw_app
    dependencies:
    - holo_bag
    - holo_cmw
    - holo_sensors_base
    - holo_parking_msg
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  odm:
    url: ${git_url}/fun/odm.git
    branch: release/dds/2021.11
    dependencies:
    - BaseCamp
    - holo_parking_base
    commands:
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  odm/cmw_app:
    url: odm/cmw_app
    dependencies:
    - BaseCamp
    - odm
    - holo_parking_msg
    commands: {}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_winterfell:
    url: ${git_url}/win/holo_winterfell.git
    branch: release/dds/2021.11
    dependencies:
    - holo_base
    - holo_bag
    - holo_parking_base
    commands:
      configure:
        arguments:
        - -DHOLO_BUILD_ON_TDA4=ON
        - ${SOURCE_ROOT}
      test:
        command: make
        arguments:
        - test
        - '||'
        - 'true'
      doc:
        command: make
        arguments:
        - doc
      coverage:
        command: make
        arguments:
        - coverage
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_winterfell/cmw_app:
    url: holo_winterfell/cmw_app
    dependencies:
    - holo_winterfell
    - holo_cmw
    - holo_parking_base
    - holo_parking_msg
    commands:
      configure:
        arguments:
        - -DHOLO_BUILD_ON_TDA4=ON
        - ${SOURCE_ROOT}
    steps: null
    package:
      manifest: ${BUILD_ROOT}/install_manifest.txt
      files: []
      directories: []
  holo_params:
    url: ${git_url}/vs/holo_params.git
    branch: release/dds/2021.11
    dependencies: []
    commands:
      build:
        command: ''
        arguments: []
    steps: null
  ParkingBaseCamp:
    dependencies:
    - holo_3rdparty
    - holo_base_c
    - holo_base
    - holo_calibration
    - holo_cmw
    - holo_base_msg
    - holo_sensors_c
    - holo_sensors_base
    - holo_localization_base
    - holo_perception_base
    - holo_planning_base
    - holo_control_base
    - holo_sensors_cmw_app
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
  ParkingApps:
    dependencies:
    - holo_parking_cmw_app
    - holo_calibration_cmw_app
    - holo_map_local_service_server
    - holo_map_navigator_cmw_app
    - odm/cmw_app
    dependencies_x86_64_ubuntu-18.04:
    - holo_parking_cmw_app
    - holo_calibration_cmw_app
    - holo_map_local_service_server
    - holo_map_navigator_cmw_app
    - holo_x_client
    - odm/cmw_app
    dependencies_tda4_qnx-7.0.0:
    - holo_parking_cmw_app
    - holo_calibration_cmw_app
    - holo_map_local_service_server
    - holo_map_navigator_cmw_app
    - holo_bag/cmw_app
    - odm/cmw_app
    - holo_winterfell/cmw_app
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
  ParkingHpp:
    dependencies:
    - ParkingBaseCamp
    - ParkingApps
    commands:
      configure:
        command: ''
        arguments:
        - ${SOURCE_ROOT}
      build:
        command: ''
        arguments: []
      install:
        command: ''
        arguments: []
    steps: null
version: 1
