base:
- Pilot/GH02/develop
projects:
  # BaseCampLib
  holo_map_local_service_client:
    commands:
      configure:
        arguments:
          - -DHOLO_BUILD_FOR_URBAN_PILOT=ON
          - ${SOURCE_ROOT}
  # BaseCampApp
  holo_perception_pilot:
    dependencies:
    - CS
    - PER
    - holo_3d
    - gh02_msg
    - holo_dnn_base/apps
    - holo_map_local_service_client
    commands:
      configure:
        arguments:
        - -DHOLO_BUILD_MDC_CM_APP=ON
        - -DHOLO_BUILD_MAP_SDK=ON
        - ${SOURCE_ROOT}
  holo_perception_pilot/cmw_app:
    commands:
      configure:
        arguments:
        - -DHOLO_BUILD_MDC_CM_APP=ON
        - -DHOLO_BUILD_MAP_SDK=ON
        - ${SOURCE_ROOT}
  holo_params:
    url: ${git_url}/vs/holo_params.git
    branch: dragonglass-develop
    commands:
      configure:
        command: 'cmake'
        arguments:
        - -DVID=aionlx-up-1
        - ${SOURCE_ROOT}
        retcode: [0]
    steps:
        - configure
        - build
        - install
    package:
        manifest: ${BUILD_ROOT}/install_manifest.txt
        files: []
        directories: []
