#ifndef HOLO_PARKING_MSG_PARKING_MANAGER_PARKING_STATE_IDL_
#define HOLO_PARKING_MSG_PARKING_MANAGER_PARKING_STATE_IDL_

#include <holo_parking_msg/common/Common.idl>

module holo_parking_msg
{
    module parking_manager
    {
#pragma DCPS_DATA_TYPE "holo_parking_msg::parking_manager::APAParkingState"

        struct APAParkingState
        {
            holo_parking_msg::common::Timestamp timestamp;
            holo_parking_msg::core::uint8_t  current_state;
            holo_parking_msg::core::uint8_t  last_state;
        };
    };
};

#endif   /// HOLO_PARKING_MSG_PARKING_MANAGER_PARKING_STATE_IDL_
